// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Tracing implementation internals
#include "verilated_vcd_c.h"
#include "Vtop__Syms.h"


VL_ATTR_COLD void Vtop___024root__trace_init_sub__TOP__0(Vtop___024root* vlSelf, VerilatedVcd* tracep) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_init_sub__TOP__0\n"); );
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Init
    const int c = vlSymsp->__Vm_baseCode;
    // Body
    tracep->declBus(c+1,0,"adder.a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+2,0,"adder.b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+3,0,"adder.y",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+4,0,"opb5",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+5,0,"funct3",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBit(c+6,0,"functb5",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+7,0,"aludec.aluop",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+8,0,"alucontrol",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+9,0,"alup.a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+10,0,"alup.b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+11,0,"f",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+12,0,"shamt",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+13,0,"alup.y",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+14,0,"dmem.clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+15,0,"we",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+16,0,"worb",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+17,0,"dmem.a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+18,0,"wd",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+19,0,"dmem.rd",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+20,0,"eqcomp.a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+21,0,"eqcomp.b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+22,0,"eqcomp.y",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+23,0,"instr",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,7);
    tracep->declBus(c+24,0,"extend.immsrc",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+25,0,"immext",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+26,0,"flopenrc.clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+27,0,"flopenrc.rst",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+28,0,"flopenrc.en",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+29,0,"flopenrc.clear",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+30,0,"flopenrc.d",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+31,0,"flopenrc.q",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBit(c+32,0,"flopenr.clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+33,0,"flopenr.rst",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+34,0,"flopenr.en",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+35,0,"flopenr.d",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+36,0,"flopenr.q",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBit(c+37,0,"floprc.clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+38,0,"floprc.rst",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+39,0,"floprc.clear",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+40,0,"floprc.d",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+41,0,"floprc.q",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBit(c+42,0,"flopr.clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+43,0,"flopr.rst",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+44,0,"flopr.d",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+45,0,"flopr.q",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+46,0,"imem.a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+47,0,"imem.rd",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+48,0,"ls2.a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+49,0,"ls2.y",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+50,0,"op",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 6,0);
    tracep->declBus(c+51,0,"resultsrc",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBit(c+52,0,"regwrite",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+53,0,"memwrite",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+54,0,"jump",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+55,0,"branch",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+56,0,"alusrc",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+57,0,"maindec.immsrc",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+58,0,"maindec.aluop",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+59,0,"mux2.a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+60,0,"mux2.b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+61,0,"mux2.sel",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+62,0,"mux2.y",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+63,0,"mux3.a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+64,0,"mux3.b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+65,0,"mux3.c",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+66,0,"mux3.sel",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+67,0,"mux3.y",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+68,0,"mux4.a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+69,0,"mux4.b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+70,0,"mux4.c",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+71,0,"mux4.d",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+72,0,"mux4.sel",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+73,0,"mux4.y",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+74,0,"regfilep.clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+75,0,"we3",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+76,0,"ra1",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+77,0,"ra2",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+78,0,"wa3",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+79,0,"wd3",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+80,0,"rd1",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+81,0,"rd2",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->pushPrefix("adder", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+197,0,"WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+82,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+83,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+84,0,"y",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->popPrefix();
    tracep->pushPrefix("aludec", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+85,0,"opb5",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+86,0,"funct3",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBit(c+87,0,"functb5",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+88,0,"aluop",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+89,0,"alucontrol",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBit(c+90,0,"rsub",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->pushPrefix("alup", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+197,0,"WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+91,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+92,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+93,0,"f",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+94,0,"shamt",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+95,0,"y",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->popPrefix();
    tracep->pushPrefix("dmem", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+197,0,"WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+96,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+97,0,"we",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+98,0,"worb",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+99,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+100,0,"wd",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+101,0,"rd",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->popPrefix();
    tracep->pushPrefix("eqcomp", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+197,0,"WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+102,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+103,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+104,0,"y",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->pushPrefix("extend", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+197,0,"OUTWIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+105,0,"instr",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,7);
    tracep->declBus(c+106,0,"immsrc",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+107,0,"immext",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->popPrefix();
    tracep->pushPrefix("flopenr", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+198,0,"WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+108,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+109,0,"rst",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+110,0,"en",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+111,0,"d",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+112,0,"q",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->popPrefix();
    tracep->pushPrefix("flopenrc", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+198,0,"WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+113,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+114,0,"rst",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+115,0,"en",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+116,0,"clear",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+117,0,"d",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+118,0,"q",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->popPrefix();
    tracep->pushPrefix("flopr", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+198,0,"WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+119,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+120,0,"rst",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+121,0,"d",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+122,0,"q",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->popPrefix();
    tracep->pushPrefix("floprc", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+198,0,"WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+123,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+124,0,"rst",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+125,0,"clear",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+126,0,"d",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+127,0,"q",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->popPrefix();
    tracep->pushPrefix("imem", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+197,0,"WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+128,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+129,0,"rd",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->popPrefix();
    tracep->pushPrefix("ls2", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+197,0,"WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+130,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+131,0,"y",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->popPrefix();
    tracep->pushPrefix("maindec", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+132,0,"op",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 6,0);
    tracep->declBus(c+133,0,"resultsrc",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBit(c+134,0,"regwrite",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+135,0,"memwrite",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+136,0,"jump",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+137,0,"branch",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+138,0,"alusrc",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+139,0,"immsrc",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+140,0,"aluop",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+141,0,"controlsig",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 10,0);
    tracep->popPrefix();
    tracep->pushPrefix("mux2", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+197,0,"WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+142,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+143,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+144,0,"sel",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+145,0,"y",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->popPrefix();
    tracep->pushPrefix("mux3", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+197,0,"WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+146,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+147,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+148,0,"c",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+149,0,"sel",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+150,0,"y",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->popPrefix();
    tracep->pushPrefix("mux4", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+197,0,"WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+151,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+152,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+153,0,"c",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+154,0,"d",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+155,0,"sel",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+156,0,"y",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->popPrefix();
    tracep->pushPrefix("regfilep", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+197,0,"WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+157,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+158,0,"we3",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+159,0,"ra1",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+160,0,"ra2",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+161,0,"wa3",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+162,0,"wd3",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+163,0,"rd1",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+164,0,"rd2",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->pushPrefix("rf", VerilatedTracePrefixType::ARRAY_UNPACKED);
    for (int i = 0; i < 32; ++i) {
        tracep->declBus(c+165+i*1,0,"",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, true,(i+0), 31,0);
    }
    tracep->popPrefix();
    tracep->popPrefix();
}

VL_ATTR_COLD void Vtop___024root__trace_init_top(Vtop___024root* vlSelf, VerilatedVcd* tracep) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_init_top\n"); );
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Body
    Vtop___024root__trace_init_sub__TOP__0(vlSelf, tracep);
}

VL_ATTR_COLD void Vtop___024root__trace_const_0(void* voidSelf, VerilatedVcd::Buffer* bufp);
VL_ATTR_COLD void Vtop___024root__trace_full_0(void* voidSelf, VerilatedVcd::Buffer* bufp);
void Vtop___024root__trace_chg_0(void* voidSelf, VerilatedVcd::Buffer* bufp);
void Vtop___024root__trace_cleanup(void* voidSelf, VerilatedVcd* /*unused*/);

VL_ATTR_COLD void Vtop___024root__trace_register(Vtop___024root* vlSelf, VerilatedVcd* tracep) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_register\n"); );
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Body
    tracep->addConstCb(&Vtop___024root__trace_const_0, 0U, vlSelf);
    tracep->addFullCb(&Vtop___024root__trace_full_0, 0U, vlSelf);
    tracep->addChgCb(&Vtop___024root__trace_chg_0, 0U, vlSelf);
    tracep->addCleanupCb(&Vtop___024root__trace_cleanup, vlSelf);
}

VL_ATTR_COLD void Vtop___024root__trace_const_0_sub_0(Vtop___024root* vlSelf, VerilatedVcd::Buffer* bufp);

VL_ATTR_COLD void Vtop___024root__trace_const_0(void* voidSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_const_0\n"); );
    // Init
    Vtop___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vtop___024root*>(voidSelf);
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    // Body
    Vtop___024root__trace_const_0_sub_0((&vlSymsp->TOP), bufp);
}

VL_ATTR_COLD void Vtop___024root__trace_const_0_sub_0(Vtop___024root* vlSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_const_0_sub_0\n"); );
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Init
    uint32_t* const oldp VL_ATTR_UNUSED = bufp->oldp(vlSymsp->__Vm_baseCode);
    // Body
    bufp->fullIData(oldp+197,(0x20U),32);
    bufp->fullIData(oldp+198,(8U),32);
}

VL_ATTR_COLD void Vtop___024root__trace_full_0_sub_0(Vtop___024root* vlSelf, VerilatedVcd::Buffer* bufp);

VL_ATTR_COLD void Vtop___024root__trace_full_0(void* voidSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_full_0\n"); );
    // Init
    Vtop___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vtop___024root*>(voidSelf);
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    // Body
    Vtop___024root__trace_full_0_sub_0((&vlSymsp->TOP), bufp);
}

VL_ATTR_COLD void Vtop___024root__trace_full_0_sub_0(Vtop___024root* vlSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_full_0_sub_0\n"); );
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Init
    uint32_t* const oldp VL_ATTR_UNUSED = bufp->oldp(vlSymsp->__Vm_baseCode);
    // Body
    bufp->fullIData(oldp+1,(vlSelfRef.adder__02Ea),32);
    bufp->fullIData(oldp+2,(vlSelfRef.adder__02Eb),32);
    bufp->fullIData(oldp+3,(vlSelfRef.adder__02Ey),32);
    bufp->fullBit(oldp+4,(vlSelfRef.opb5));
    bufp->fullCData(oldp+5,(vlSelfRef.funct3),3);
    bufp->fullBit(oldp+6,(vlSelfRef.functb5));
    bufp->fullCData(oldp+7,(vlSelfRef.aludec__02Ealuop),2);
    bufp->fullCData(oldp+8,(vlSelfRef.alucontrol),3);
    bufp->fullIData(oldp+9,(vlSelfRef.alup__02Ea),32);
    bufp->fullIData(oldp+10,(vlSelfRef.alup__02Eb),32);
    bufp->fullCData(oldp+11,(vlSelfRef.f),3);
    bufp->fullCData(oldp+12,(vlSelfRef.shamt),5);
    bufp->fullIData(oldp+13,(vlSelfRef.alup__02Ey),32);
    bufp->fullBit(oldp+14,(vlSelfRef.dmem__02Eclk));
    bufp->fullBit(oldp+15,(vlSelfRef.we));
    bufp->fullBit(oldp+16,(vlSelfRef.worb));
    bufp->fullIData(oldp+17,(vlSelfRef.dmem__02Ea),32);
    bufp->fullIData(oldp+18,(vlSelfRef.wd),32);
    bufp->fullIData(oldp+19,(vlSelfRef.dmem__02Erd),32);
    bufp->fullIData(oldp+20,(vlSelfRef.eqcomp__02Ea),32);
    bufp->fullIData(oldp+21,(vlSelfRef.eqcomp__02Eb),32);
    bufp->fullBit(oldp+22,(vlSelfRef.eqcomp__02Ey));
    bufp->fullIData(oldp+23,(vlSelfRef.instr),25);
    bufp->fullCData(oldp+24,(vlSelfRef.extend__02Eimmsrc),2);
    bufp->fullIData(oldp+25,(vlSelfRef.immext),32);
    bufp->fullBit(oldp+26,(vlSelfRef.flopenrc__02Eclk));
    bufp->fullBit(oldp+27,(vlSelfRef.flopenrc__02Erst));
    bufp->fullBit(oldp+28,(vlSelfRef.flopenrc__02Een));
    bufp->fullBit(oldp+29,(vlSelfRef.flopenrc__02Eclear));
    bufp->fullCData(oldp+30,(vlSelfRef.flopenrc__02Ed),8);
    bufp->fullCData(oldp+31,(vlSelfRef.flopenrc__02Eq),8);
    bufp->fullBit(oldp+32,(vlSelfRef.flopenr__02Eclk));
    bufp->fullBit(oldp+33,(vlSelfRef.flopenr__02Erst));
    bufp->fullBit(oldp+34,(vlSelfRef.flopenr__02Een));
    bufp->fullCData(oldp+35,(vlSelfRef.flopenr__02Ed),8);
    bufp->fullCData(oldp+36,(vlSelfRef.flopenr__02Eq),8);
    bufp->fullBit(oldp+37,(vlSelfRef.floprc__02Eclk));
    bufp->fullBit(oldp+38,(vlSelfRef.floprc__02Erst));
    bufp->fullBit(oldp+39,(vlSelfRef.floprc__02Eclear));
    bufp->fullCData(oldp+40,(vlSelfRef.floprc__02Ed),8);
    bufp->fullCData(oldp+41,(vlSelfRef.floprc__02Eq),8);
    bufp->fullBit(oldp+42,(vlSelfRef.flopr__02Eclk));
    bufp->fullBit(oldp+43,(vlSelfRef.flopr__02Erst));
    bufp->fullCData(oldp+44,(vlSelfRef.flopr__02Ed),8);
    bufp->fullCData(oldp+45,(vlSelfRef.flopr__02Eq),8);
    bufp->fullIData(oldp+46,(vlSelfRef.imem__02Ea),32);
    bufp->fullIData(oldp+47,(vlSelfRef.imem__02Erd),32);
    bufp->fullIData(oldp+48,(vlSelfRef.ls2__02Ea),32);
    bufp->fullIData(oldp+49,(vlSelfRef.ls2__02Ey),32);
    bufp->fullCData(oldp+50,(vlSelfRef.op),7);
    bufp->fullCData(oldp+51,(vlSelfRef.resultsrc),2);
    bufp->fullBit(oldp+52,(vlSelfRef.regwrite));
    bufp->fullBit(oldp+53,(vlSelfRef.memwrite));
    bufp->fullBit(oldp+54,(vlSelfRef.jump));
    bufp->fullBit(oldp+55,(vlSelfRef.branch));
    bufp->fullBit(oldp+56,(vlSelfRef.alusrc));
    bufp->fullCData(oldp+57,(vlSelfRef.maindec__02Eimmsrc),2);
    bufp->fullCData(oldp+58,(vlSelfRef.maindec__02Ealuop),2);
    bufp->fullIData(oldp+59,(vlSelfRef.mux2__02Ea),32);
    bufp->fullIData(oldp+60,(vlSelfRef.mux2__02Eb),32);
    bufp->fullBit(oldp+61,(vlSelfRef.mux2__02Esel));
    bufp->fullIData(oldp+62,(vlSelfRef.mux2__02Ey),32);
    bufp->fullIData(oldp+63,(vlSelfRef.mux3__02Ea),32);
    bufp->fullIData(oldp+64,(vlSelfRef.mux3__02Eb),32);
    bufp->fullIData(oldp+65,(vlSelfRef.mux3__02Ec),32);
    bufp->fullCData(oldp+66,(vlSelfRef.mux3__02Esel),2);
    bufp->fullIData(oldp+67,(vlSelfRef.mux3__02Ey),32);
    bufp->fullIData(oldp+68,(vlSelfRef.mux4__02Ea),32);
    bufp->fullIData(oldp+69,(vlSelfRef.mux4__02Eb),32);
    bufp->fullIData(oldp+70,(vlSelfRef.mux4__02Ec),32);
    bufp->fullIData(oldp+71,(vlSelfRef.mux4__02Ed),32);
    bufp->fullCData(oldp+72,(vlSelfRef.mux4__02Esel),2);
    bufp->fullIData(oldp+73,(vlSelfRef.mux4__02Ey),32);
    bufp->fullBit(oldp+74,(vlSelfRef.regfilep__02Eclk));
    bufp->fullBit(oldp+75,(vlSelfRef.we3));
    bufp->fullCData(oldp+76,(vlSelfRef.ra1),5);
    bufp->fullCData(oldp+77,(vlSelfRef.ra2),5);
    bufp->fullCData(oldp+78,(vlSelfRef.wa3),5);
    bufp->fullIData(oldp+79,(vlSelfRef.wd3),32);
    bufp->fullIData(oldp+80,(vlSelfRef.rd1),32);
    bufp->fullIData(oldp+81,(vlSelfRef.rd2),32);
    bufp->fullIData(oldp+82,(vlSelfRef.adder__DOT__a),32);
    bufp->fullIData(oldp+83,(vlSelfRef.adder__DOT__b),32);
    bufp->fullIData(oldp+84,(vlSelfRef.adder__DOT__y),32);
    bufp->fullBit(oldp+85,(vlSelfRef.aludec__DOT__opb5));
    bufp->fullCData(oldp+86,(vlSelfRef.aludec__DOT__funct3),3);
    bufp->fullBit(oldp+87,(vlSelfRef.aludec__DOT__functb5));
    bufp->fullCData(oldp+88,(vlSelfRef.aludec__DOT__aluop),2);
    bufp->fullCData(oldp+89,(vlSelfRef.aludec__DOT__alucontrol),3);
    bufp->fullBit(oldp+90,(vlSelfRef.aludec__DOT__rsub));
    bufp->fullIData(oldp+91,(vlSelfRef.alup__DOT__a),32);
    bufp->fullIData(oldp+92,(vlSelfRef.alup__DOT__b),32);
    bufp->fullCData(oldp+93,(vlSelfRef.alup__DOT__f),3);
    bufp->fullCData(oldp+94,(vlSelfRef.alup__DOT__shamt),5);
    bufp->fullIData(oldp+95,(vlSelfRef.alup__DOT__y),32);
    bufp->fullBit(oldp+96,(vlSelfRef.dmem__DOT__clk));
    bufp->fullBit(oldp+97,(vlSelfRef.dmem__DOT__we));
    bufp->fullBit(oldp+98,(vlSelfRef.dmem__DOT__worb));
    bufp->fullIData(oldp+99,(vlSelfRef.dmem__DOT__a),32);
    bufp->fullIData(oldp+100,(vlSelfRef.dmem__DOT__wd),32);
    bufp->fullIData(oldp+101,(vlSelfRef.dmem__DOT__rd),32);
    bufp->fullIData(oldp+102,(vlSelfRef.eqcomp__DOT__a),32);
    bufp->fullIData(oldp+103,(vlSelfRef.eqcomp__DOT__b),32);
    bufp->fullBit(oldp+104,(vlSelfRef.eqcomp__DOT__y));
    bufp->fullIData(oldp+105,(vlSelfRef.extend__DOT__instr),25);
    bufp->fullCData(oldp+106,(vlSelfRef.extend__DOT__immsrc),2);
    bufp->fullIData(oldp+107,(vlSelfRef.extend__DOT__immext),32);
    bufp->fullBit(oldp+108,(vlSelfRef.flopenr__DOT__clk));
    bufp->fullBit(oldp+109,(vlSelfRef.flopenr__DOT__rst));
    bufp->fullBit(oldp+110,(vlSelfRef.flopenr__DOT__en));
    bufp->fullCData(oldp+111,(vlSelfRef.flopenr__DOT__d),8);
    bufp->fullCData(oldp+112,(vlSelfRef.flopenr__DOT__q),8);
    bufp->fullBit(oldp+113,(vlSelfRef.flopenrc__DOT__clk));
    bufp->fullBit(oldp+114,(vlSelfRef.flopenrc__DOT__rst));
    bufp->fullBit(oldp+115,(vlSelfRef.flopenrc__DOT__en));
    bufp->fullBit(oldp+116,(vlSelfRef.flopenrc__DOT__clear));
    bufp->fullCData(oldp+117,(vlSelfRef.flopenrc__DOT__d),8);
    bufp->fullCData(oldp+118,(vlSelfRef.flopenrc__DOT__q),8);
    bufp->fullBit(oldp+119,(vlSelfRef.flopr__DOT__clk));
    bufp->fullBit(oldp+120,(vlSelfRef.flopr__DOT__rst));
    bufp->fullCData(oldp+121,(vlSelfRef.flopr__DOT__d),8);
    bufp->fullCData(oldp+122,(vlSelfRef.flopr__DOT__q),8);
    bufp->fullBit(oldp+123,(vlSelfRef.floprc__DOT__clk));
    bufp->fullBit(oldp+124,(vlSelfRef.floprc__DOT__rst));
    bufp->fullBit(oldp+125,(vlSelfRef.floprc__DOT__clear));
    bufp->fullCData(oldp+126,(vlSelfRef.floprc__DOT__d),8);
    bufp->fullCData(oldp+127,(vlSelfRef.floprc__DOT__q),8);
    bufp->fullIData(oldp+128,(vlSelfRef.imem__DOT__a),32);
    bufp->fullIData(oldp+129,(vlSelfRef.imem__DOT__rd),32);
    bufp->fullIData(oldp+130,(vlSelfRef.ls2__DOT__a),32);
    bufp->fullIData(oldp+131,(vlSelfRef.ls2__DOT__y),32);
    bufp->fullCData(oldp+132,(vlSelfRef.maindec__DOT__op),7);
    bufp->fullCData(oldp+133,(vlSelfRef.maindec__DOT__resultsrc),2);
    bufp->fullBit(oldp+134,(vlSelfRef.maindec__DOT__regwrite));
    bufp->fullBit(oldp+135,(vlSelfRef.maindec__DOT__memwrite));
    bufp->fullBit(oldp+136,(vlSelfRef.maindec__DOT__jump));
    bufp->fullBit(oldp+137,(vlSelfRef.maindec__DOT__branch));
    bufp->fullBit(oldp+138,(vlSelfRef.maindec__DOT__alusrc));
    bufp->fullCData(oldp+139,(vlSelfRef.maindec__DOT__immsrc),2);
    bufp->fullCData(oldp+140,(vlSelfRef.maindec__DOT__aluop),2);
    bufp->fullSData(oldp+141,(vlSelfRef.maindec__DOT__controlsig),11);
    bufp->fullIData(oldp+142,(vlSelfRef.mux2__DOT__a),32);
    bufp->fullIData(oldp+143,(vlSelfRef.mux2__DOT__b),32);
    bufp->fullBit(oldp+144,(vlSelfRef.mux2__DOT__sel));
    bufp->fullIData(oldp+145,(vlSelfRef.mux2__DOT__y),32);
    bufp->fullIData(oldp+146,(vlSelfRef.mux3__DOT__a),32);
    bufp->fullIData(oldp+147,(vlSelfRef.mux3__DOT__b),32);
    bufp->fullIData(oldp+148,(vlSelfRef.mux3__DOT__c),32);
    bufp->fullCData(oldp+149,(vlSelfRef.mux3__DOT__sel),2);
    bufp->fullIData(oldp+150,(vlSelfRef.mux3__DOT__y),32);
    bufp->fullIData(oldp+151,(vlSelfRef.mux4__DOT__a),32);
    bufp->fullIData(oldp+152,(vlSelfRef.mux4__DOT__b),32);
    bufp->fullIData(oldp+153,(vlSelfRef.mux4__DOT__c),32);
    bufp->fullIData(oldp+154,(vlSelfRef.mux4__DOT__d),32);
    bufp->fullCData(oldp+155,(vlSelfRef.mux4__DOT__sel),2);
    bufp->fullIData(oldp+156,(vlSelfRef.mux4__DOT__y),32);
    bufp->fullBit(oldp+157,(vlSelfRef.regfilep__DOT__clk));
    bufp->fullBit(oldp+158,(vlSelfRef.regfilep__DOT__we3));
    bufp->fullCData(oldp+159,(vlSelfRef.regfilep__DOT__ra1),5);
    bufp->fullCData(oldp+160,(vlSelfRef.regfilep__DOT__ra2),5);
    bufp->fullCData(oldp+161,(vlSelfRef.regfilep__DOT__wa3),5);
    bufp->fullIData(oldp+162,(vlSelfRef.regfilep__DOT__wd3),32);
    bufp->fullIData(oldp+163,(vlSelfRef.regfilep__DOT__rd1),32);
    bufp->fullIData(oldp+164,(vlSelfRef.regfilep__DOT__rd2),32);
    bufp->fullIData(oldp+165,(vlSelfRef.regfilep__DOT__rf[0]),32);
    bufp->fullIData(oldp+166,(vlSelfRef.regfilep__DOT__rf[1]),32);
    bufp->fullIData(oldp+167,(vlSelfRef.regfilep__DOT__rf[2]),32);
    bufp->fullIData(oldp+168,(vlSelfRef.regfilep__DOT__rf[3]),32);
    bufp->fullIData(oldp+169,(vlSelfRef.regfilep__DOT__rf[4]),32);
    bufp->fullIData(oldp+170,(vlSelfRef.regfilep__DOT__rf[5]),32);
    bufp->fullIData(oldp+171,(vlSelfRef.regfilep__DOT__rf[6]),32);
    bufp->fullIData(oldp+172,(vlSelfRef.regfilep__DOT__rf[7]),32);
    bufp->fullIData(oldp+173,(vlSelfRef.regfilep__DOT__rf[8]),32);
    bufp->fullIData(oldp+174,(vlSelfRef.regfilep__DOT__rf[9]),32);
    bufp->fullIData(oldp+175,(vlSelfRef.regfilep__DOT__rf[10]),32);
    bufp->fullIData(oldp+176,(vlSelfRef.regfilep__DOT__rf[11]),32);
    bufp->fullIData(oldp+177,(vlSelfRef.regfilep__DOT__rf[12]),32);
    bufp->fullIData(oldp+178,(vlSelfRef.regfilep__DOT__rf[13]),32);
    bufp->fullIData(oldp+179,(vlSelfRef.regfilep__DOT__rf[14]),32);
    bufp->fullIData(oldp+180,(vlSelfRef.regfilep__DOT__rf[15]),32);
    bufp->fullIData(oldp+181,(vlSelfRef.regfilep__DOT__rf[16]),32);
    bufp->fullIData(oldp+182,(vlSelfRef.regfilep__DOT__rf[17]),32);
    bufp->fullIData(oldp+183,(vlSelfRef.regfilep__DOT__rf[18]),32);
    bufp->fullIData(oldp+184,(vlSelfRef.regfilep__DOT__rf[19]),32);
    bufp->fullIData(oldp+185,(vlSelfRef.regfilep__DOT__rf[20]),32);
    bufp->fullIData(oldp+186,(vlSelfRef.regfilep__DOT__rf[21]),32);
    bufp->fullIData(oldp+187,(vlSelfRef.regfilep__DOT__rf[22]),32);
    bufp->fullIData(oldp+188,(vlSelfRef.regfilep__DOT__rf[23]),32);
    bufp->fullIData(oldp+189,(vlSelfRef.regfilep__DOT__rf[24]),32);
    bufp->fullIData(oldp+190,(vlSelfRef.regfilep__DOT__rf[25]),32);
    bufp->fullIData(oldp+191,(vlSelfRef.regfilep__DOT__rf[26]),32);
    bufp->fullIData(oldp+192,(vlSelfRef.regfilep__DOT__rf[27]),32);
    bufp->fullIData(oldp+193,(vlSelfRef.regfilep__DOT__rf[28]),32);
    bufp->fullIData(oldp+194,(vlSelfRef.regfilep__DOT__rf[29]),32);
    bufp->fullIData(oldp+195,(vlSelfRef.regfilep__DOT__rf[30]),32);
    bufp->fullIData(oldp+196,(vlSelfRef.regfilep__DOT__rf[31]),32);
}
