// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Tracing implementation internals
#include "verilated_vcd_c.h"
#include "Vtop__Syms.h"


VL_ATTR_COLD void Vtop___024root__trace_init_sub__TOP__0(Vtop___024root* vlSelf, VerilatedVcd* tracep) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_init_sub__TOP__0\n"); );
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Init
    const int c = vlSymsp->__Vm_baseCode;
    // Body
    tracep->declBit(c+1,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+2,0,"rst",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+3,0,"writedata",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+4,0,"dataaddr",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+5,0,"memwrite",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->pushPrefix("toplevel", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+177,0,"WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+178,0,"PCWIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+6,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+7,0,"rst",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+8,0,"writedata",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+9,0,"dataaddr",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+10,0,"memwrite",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+11,0,"currentpc",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+12,0,"instruction",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+13,0,"datamemout",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->pushPrefix("dmem", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+177,0,"WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+14,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+15,0,"we",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+16,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+17,0,"wd",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+18,0,"rd",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->popPrefix();
    tracep->pushPrefix("imem", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+19,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 5,0);
    tracep->declBus(c+20,0,"rd",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->popPrefix();
    tracep->pushPrefix("mips_core", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+177,0,"WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+178,0,"PCWIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+21,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+22,0,"rst",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+23,0,"instruction",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+24,0,"datamemout",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+25,0,"memwrite",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+26,0,"aluresult",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+27,0,"writedata",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+28,0,"currentpc",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+29,0,"op",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 5,0);
    tracep->declBus(c+30,0,"funct",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 5,0);
    tracep->declBit(c+31,0,"zero",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+32,0,"jump",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+33,0,"regwrite",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+34,0,"regdst",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+35,0,"memtoreg",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+36,0,"pcsrc",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+37,0,"alusrc",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+38,0,"alucontrol",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->pushPrefix("control_unit_inst", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+39,0,"op",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 5,0);
    tracep->declBus(c+40,0,"funct",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 5,0);
    tracep->declBit(c+41,0,"zero",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+42,0,"memtoreg",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+43,0,"memwrite",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+44,0,"regdst",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+45,0,"regwrite",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+46,0,"jump",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+47,0,"pcsrc",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+48,0,"alusrc",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+49,0,"alucontrol",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBit(c+50,0,"branch",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+51,0,"aluop",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->pushPrefix("alu_decoder_inst", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+52,0,"funct",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 5,0);
    tracep->declBus(c+53,0,"aluop",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+54,0,"alucontrol",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->popPrefix();
    tracep->pushPrefix("main_decoder_inst", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+55,0,"op",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 5,0);
    tracep->declBit(c+56,0,"memtoreg",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+57,0,"memwrite",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+58,0,"branch",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+59,0,"aluscr",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+60,0,"regdst",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+61,0,"regwrite",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+62,0,"jump",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+63,0,"aluop",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+64,0,"controlsig",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 8,0);
    tracep->popPrefix();
    tracep->popPrefix();
    tracep->pushPrefix("datapath_inst", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+177,0,"WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+178,0,"PCWIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+65,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+66,0,"rst",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+67,0,"jump",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+68,0,"regwrite",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+69,0,"regdst",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+70,0,"memtoreg",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+71,0,"memwrite",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+72,0,"alucontrol",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBit(c+73,0,"pcsrc",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+74,0,"alusrc",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+75,0,"op",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 5,0);
    tracep->declBus(c+76,0,"funct",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 5,0);
    tracep->declBit(c+77,0,"zero",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+78,0,"instruction",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+79,0,"currentpc",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+80,0,"aluresult",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+81,0,"regout2",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+82,0,"datamemout",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+83,0,"pcplus4",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+84,0,"branchmuxout",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+85,0,"jumpmuxout",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+86,0,"pcbranchout",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+87,0,"wa3",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+88,0,"immext",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+89,0,"ls2out",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+90,0,"regout1",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+91,0,"alumuxout",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+92,0,"writedatareg",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+93,0,"currentpc_32",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+94,0,"pcjump",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+95,0,"jumpls2out",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->pushPrefix("alu", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+177,0,"WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+96,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+97,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+98,0,"f",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+99,0,"y",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+100,0,"zero",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->pushPrefix("alumux", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+177,0,"WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+101,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+102,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+103,0,"sel",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+104,0,"y",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->popPrefix();
    tracep->pushPrefix("branchmux", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+178,0,"WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+105,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+106,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBit(c+107,0,"sel",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+108,0,"y",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->popPrefix();
    tracep->pushPrefix("jumpls2_inst", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+177,0,"WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+109,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+110,0,"y",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->popPrefix();
    tracep->pushPrefix("jumpmux", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+178,0,"WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+111,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+112,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBit(c+113,0,"sel",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+114,0,"y",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->popPrefix();
    tracep->pushPrefix("pc", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+178,0,"WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+115,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+116,0,"rst",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+117,0,"d",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+118,0,"q",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->popPrefix();
    tracep->pushPrefix("pcbranch", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+177,0,"WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+119,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+120,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+121,0,"y",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->popPrefix();
    tracep->pushPrefix("pcplus4_inst", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+177,0,"WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+122,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+123,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+124,0,"y",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->popPrefix();
    tracep->pushPrefix("resultmux", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+177,0,"WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+125,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+126,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+127,0,"sel",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+128,0,"y",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->popPrefix();
    tracep->pushPrefix("rf", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+177,0,"WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+129,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+130,0,"we3",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+131,0,"ra1",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+132,0,"ra2",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+133,0,"wa3",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+134,0,"wd3",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+135,0,"rd1",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+136,0,"rd2",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->pushPrefix("rf", VerilatedTracePrefixType::ARRAY_UNPACKED);
    for (int i = 0; i < 32; ++i) {
        tracep->declBus(c+137+i*1,0,"",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, true,(i+0), 31,0);
    }
    tracep->popPrefix();
    tracep->popPrefix();
    tracep->pushPrefix("se", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+179,0,"WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+177,0,"OUTWIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+169,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+170,0,"y",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->popPrefix();
    tracep->pushPrefix("signextls2", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+177,0,"WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+171,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+172,0,"y",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->popPrefix();
    tracep->pushPrefix("wregmux", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+180,0,"WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+173,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+174,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBit(c+175,0,"sel",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+176,0,"y",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->popPrefix();
    tracep->popPrefix();
    tracep->popPrefix();
    tracep->popPrefix();
}

VL_ATTR_COLD void Vtop___024root__trace_init_top(Vtop___024root* vlSelf, VerilatedVcd* tracep) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_init_top\n"); );
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Body
    Vtop___024root__trace_init_sub__TOP__0(vlSelf, tracep);
}

VL_ATTR_COLD void Vtop___024root__trace_const_0(void* voidSelf, VerilatedVcd::Buffer* bufp);
VL_ATTR_COLD void Vtop___024root__trace_full_0(void* voidSelf, VerilatedVcd::Buffer* bufp);
void Vtop___024root__trace_chg_0(void* voidSelf, VerilatedVcd::Buffer* bufp);
void Vtop___024root__trace_cleanup(void* voidSelf, VerilatedVcd* /*unused*/);

VL_ATTR_COLD void Vtop___024root__trace_register(Vtop___024root* vlSelf, VerilatedVcd* tracep) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_register\n"); );
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Body
    tracep->addConstCb(&Vtop___024root__trace_const_0, 0U, vlSelf);
    tracep->addFullCb(&Vtop___024root__trace_full_0, 0U, vlSelf);
    tracep->addChgCb(&Vtop___024root__trace_chg_0, 0U, vlSelf);
    tracep->addCleanupCb(&Vtop___024root__trace_cleanup, vlSelf);
}

VL_ATTR_COLD void Vtop___024root__trace_const_0_sub_0(Vtop___024root* vlSelf, VerilatedVcd::Buffer* bufp);

VL_ATTR_COLD void Vtop___024root__trace_const_0(void* voidSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_const_0\n"); );
    // Init
    Vtop___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vtop___024root*>(voidSelf);
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    // Body
    Vtop___024root__trace_const_0_sub_0((&vlSymsp->TOP), bufp);
}

VL_ATTR_COLD void Vtop___024root__trace_const_0_sub_0(Vtop___024root* vlSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_const_0_sub_0\n"); );
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Init
    uint32_t* const oldp VL_ATTR_UNUSED = bufp->oldp(vlSymsp->__Vm_baseCode);
    // Body
    bufp->fullIData(oldp+177,(0x20U),32);
    bufp->fullIData(oldp+178,(8U),32);
    bufp->fullIData(oldp+179,(0x10U),32);
    bufp->fullIData(oldp+180,(5U),32);
}

VL_ATTR_COLD void Vtop___024root__trace_full_0_sub_0(Vtop___024root* vlSelf, VerilatedVcd::Buffer* bufp);

VL_ATTR_COLD void Vtop___024root__trace_full_0(void* voidSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_full_0\n"); );
    // Init
    Vtop___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vtop___024root*>(voidSelf);
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    // Body
    Vtop___024root__trace_full_0_sub_0((&vlSymsp->TOP), bufp);
}

VL_ATTR_COLD void Vtop___024root__trace_full_0_sub_0(Vtop___024root* vlSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_full_0_sub_0\n"); );
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Init
    uint32_t* const oldp VL_ATTR_UNUSED = bufp->oldp(vlSymsp->__Vm_baseCode);
    // Body
    bufp->fullBit(oldp+1,(vlSelfRef.clk));
    bufp->fullBit(oldp+2,(vlSelfRef.rst));
    bufp->fullIData(oldp+3,(vlSelfRef.writedata),32);
    bufp->fullIData(oldp+4,(vlSelfRef.dataaddr),32);
    bufp->fullBit(oldp+5,(vlSelfRef.memwrite));
    bufp->fullBit(oldp+6,(vlSelfRef.toplevel__DOT__clk));
    bufp->fullBit(oldp+7,(vlSelfRef.toplevel__DOT__rst));
    bufp->fullIData(oldp+8,(vlSelfRef.toplevel__DOT__writedata),32);
    bufp->fullIData(oldp+9,(vlSelfRef.toplevel__DOT__dataaddr),32);
    bufp->fullBit(oldp+10,(vlSelfRef.toplevel__DOT__memwrite));
    bufp->fullCData(oldp+11,(vlSelfRef.toplevel__DOT__currentpc),8);
    bufp->fullIData(oldp+12,(vlSelfRef.toplevel__DOT__instruction),32);
    bufp->fullIData(oldp+13,(vlSelfRef.toplevel__DOT__datamemout),32);
    bufp->fullBit(oldp+14,(vlSelfRef.toplevel__DOT__dmem__DOT__clk));
    bufp->fullBit(oldp+15,(vlSelfRef.toplevel__DOT__dmem__DOT__we));
    bufp->fullIData(oldp+16,(vlSelfRef.toplevel__DOT__dmem__DOT__a),32);
    bufp->fullIData(oldp+17,(vlSelfRef.toplevel__DOT__dmem__DOT__wd),32);
    bufp->fullIData(oldp+18,(vlSelfRef.toplevel__DOT__dmem__DOT__rd),32);
    bufp->fullCData(oldp+19,(vlSelfRef.toplevel__DOT__imem__DOT__a),6);
    bufp->fullIData(oldp+20,(vlSelfRef.toplevel__DOT__imem__DOT__rd),32);
    bufp->fullBit(oldp+21,(vlSelfRef.toplevel__DOT__mips_core__DOT__clk));
    bufp->fullBit(oldp+22,(vlSelfRef.toplevel__DOT__mips_core__DOT__rst));
    bufp->fullIData(oldp+23,(vlSelfRef.toplevel__DOT__mips_core__DOT__instruction),32);
    bufp->fullIData(oldp+24,(vlSelfRef.toplevel__DOT__mips_core__DOT__datamemout),32);
    bufp->fullBit(oldp+25,(vlSelfRef.toplevel__DOT__mips_core__DOT__memwrite));
    bufp->fullIData(oldp+26,(vlSelfRef.toplevel__DOT__mips_core__DOT__aluresult),32);
    bufp->fullIData(oldp+27,(vlSelfRef.toplevel__DOT__mips_core__DOT__writedata),32);
    bufp->fullCData(oldp+28,(vlSelfRef.toplevel__DOT__mips_core__DOT__currentpc),8);
    bufp->fullCData(oldp+29,(vlSelfRef.toplevel__DOT__mips_core__DOT__op),6);
    bufp->fullCData(oldp+30,(vlSelfRef.toplevel__DOT__mips_core__DOT__funct),6);
    bufp->fullBit(oldp+31,(vlSelfRef.toplevel__DOT__mips_core__DOT__zero));
    bufp->fullBit(oldp+32,(vlSelfRef.toplevel__DOT__mips_core__DOT__jump));
    bufp->fullBit(oldp+33,(vlSelfRef.toplevel__DOT__mips_core__DOT__regwrite));
    bufp->fullBit(oldp+34,(vlSelfRef.toplevel__DOT__mips_core__DOT__regdst));
    bufp->fullBit(oldp+35,(vlSelfRef.toplevel__DOT__mips_core__DOT__memtoreg));
    bufp->fullBit(oldp+36,(vlSelfRef.toplevel__DOT__mips_core__DOT__pcsrc));
    bufp->fullBit(oldp+37,(vlSelfRef.toplevel__DOT__mips_core__DOT__alusrc));
    bufp->fullCData(oldp+38,(vlSelfRef.toplevel__DOT__mips_core__DOT__alucontrol),3);
    bufp->fullCData(oldp+39,(vlSelfRef.toplevel__DOT__mips_core__DOT__control_unit_inst__DOT__op),6);
    bufp->fullCData(oldp+40,(vlSelfRef.toplevel__DOT__mips_core__DOT__control_unit_inst__DOT__funct),6);
    bufp->fullBit(oldp+41,(vlSelfRef.toplevel__DOT__mips_core__DOT__control_unit_inst__DOT__zero));
    bufp->fullBit(oldp+42,(vlSelfRef.toplevel__DOT__mips_core__DOT__control_unit_inst__DOT__memtoreg));
    bufp->fullBit(oldp+43,(vlSelfRef.toplevel__DOT__mips_core__DOT__control_unit_inst__DOT__memwrite));
    bufp->fullBit(oldp+44,(vlSelfRef.toplevel__DOT__mips_core__DOT__control_unit_inst__DOT__regdst));
    bufp->fullBit(oldp+45,(vlSelfRef.toplevel__DOT__mips_core__DOT__control_unit_inst__DOT__regwrite));
    bufp->fullBit(oldp+46,(vlSelfRef.toplevel__DOT__mips_core__DOT__control_unit_inst__DOT__jump));
    bufp->fullBit(oldp+47,(vlSelfRef.toplevel__DOT__mips_core__DOT__control_unit_inst__DOT__pcsrc));
    bufp->fullBit(oldp+48,(vlSelfRef.toplevel__DOT__mips_core__DOT__control_unit_inst__DOT__alusrc));
    bufp->fullCData(oldp+49,(vlSelfRef.toplevel__DOT__mips_core__DOT__control_unit_inst__DOT__alucontrol),3);
    bufp->fullBit(oldp+50,(vlSelfRef.toplevel__DOT__mips_core__DOT__control_unit_inst__DOT__branch));
    bufp->fullCData(oldp+51,(vlSelfRef.toplevel__DOT__mips_core__DOT__control_unit_inst__DOT__aluop),2);
    bufp->fullCData(oldp+52,(vlSelfRef.toplevel__DOT__mips_core__DOT__control_unit_inst__DOT__alu_decoder_inst__DOT__funct),6);
    bufp->fullCData(oldp+53,(vlSelfRef.toplevel__DOT__mips_core__DOT__control_unit_inst__DOT__alu_decoder_inst__DOT__aluop),2);
    bufp->fullCData(oldp+54,(vlSelfRef.toplevel__DOT__mips_core__DOT__control_unit_inst__DOT__alu_decoder_inst__DOT__alucontrol),3);
    bufp->fullCData(oldp+55,(vlSelfRef.toplevel__DOT__mips_core__DOT__control_unit_inst__DOT__main_decoder_inst__DOT__op),6);
    bufp->fullBit(oldp+56,(vlSelfRef.toplevel__DOT__mips_core__DOT__control_unit_inst__DOT__main_decoder_inst__DOT__memtoreg));
    bufp->fullBit(oldp+57,(vlSelfRef.toplevel__DOT__mips_core__DOT__control_unit_inst__DOT__main_decoder_inst__DOT__memwrite));
    bufp->fullBit(oldp+58,(vlSelfRef.toplevel__DOT__mips_core__DOT__control_unit_inst__DOT__main_decoder_inst__DOT__branch));
    bufp->fullBit(oldp+59,(vlSelfRef.toplevel__DOT__mips_core__DOT__control_unit_inst__DOT__main_decoder_inst__DOT__aluscr));
    bufp->fullBit(oldp+60,(vlSelfRef.toplevel__DOT__mips_core__DOT__control_unit_inst__DOT__main_decoder_inst__DOT__regdst));
    bufp->fullBit(oldp+61,(vlSelfRef.toplevel__DOT__mips_core__DOT__control_unit_inst__DOT__main_decoder_inst__DOT__regwrite));
    bufp->fullBit(oldp+62,(vlSelfRef.toplevel__DOT__mips_core__DOT__control_unit_inst__DOT__main_decoder_inst__DOT__jump));
    bufp->fullCData(oldp+63,(vlSelfRef.toplevel__DOT__mips_core__DOT__control_unit_inst__DOT__main_decoder_inst__DOT__aluop),2);
    bufp->fullSData(oldp+64,(vlSelfRef.toplevel__DOT__mips_core__DOT__control_unit_inst__DOT__main_decoder_inst__DOT__controlsig),9);
    bufp->fullBit(oldp+65,(vlSelfRef.toplevel__DOT__mips_core__DOT__datapath_inst__DOT__clk));
    bufp->fullBit(oldp+66,(vlSelfRef.toplevel__DOT__mips_core__DOT__datapath_inst__DOT__rst));
    bufp->fullBit(oldp+67,(vlSelfRef.toplevel__DOT__mips_core__DOT__datapath_inst__DOT__jump));
    bufp->fullBit(oldp+68,(vlSelfRef.toplevel__DOT__mips_core__DOT__datapath_inst__DOT__regwrite));
    bufp->fullBit(oldp+69,(vlSelfRef.toplevel__DOT__mips_core__DOT__datapath_inst__DOT__regdst));
    bufp->fullBit(oldp+70,(vlSelfRef.toplevel__DOT__mips_core__DOT__datapath_inst__DOT__memtoreg));
    bufp->fullBit(oldp+71,(vlSelfRef.toplevel__DOT__mips_core__DOT__datapath_inst__DOT__memwrite));
    bufp->fullCData(oldp+72,(vlSelfRef.toplevel__DOT__mips_core__DOT__datapath_inst__DOT__alucontrol),3);
    bufp->fullBit(oldp+73,(vlSelfRef.toplevel__DOT__mips_core__DOT__datapath_inst__DOT__pcsrc));
    bufp->fullBit(oldp+74,(vlSelfRef.toplevel__DOT__mips_core__DOT__datapath_inst__DOT__alusrc));
    bufp->fullCData(oldp+75,(vlSelfRef.toplevel__DOT__mips_core__DOT__datapath_inst__DOT__op),6);
    bufp->fullCData(oldp+76,(vlSelfRef.toplevel__DOT__mips_core__DOT__datapath_inst__DOT__funct),6);
    bufp->fullBit(oldp+77,(vlSelfRef.toplevel__DOT__mips_core__DOT__datapath_inst__DOT__zero));
    bufp->fullIData(oldp+78,(vlSelfRef.toplevel__DOT__mips_core__DOT__datapath_inst__DOT__instruction),32);
    bufp->fullCData(oldp+79,(vlSelfRef.toplevel__DOT__mips_core__DOT__datapath_inst__DOT__currentpc),8);
    bufp->fullIData(oldp+80,(vlSelfRef.toplevel__DOT__mips_core__DOT__datapath_inst__DOT__aluresult),32);
    bufp->fullIData(oldp+81,(vlSelfRef.toplevel__DOT__mips_core__DOT__datapath_inst__DOT__regout2),32);
    bufp->fullIData(oldp+82,(vlSelfRef.toplevel__DOT__mips_core__DOT__datapath_inst__DOT__datamemout),32);
    bufp->fullIData(oldp+83,(vlSelfRef.toplevel__DOT__mips_core__DOT__datapath_inst__DOT__pcplus4),32);
    bufp->fullCData(oldp+84,(vlSelfRef.toplevel__DOT__mips_core__DOT__datapath_inst__DOT__branchmuxout),8);
    bufp->fullCData(oldp+85,(vlSelfRef.toplevel__DOT__mips_core__DOT__datapath_inst__DOT__jumpmuxout),8);
    bufp->fullIData(oldp+86,(vlSelfRef.toplevel__DOT__mips_core__DOT__datapath_inst__DOT__pcbranchout),32);
    bufp->fullCData(oldp+87,(vlSelfRef.toplevel__DOT__mips_core__DOT__datapath_inst__DOT__wa3),5);
    bufp->fullIData(oldp+88,(vlSelfRef.toplevel__DOT__mips_core__DOT__datapath_inst__DOT__immext),32);
    bufp->fullIData(oldp+89,(vlSelfRef.toplevel__DOT__mips_core__DOT__datapath_inst__DOT__ls2out),32);
    bufp->fullIData(oldp+90,(vlSelfRef.toplevel__DOT__mips_core__DOT__datapath_inst__DOT__regout1),32);
    bufp->fullIData(oldp+91,(vlSelfRef.toplevel__DOT__mips_core__DOT__datapath_inst__DOT__alumuxout),32);
    bufp->fullIData(oldp+92,(vlSelfRef.toplevel__DOT__mips_core__DOT__datapath_inst__DOT__writedatareg),32);
    bufp->fullIData(oldp+93,(vlSelfRef.toplevel__DOT__mips_core__DOT__datapath_inst__DOT__currentpc_32),32);
    bufp->fullIData(oldp+94,(vlSelfRef.toplevel__DOT__mips_core__DOT__datapath_inst__DOT__pcjump),32);
    bufp->fullIData(oldp+95,(vlSelfRef.toplevel__DOT__mips_core__DOT__datapath_inst__DOT__jumpls2out),32);
    bufp->fullIData(oldp+96,(vlSelfRef.toplevel__DOT__mips_core__DOT__datapath_inst__DOT__alu__DOT__a),32);
    bufp->fullIData(oldp+97,(vlSelfRef.toplevel__DOT__mips_core__DOT__datapath_inst__DOT__alu__DOT__b),32);
    bufp->fullCData(oldp+98,(vlSelfRef.toplevel__DOT__mips_core__DOT__datapath_inst__DOT__alu__DOT__f),3);
    bufp->fullIData(oldp+99,(vlSelfRef.toplevel__DOT__mips_core__DOT__datapath_inst__DOT__alu__DOT__y),32);
    bufp->fullBit(oldp+100,(vlSelfRef.toplevel__DOT__mips_core__DOT__datapath_inst__DOT__alu__DOT__zero));
    bufp->fullIData(oldp+101,(vlSelfRef.toplevel__DOT__mips_core__DOT__datapath_inst__DOT__alumux__DOT__a),32);
    bufp->fullIData(oldp+102,(vlSelfRef.toplevel__DOT__mips_core__DOT__datapath_inst__DOT__alumux__DOT__b),32);
    bufp->fullBit(oldp+103,(vlSelfRef.toplevel__DOT__mips_core__DOT__datapath_inst__DOT__alumux__DOT__sel));
    bufp->fullIData(oldp+104,(vlSelfRef.toplevel__DOT__mips_core__DOT__datapath_inst__DOT__alumux__DOT__y),32);
    bufp->fullCData(oldp+105,(vlSelfRef.toplevel__DOT__mips_core__DOT__datapath_inst__DOT__branchmux__DOT__a),8);
    bufp->fullCData(oldp+106,(vlSelfRef.toplevel__DOT__mips_core__DOT__datapath_inst__DOT__branchmux__DOT__b),8);
    bufp->fullBit(oldp+107,(vlSelfRef.toplevel__DOT__mips_core__DOT__datapath_inst__DOT__branchmux__DOT__sel));
    bufp->fullCData(oldp+108,(vlSelfRef.toplevel__DOT__mips_core__DOT__datapath_inst__DOT__branchmux__DOT__y),8);
    bufp->fullIData(oldp+109,(vlSelfRef.toplevel__DOT__mips_core__DOT__datapath_inst__DOT__jumpls2_inst__DOT__a),32);
    bufp->fullIData(oldp+110,(vlSelfRef.toplevel__DOT__mips_core__DOT__datapath_inst__DOT__jumpls2_inst__DOT__y),32);
    bufp->fullCData(oldp+111,(vlSelfRef.toplevel__DOT__mips_core__DOT__datapath_inst__DOT__jumpmux__DOT__a),8);
    bufp->fullCData(oldp+112,(vlSelfRef.toplevel__DOT__mips_core__DOT__datapath_inst__DOT__jumpmux__DOT__b),8);
    bufp->fullBit(oldp+113,(vlSelfRef.toplevel__DOT__mips_core__DOT__datapath_inst__DOT__jumpmux__DOT__sel));
    bufp->fullCData(oldp+114,(vlSelfRef.toplevel__DOT__mips_core__DOT__datapath_inst__DOT__jumpmux__DOT__y),8);
    bufp->fullBit(oldp+115,(vlSelfRef.toplevel__DOT__mips_core__DOT__datapath_inst__DOT__pc__DOT__clk));
    bufp->fullBit(oldp+116,(vlSelfRef.toplevel__DOT__mips_core__DOT__datapath_inst__DOT__pc__DOT__rst));
    bufp->fullCData(oldp+117,(vlSelfRef.toplevel__DOT__mips_core__DOT__datapath_inst__DOT__pc__DOT__d),8);
    bufp->fullCData(oldp+118,(vlSelfRef.toplevel__DOT__mips_core__DOT__datapath_inst__DOT__pc__DOT__q),8);
    bufp->fullIData(oldp+119,(vlSelfRef.toplevel__DOT__mips_core__DOT__datapath_inst__DOT__pcbranch__DOT__a),32);
    bufp->fullIData(oldp+120,(vlSelfRef.toplevel__DOT__mips_core__DOT__datapath_inst__DOT__pcbranch__DOT__b),32);
    bufp->fullIData(oldp+121,(vlSelfRef.toplevel__DOT__mips_core__DOT__datapath_inst__DOT__pcbranch__DOT__y),32);
    bufp->fullIData(oldp+122,(vlSelfRef.toplevel__DOT__mips_core__DOT__datapath_inst__DOT__pcplus4_inst__DOT__a),32);
    bufp->fullIData(oldp+123,(vlSelfRef.toplevel__DOT__mips_core__DOT__datapath_inst__DOT__pcplus4_inst__DOT__b),32);
    bufp->fullIData(oldp+124,(vlSelfRef.toplevel__DOT__mips_core__DOT__datapath_inst__DOT__pcplus4_inst__DOT__y),32);
    bufp->fullIData(oldp+125,(vlSelfRef.toplevel__DOT__mips_core__DOT__datapath_inst__DOT__resultmux__DOT__a),32);
    bufp->fullIData(oldp+126,(vlSelfRef.toplevel__DOT__mips_core__DOT__datapath_inst__DOT__resultmux__DOT__b),32);
    bufp->fullBit(oldp+127,(vlSelfRef.toplevel__DOT__mips_core__DOT__datapath_inst__DOT__resultmux__DOT__sel));
    bufp->fullIData(oldp+128,(vlSelfRef.toplevel__DOT__mips_core__DOT__datapath_inst__DOT__resultmux__DOT__y),32);
    bufp->fullBit(oldp+129,(vlSelfRef.toplevel__DOT__mips_core__DOT__datapath_inst__DOT__rf__DOT__clk));
    bufp->fullBit(oldp+130,(vlSelfRef.toplevel__DOT__mips_core__DOT__datapath_inst__DOT__rf__DOT__we3));
    bufp->fullCData(oldp+131,(vlSelfRef.toplevel__DOT__mips_core__DOT__datapath_inst__DOT__rf__DOT__ra1),5);
    bufp->fullCData(oldp+132,(vlSelfRef.toplevel__DOT__mips_core__DOT__datapath_inst__DOT__rf__DOT__ra2),5);
    bufp->fullCData(oldp+133,(vlSelfRef.toplevel__DOT__mips_core__DOT__datapath_inst__DOT__rf__DOT__wa3),5);
    bufp->fullIData(oldp+134,(vlSelfRef.toplevel__DOT__mips_core__DOT__datapath_inst__DOT__rf__DOT__wd3),32);
    bufp->fullIData(oldp+135,(vlSelfRef.toplevel__DOT__mips_core__DOT__datapath_inst__DOT__rf__DOT__rd1),32);
    bufp->fullIData(oldp+136,(vlSelfRef.toplevel__DOT__mips_core__DOT__datapath_inst__DOT__rf__DOT__rd2),32);
    bufp->fullIData(oldp+137,(vlSelfRef.toplevel__DOT__mips_core__DOT__datapath_inst__DOT__rf__DOT__rf[0]),32);
    bufp->fullIData(oldp+138,(vlSelfRef.toplevel__DOT__mips_core__DOT__datapath_inst__DOT__rf__DOT__rf[1]),32);
    bufp->fullIData(oldp+139,(vlSelfRef.toplevel__DOT__mips_core__DOT__datapath_inst__DOT__rf__DOT__rf[2]),32);
    bufp->fullIData(oldp+140,(vlSelfRef.toplevel__DOT__mips_core__DOT__datapath_inst__DOT__rf__DOT__rf[3]),32);
    bufp->fullIData(oldp+141,(vlSelfRef.toplevel__DOT__mips_core__DOT__datapath_inst__DOT__rf__DOT__rf[4]),32);
    bufp->fullIData(oldp+142,(vlSelfRef.toplevel__DOT__mips_core__DOT__datapath_inst__DOT__rf__DOT__rf[5]),32);
    bufp->fullIData(oldp+143,(vlSelfRef.toplevel__DOT__mips_core__DOT__datapath_inst__DOT__rf__DOT__rf[6]),32);
    bufp->fullIData(oldp+144,(vlSelfRef.toplevel__DOT__mips_core__DOT__datapath_inst__DOT__rf__DOT__rf[7]),32);
    bufp->fullIData(oldp+145,(vlSelfRef.toplevel__DOT__mips_core__DOT__datapath_inst__DOT__rf__DOT__rf[8]),32);
    bufp->fullIData(oldp+146,(vlSelfRef.toplevel__DOT__mips_core__DOT__datapath_inst__DOT__rf__DOT__rf[9]),32);
    bufp->fullIData(oldp+147,(vlSelfRef.toplevel__DOT__mips_core__DOT__datapath_inst__DOT__rf__DOT__rf[10]),32);
    bufp->fullIData(oldp+148,(vlSelfRef.toplevel__DOT__mips_core__DOT__datapath_inst__DOT__rf__DOT__rf[11]),32);
    bufp->fullIData(oldp+149,(vlSelfRef.toplevel__DOT__mips_core__DOT__datapath_inst__DOT__rf__DOT__rf[12]),32);
    bufp->fullIData(oldp+150,(vlSelfRef.toplevel__DOT__mips_core__DOT__datapath_inst__DOT__rf__DOT__rf[13]),32);
    bufp->fullIData(oldp+151,(vlSelfRef.toplevel__DOT__mips_core__DOT__datapath_inst__DOT__rf__DOT__rf[14]),32);
    bufp->fullIData(oldp+152,(vlSelfRef.toplevel__DOT__mips_core__DOT__datapath_inst__DOT__rf__DOT__rf[15]),32);
    bufp->fullIData(oldp+153,(vlSelfRef.toplevel__DOT__mips_core__DOT__datapath_inst__DOT__rf__DOT__rf[16]),32);
    bufp->fullIData(oldp+154,(vlSelfRef.toplevel__DOT__mips_core__DOT__datapath_inst__DOT__rf__DOT__rf[17]),32);
    bufp->fullIData(oldp+155,(vlSelfRef.toplevel__DOT__mips_core__DOT__datapath_inst__DOT__rf__DOT__rf[18]),32);
    bufp->fullIData(oldp+156,(vlSelfRef.toplevel__DOT__mips_core__DOT__datapath_inst__DOT__rf__DOT__rf[19]),32);
    bufp->fullIData(oldp+157,(vlSelfRef.toplevel__DOT__mips_core__DOT__datapath_inst__DOT__rf__DOT__rf[20]),32);
    bufp->fullIData(oldp+158,(vlSelfRef.toplevel__DOT__mips_core__DOT__datapath_inst__DOT__rf__DOT__rf[21]),32);
    bufp->fullIData(oldp+159,(vlSelfRef.toplevel__DOT__mips_core__DOT__datapath_inst__DOT__rf__DOT__rf[22]),32);
    bufp->fullIData(oldp+160,(vlSelfRef.toplevel__DOT__mips_core__DOT__datapath_inst__DOT__rf__DOT__rf[23]),32);
    bufp->fullIData(oldp+161,(vlSelfRef.toplevel__DOT__mips_core__DOT__datapath_inst__DOT__rf__DOT__rf[24]),32);
    bufp->fullIData(oldp+162,(vlSelfRef.toplevel__DOT__mips_core__DOT__datapath_inst__DOT__rf__DOT__rf[25]),32);
    bufp->fullIData(oldp+163,(vlSelfRef.toplevel__DOT__mips_core__DOT__datapath_inst__DOT__rf__DOT__rf[26]),32);
    bufp->fullIData(oldp+164,(vlSelfRef.toplevel__DOT__mips_core__DOT__datapath_inst__DOT__rf__DOT__rf[27]),32);
    bufp->fullIData(oldp+165,(vlSelfRef.toplevel__DOT__mips_core__DOT__datapath_inst__DOT__rf__DOT__rf[28]),32);
    bufp->fullIData(oldp+166,(vlSelfRef.toplevel__DOT__mips_core__DOT__datapath_inst__DOT__rf__DOT__rf[29]),32);
    bufp->fullIData(oldp+167,(vlSelfRef.toplevel__DOT__mips_core__DOT__datapath_inst__DOT__rf__DOT__rf[30]),32);
    bufp->fullIData(oldp+168,(vlSelfRef.toplevel__DOT__mips_core__DOT__datapath_inst__DOT__rf__DOT__rf[31]),32);
    bufp->fullSData(oldp+169,(vlSelfRef.toplevel__DOT__mips_core__DOT__datapath_inst__DOT__se__DOT__a),16);
    bufp->fullIData(oldp+170,(vlSelfRef.toplevel__DOT__mips_core__DOT__datapath_inst__DOT__se__DOT__y),32);
    bufp->fullIData(oldp+171,(vlSelfRef.toplevel__DOT__mips_core__DOT__datapath_inst__DOT__signextls2__DOT__a),32);
    bufp->fullIData(oldp+172,(vlSelfRef.toplevel__DOT__mips_core__DOT__datapath_inst__DOT__signextls2__DOT__y),32);
    bufp->fullCData(oldp+173,(vlSelfRef.toplevel__DOT__mips_core__DOT__datapath_inst__DOT__wregmux__DOT__a),5);
    bufp->fullCData(oldp+174,(vlSelfRef.toplevel__DOT__mips_core__DOT__datapath_inst__DOT__wregmux__DOT__b),5);
    bufp->fullBit(oldp+175,(vlSelfRef.toplevel__DOT__mips_core__DOT__datapath_inst__DOT__wregmux__DOT__sel));
    bufp->fullCData(oldp+176,(vlSelfRef.toplevel__DOT__mips_core__DOT__datapath_inst__DOT__wregmux__DOT__y),5);
}
