// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Symbol table implementation internals

#include "Vtop__pch.h"
#include "Vtop.h"
#include "Vtop___024root.h"

// FUNCTIONS
Vtop__Syms::~Vtop__Syms()
{

    // Tear down scope hierarchy
    __Vhier.remove(0, &__Vscope_top);
    __Vhier.remove(&__Vscope_top, &__Vscope_top__dmem);
    __Vhier.remove(&__Vscope_top, &__Vscope_top__imem);
    __Vhier.remove(&__Vscope_top, &__Vscope_top__riscv);
    __Vhier.remove(&__Vscope_top__riscv, &__Vscope_top__riscv__cu);
    __Vhier.remove(&__Vscope_top__riscv, &__Vscope_top__riscv__dp);
    __Vhier.remove(&__Vscope_top__riscv, &__Vscope_top__riscv__hu);
    __Vhier.remove(&__Vscope_top__riscv__cu, &__Vscope_top__riscv__cu__ad);
    __Vhier.remove(&__Vscope_top__riscv__cu, &__Vscope_top__riscv__cu__md);
    __Vhier.remove(&__Vscope_top__riscv__cu, &__Vscope_top__riscv__cu__regE);
    __Vhier.remove(&__Vscope_top__riscv__cu, &__Vscope_top__riscv__cu__regM);
    __Vhier.remove(&__Vscope_top__riscv__cu, &__Vscope_top__riscv__cu__regW);
    __Vhier.remove(&__Vscope_top__riscv__dp, &__Vscope_top__riscv__dp__adderE);
    __Vhier.remove(&__Vscope_top__riscv__dp, &__Vscope_top__riscv__dp__adderF);
    __Vhier.remove(&__Vscope_top__riscv__dp, &__Vscope_top__riscv__dp__alu);
    __Vhier.remove(&__Vscope_top__riscv__dp, &__Vscope_top__riscv__dp__alumux);
    __Vhier.remove(&__Vscope_top__riscv__dp, &__Vscope_top__riscv__dp__ext);
    __Vhier.remove(&__Vscope_top__riscv__dp, &__Vscope_top__riscv__dp__fmuxa);
    __Vhier.remove(&__Vscope_top__riscv__dp, &__Vscope_top__riscv__dp__fmuxb);
    __Vhier.remove(&__Vscope_top__riscv__dp, &__Vscope_top__riscv__dp__pc);
    __Vhier.remove(&__Vscope_top__riscv__dp, &__Vscope_top__riscv__dp__pcmux);
    __Vhier.remove(&__Vscope_top__riscv__dp, &__Vscope_top__riscv__dp__regD1);
    __Vhier.remove(&__Vscope_top__riscv__dp, &__Vscope_top__riscv__dp__regD2);
    __Vhier.remove(&__Vscope_top__riscv__dp, &__Vscope_top__riscv__dp__regD3);
    __Vhier.remove(&__Vscope_top__riscv__dp, &__Vscope_top__riscv__dp__regE1);
    __Vhier.remove(&__Vscope_top__riscv__dp, &__Vscope_top__riscv__dp__regE2);
    __Vhier.remove(&__Vscope_top__riscv__dp, &__Vscope_top__riscv__dp__regE3);
    __Vhier.remove(&__Vscope_top__riscv__dp, &__Vscope_top__riscv__dp__regE4);
    __Vhier.remove(&__Vscope_top__riscv__dp, &__Vscope_top__riscv__dp__regE5);
    __Vhier.remove(&__Vscope_top__riscv__dp, &__Vscope_top__riscv__dp__regE6);
    __Vhier.remove(&__Vscope_top__riscv__dp, &__Vscope_top__riscv__dp__regE7);
    __Vhier.remove(&__Vscope_top__riscv__dp, &__Vscope_top__riscv__dp__regE8);
    __Vhier.remove(&__Vscope_top__riscv__dp, &__Vscope_top__riscv__dp__regM1);
    __Vhier.remove(&__Vscope_top__riscv__dp, &__Vscope_top__riscv__dp__regM2);
    __Vhier.remove(&__Vscope_top__riscv__dp, &__Vscope_top__riscv__dp__regM3);
    __Vhier.remove(&__Vscope_top__riscv__dp, &__Vscope_top__riscv__dp__regM4);
    __Vhier.remove(&__Vscope_top__riscv__dp, &__Vscope_top__riscv__dp__regW1);
    __Vhier.remove(&__Vscope_top__riscv__dp, &__Vscope_top__riscv__dp__regW2);
    __Vhier.remove(&__Vscope_top__riscv__dp, &__Vscope_top__riscv__dp__regW3);
    __Vhier.remove(&__Vscope_top__riscv__dp, &__Vscope_top__riscv__dp__regW4);
    __Vhier.remove(&__Vscope_top__riscv__dp, &__Vscope_top__riscv__dp__resultmux);
    __Vhier.remove(&__Vscope_top__riscv__dp, &__Vscope_top__riscv__dp__rf);

}

Vtop__Syms::Vtop__Syms(VerilatedContext* contextp, const char* namep, Vtop* modelp)
    : VerilatedSyms{contextp}
    // Setup internal state of the Syms class
    , __Vm_modelp{modelp}
    // Setup module instances
    , TOP{this, namep}
{
        // Check resources
        Verilated::stackCheck(65);
    // Configure time unit / time precision
    _vm_contextp__->timeunit(-9);
    _vm_contextp__->timeprecision(-12);
    // Setup each module's pointers to their submodules
    // Setup each module's pointer back to symbol table (for public functions)
    TOP.__Vconfigure(true);
    // Setup scopes
    __Vscope_TOP.configure(this, name(), "TOP", "TOP", "<null>", 0, VerilatedScope::SCOPE_OTHER);
    __Vscope_top.configure(this, name(), "top", "top", "top", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_top__dmem.configure(this, name(), "top.dmem", "dmem", "dmem", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_top__imem.configure(this, name(), "top.imem", "imem", "imem", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_top__riscv.configure(this, name(), "top.riscv", "riscv", "pipelinedprocessor", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_top__riscv__cu.configure(this, name(), "top.riscv.cu", "cu", "controller", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_top__riscv__cu__ad.configure(this, name(), "top.riscv.cu.ad", "ad", "aludec", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_top__riscv__cu__md.configure(this, name(), "top.riscv.cu.md", "md", "maindec", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_top__riscv__cu__regE.configure(this, name(), "top.riscv.cu.regE", "regE", "floprc", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_top__riscv__cu__regM.configure(this, name(), "top.riscv.cu.regM", "regM", "flopr", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_top__riscv__cu__regW.configure(this, name(), "top.riscv.cu.regW", "regW", "flopr", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_top__riscv__dp.configure(this, name(), "top.riscv.dp", "dp", "datapath", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_top__riscv__dp__adderE.configure(this, name(), "top.riscv.dp.adderE", "adderE", "adder", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_top__riscv__dp__adderF.configure(this, name(), "top.riscv.dp.adderF", "adderF", "adder", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_top__riscv__dp__alu.configure(this, name(), "top.riscv.dp.alu", "alu", "alu", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_top__riscv__dp__alumux.configure(this, name(), "top.riscv.dp.alumux", "alumux", "mux2", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_top__riscv__dp__ext.configure(this, name(), "top.riscv.dp.ext", "ext", "extend", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_top__riscv__dp__fmuxa.configure(this, name(), "top.riscv.dp.fmuxa", "fmuxa", "mux3", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_top__riscv__dp__fmuxb.configure(this, name(), "top.riscv.dp.fmuxb", "fmuxb", "mux3", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_top__riscv__dp__pc.configure(this, name(), "top.riscv.dp.pc", "pc", "flopenr", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_top__riscv__dp__pcmux.configure(this, name(), "top.riscv.dp.pcmux", "pcmux", "mux2", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_top__riscv__dp__regD1.configure(this, name(), "top.riscv.dp.regD1", "regD1", "flopenrc", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_top__riscv__dp__regD2.configure(this, name(), "top.riscv.dp.regD2", "regD2", "flopenrc", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_top__riscv__dp__regD3.configure(this, name(), "top.riscv.dp.regD3", "regD3", "flopenrc", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_top__riscv__dp__regE1.configure(this, name(), "top.riscv.dp.regE1", "regE1", "floprc", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_top__riscv__dp__regE2.configure(this, name(), "top.riscv.dp.regE2", "regE2", "floprc", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_top__riscv__dp__regE3.configure(this, name(), "top.riscv.dp.regE3", "regE3", "floprc", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_top__riscv__dp__regE4.configure(this, name(), "top.riscv.dp.regE4", "regE4", "floprc", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_top__riscv__dp__regE5.configure(this, name(), "top.riscv.dp.regE5", "regE5", "floprc", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_top__riscv__dp__regE6.configure(this, name(), "top.riscv.dp.regE6", "regE6", "floprc", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_top__riscv__dp__regE7.configure(this, name(), "top.riscv.dp.regE7", "regE7", "floprc", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_top__riscv__dp__regE8.configure(this, name(), "top.riscv.dp.regE8", "regE8", "floprc", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_top__riscv__dp__regM1.configure(this, name(), "top.riscv.dp.regM1", "regM1", "flopr", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_top__riscv__dp__regM2.configure(this, name(), "top.riscv.dp.regM2", "regM2", "flopr", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_top__riscv__dp__regM3.configure(this, name(), "top.riscv.dp.regM3", "regM3", "flopr", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_top__riscv__dp__regM4.configure(this, name(), "top.riscv.dp.regM4", "regM4", "flopr", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_top__riscv__dp__regW1.configure(this, name(), "top.riscv.dp.regW1", "regW1", "flopr", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_top__riscv__dp__regW2.configure(this, name(), "top.riscv.dp.regW2", "regW2", "flopr", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_top__riscv__dp__regW3.configure(this, name(), "top.riscv.dp.regW3", "regW3", "flopr", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_top__riscv__dp__regW4.configure(this, name(), "top.riscv.dp.regW4", "regW4", "flopr", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_top__riscv__dp__resultmux.configure(this, name(), "top.riscv.dp.resultmux", "resultmux", "mux3", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_top__riscv__dp__rf.configure(this, name(), "top.riscv.dp.rf", "rf", "regfilep", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_top__riscv__hu.configure(this, name(), "top.riscv.hu", "hu", "hazardunit", -9, VerilatedScope::SCOPE_MODULE);

    // Set up scope hierarchy
    __Vhier.add(0, &__Vscope_top);
    __Vhier.add(&__Vscope_top, &__Vscope_top__dmem);
    __Vhier.add(&__Vscope_top, &__Vscope_top__imem);
    __Vhier.add(&__Vscope_top, &__Vscope_top__riscv);
    __Vhier.add(&__Vscope_top__riscv, &__Vscope_top__riscv__cu);
    __Vhier.add(&__Vscope_top__riscv, &__Vscope_top__riscv__dp);
    __Vhier.add(&__Vscope_top__riscv, &__Vscope_top__riscv__hu);
    __Vhier.add(&__Vscope_top__riscv__cu, &__Vscope_top__riscv__cu__ad);
    __Vhier.add(&__Vscope_top__riscv__cu, &__Vscope_top__riscv__cu__md);
    __Vhier.add(&__Vscope_top__riscv__cu, &__Vscope_top__riscv__cu__regE);
    __Vhier.add(&__Vscope_top__riscv__cu, &__Vscope_top__riscv__cu__regM);
    __Vhier.add(&__Vscope_top__riscv__cu, &__Vscope_top__riscv__cu__regW);
    __Vhier.add(&__Vscope_top__riscv__dp, &__Vscope_top__riscv__dp__adderE);
    __Vhier.add(&__Vscope_top__riscv__dp, &__Vscope_top__riscv__dp__adderF);
    __Vhier.add(&__Vscope_top__riscv__dp, &__Vscope_top__riscv__dp__alu);
    __Vhier.add(&__Vscope_top__riscv__dp, &__Vscope_top__riscv__dp__alumux);
    __Vhier.add(&__Vscope_top__riscv__dp, &__Vscope_top__riscv__dp__ext);
    __Vhier.add(&__Vscope_top__riscv__dp, &__Vscope_top__riscv__dp__fmuxa);
    __Vhier.add(&__Vscope_top__riscv__dp, &__Vscope_top__riscv__dp__fmuxb);
    __Vhier.add(&__Vscope_top__riscv__dp, &__Vscope_top__riscv__dp__pc);
    __Vhier.add(&__Vscope_top__riscv__dp, &__Vscope_top__riscv__dp__pcmux);
    __Vhier.add(&__Vscope_top__riscv__dp, &__Vscope_top__riscv__dp__regD1);
    __Vhier.add(&__Vscope_top__riscv__dp, &__Vscope_top__riscv__dp__regD2);
    __Vhier.add(&__Vscope_top__riscv__dp, &__Vscope_top__riscv__dp__regD3);
    __Vhier.add(&__Vscope_top__riscv__dp, &__Vscope_top__riscv__dp__regE1);
    __Vhier.add(&__Vscope_top__riscv__dp, &__Vscope_top__riscv__dp__regE2);
    __Vhier.add(&__Vscope_top__riscv__dp, &__Vscope_top__riscv__dp__regE3);
    __Vhier.add(&__Vscope_top__riscv__dp, &__Vscope_top__riscv__dp__regE4);
    __Vhier.add(&__Vscope_top__riscv__dp, &__Vscope_top__riscv__dp__regE5);
    __Vhier.add(&__Vscope_top__riscv__dp, &__Vscope_top__riscv__dp__regE6);
    __Vhier.add(&__Vscope_top__riscv__dp, &__Vscope_top__riscv__dp__regE7);
    __Vhier.add(&__Vscope_top__riscv__dp, &__Vscope_top__riscv__dp__regE8);
    __Vhier.add(&__Vscope_top__riscv__dp, &__Vscope_top__riscv__dp__regM1);
    __Vhier.add(&__Vscope_top__riscv__dp, &__Vscope_top__riscv__dp__regM2);
    __Vhier.add(&__Vscope_top__riscv__dp, &__Vscope_top__riscv__dp__regM3);
    __Vhier.add(&__Vscope_top__riscv__dp, &__Vscope_top__riscv__dp__regM4);
    __Vhier.add(&__Vscope_top__riscv__dp, &__Vscope_top__riscv__dp__regW1);
    __Vhier.add(&__Vscope_top__riscv__dp, &__Vscope_top__riscv__dp__regW2);
    __Vhier.add(&__Vscope_top__riscv__dp, &__Vscope_top__riscv__dp__regW3);
    __Vhier.add(&__Vscope_top__riscv__dp, &__Vscope_top__riscv__dp__regW4);
    __Vhier.add(&__Vscope_top__riscv__dp, &__Vscope_top__riscv__dp__resultmux);
    __Vhier.add(&__Vscope_top__riscv__dp, &__Vscope_top__riscv__dp__rf);

    // Setup export functions
    for (int __Vfinal = 0; __Vfinal < 2; ++__Vfinal) {
        __Vscope_TOP.varInsert(__Vfinal,"clk", &(TOP.clk), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0,0);
        __Vscope_TOP.varInsert(__Vfinal,"dataadr", &(TOP.dataadr), false, VLVT_UINT32,VLVD_OUT|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_TOP.varInsert(__Vfinal,"memwrite", &(TOP.memwrite), false, VLVT_UINT8,VLVD_OUT|VLVF_PUB_RW,0,0);
        __Vscope_TOP.varInsert(__Vfinal,"rst", &(TOP.rst), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0,0);
        __Vscope_TOP.varInsert(__Vfinal,"writedata", &(TOP.writedata), false, VLVT_UINT32,VLVD_OUT|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top.varInsert(__Vfinal,"WIDTH", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__WIDTH))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top.varInsert(__Vfinal,"clk", &(TOP.top__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top.varInsert(__Vfinal,"dataadr", &(TOP.top__DOT__dataadr), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top.varInsert(__Vfinal,"instrF", &(TOP.top__DOT__instrF), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top.varInsert(__Vfinal,"memwrite", &(TOP.top__DOT__memwrite), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top.varInsert(__Vfinal,"pcF", &(TOP.top__DOT__pcF), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top.varInsert(__Vfinal,"readdataW", &(TOP.top__DOT__readdataW), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top.varInsert(__Vfinal,"rst", &(TOP.top__DOT__rst), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top.varInsert(__Vfinal,"writedata", &(TOP.top__DOT__writedata), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__dmem.varInsert(__Vfinal,"RAM", &(TOP.top__DOT__dmem__DOT__RAM), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1,1 ,63,0 ,31,0);
        __Vscope_top__dmem.varInsert(__Vfinal,"WIDTH", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__dmem__DOT__WIDTH))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__dmem.varInsert(__Vfinal,"a", &(TOP.top__DOT__dmem__DOT__a), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__dmem.varInsert(__Vfinal,"clk", &(TOP.top__DOT__dmem__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__dmem.varInsert(__Vfinal,"index", &(TOP.top__DOT__dmem__DOT__index), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,5,0);
        __Vscope_top__dmem.varInsert(__Vfinal,"rd", &(TOP.top__DOT__dmem__DOT__rd), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__dmem.varInsert(__Vfinal,"wd", &(TOP.top__DOT__dmem__DOT__wd), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__dmem.varInsert(__Vfinal,"we", &(TOP.top__DOT__dmem__DOT__we), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__imem.varInsert(__Vfinal,"RAM", &(TOP.top__DOT__imem__DOT__RAM), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1,1 ,63,0 ,31,0);
        __Vscope_top__imem.varInsert(__Vfinal,"WIDTH", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__imem__DOT__WIDTH))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__imem.varInsert(__Vfinal,"a", &(TOP.top__DOT__imem__DOT__a), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,5,0);
        __Vscope_top__imem.varInsert(__Vfinal,"rd", &(TOP.top__DOT__imem__DOT__rd), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv.varInsert(__Vfinal,"WIDTH", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__riscv__DOT__WIDTH))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv.varInsert(__Vfinal,"alucontrolE", &(TOP.top__DOT__riscv__DOT__alucontrolE), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_top__riscv.varInsert(__Vfinal,"aluresultM", &(TOP.top__DOT__riscv__DOT__aluresultM), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv.varInsert(__Vfinal,"alusrcE", &(TOP.top__DOT__riscv__DOT__alusrcE), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__riscv.varInsert(__Vfinal,"clk", &(TOP.top__DOT__riscv__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__riscv.varInsert(__Vfinal,"flushD", &(TOP.top__DOT__riscv__DOT__flushD), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__riscv.varInsert(__Vfinal,"flushE", &(TOP.top__DOT__riscv__DOT__flushE), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__riscv.varInsert(__Vfinal,"forwardAE", &(TOP.top__DOT__riscv__DOT__forwardAE), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_top__riscv.varInsert(__Vfinal,"forwardBE", &(TOP.top__DOT__riscv__DOT__forwardBE), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_top__riscv.varInsert(__Vfinal,"funct3", &(TOP.top__DOT__riscv__DOT__funct3), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_top__riscv.varInsert(__Vfinal,"funct7b5", &(TOP.top__DOT__riscv__DOT__funct7b5), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__riscv.varInsert(__Vfinal,"immsrcD", &(TOP.top__DOT__riscv__DOT__immsrcD), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_top__riscv.varInsert(__Vfinal,"instrF", &(TOP.top__DOT__riscv__DOT__instrF), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv.varInsert(__Vfinal,"memwriteM", &(TOP.top__DOT__riscv__DOT__memwriteM), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__riscv.varInsert(__Vfinal,"op", &(TOP.top__DOT__riscv__DOT__op), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,6,0);
        __Vscope_top__riscv.varInsert(__Vfinal,"pcF", &(TOP.top__DOT__riscv__DOT__pcF), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv.varInsert(__Vfinal,"pcsrcE", &(TOP.top__DOT__riscv__DOT__pcsrcE), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__riscv.varInsert(__Vfinal,"rdE", &(TOP.top__DOT__riscv__DOT__rdE), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_top__riscv.varInsert(__Vfinal,"rdM", &(TOP.top__DOT__riscv__DOT__rdM), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_top__riscv.varInsert(__Vfinal,"rdW", &(TOP.top__DOT__riscv__DOT__rdW), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_top__riscv.varInsert(__Vfinal,"readdataM", &(TOP.top__DOT__riscv__DOT__readdataM), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv.varInsert(__Vfinal,"regwriteM", &(TOP.top__DOT__riscv__DOT__regwriteM), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__riscv.varInsert(__Vfinal,"regwriteW", &(TOP.top__DOT__riscv__DOT__regwriteW), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__riscv.varInsert(__Vfinal,"resultsrcE", &(TOP.top__DOT__riscv__DOT__resultsrcE), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_top__riscv.varInsert(__Vfinal,"resultsrcW", &(TOP.top__DOT__riscv__DOT__resultsrcW), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_top__riscv.varInsert(__Vfinal,"rs1D", &(TOP.top__DOT__riscv__DOT__rs1D), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_top__riscv.varInsert(__Vfinal,"rs1E", &(TOP.top__DOT__riscv__DOT__rs1E), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_top__riscv.varInsert(__Vfinal,"rs2D", &(TOP.top__DOT__riscv__DOT__rs2D), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_top__riscv.varInsert(__Vfinal,"rs2E", &(TOP.top__DOT__riscv__DOT__rs2E), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_top__riscv.varInsert(__Vfinal,"rst", &(TOP.top__DOT__riscv__DOT__rst), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__riscv.varInsert(__Vfinal,"stallD", &(TOP.top__DOT__riscv__DOT__stallD), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__riscv.varInsert(__Vfinal,"stallF", &(TOP.top__DOT__riscv__DOT__stallF), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__riscv.varInsert(__Vfinal,"writedataM", &(TOP.top__DOT__riscv__DOT__writedataM), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv.varInsert(__Vfinal,"zeroE", &(TOP.top__DOT__riscv__DOT__zeroE), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__riscv__cu.varInsert(__Vfinal,"alucontrolD", &(TOP.top__DOT__riscv__DOT__cu__DOT__alucontrolD), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_top__riscv__cu.varInsert(__Vfinal,"alucontrolE", &(TOP.top__DOT__riscv__DOT__cu__DOT__alucontrolE), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_top__riscv__cu.varInsert(__Vfinal,"aluop", &(TOP.top__DOT__riscv__DOT__cu__DOT__aluop), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_top__riscv__cu.varInsert(__Vfinal,"alusrcD", &(TOP.top__DOT__riscv__DOT__cu__DOT__alusrcD), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__riscv__cu.varInsert(__Vfinal,"alusrcE", &(TOP.top__DOT__riscv__DOT__cu__DOT__alusrcE), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__riscv__cu.varInsert(__Vfinal,"branchD", &(TOP.top__DOT__riscv__DOT__cu__DOT__branchD), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__riscv__cu.varInsert(__Vfinal,"branchE", &(TOP.top__DOT__riscv__DOT__cu__DOT__branchE), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__riscv__cu.varInsert(__Vfinal,"clk", &(TOP.top__DOT__riscv__DOT__cu__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__riscv__cu.varInsert(__Vfinal,"flushE", &(TOP.top__DOT__riscv__DOT__cu__DOT__flushE), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__riscv__cu.varInsert(__Vfinal,"funct3", &(TOP.top__DOT__riscv__DOT__cu__DOT__funct3), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_top__riscv__cu.varInsert(__Vfinal,"funct7b5", &(TOP.top__DOT__riscv__DOT__cu__DOT__funct7b5), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__riscv__cu.varInsert(__Vfinal,"immsrcD", &(TOP.top__DOT__riscv__DOT__cu__DOT__immsrcD), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_top__riscv__cu.varInsert(__Vfinal,"immsrcE", &(TOP.top__DOT__riscv__DOT__cu__DOT__immsrcE), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_top__riscv__cu.varInsert(__Vfinal,"jumpD", &(TOP.top__DOT__riscv__DOT__cu__DOT__jumpD), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__riscv__cu.varInsert(__Vfinal,"jumpE", &(TOP.top__DOT__riscv__DOT__cu__DOT__jumpE), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__riscv__cu.varInsert(__Vfinal,"memwriteD", &(TOP.top__DOT__riscv__DOT__cu__DOT__memwriteD), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__riscv__cu.varInsert(__Vfinal,"memwriteE", &(TOP.top__DOT__riscv__DOT__cu__DOT__memwriteE), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__riscv__cu.varInsert(__Vfinal,"memwriteM", &(TOP.top__DOT__riscv__DOT__cu__DOT__memwriteM), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__riscv__cu.varInsert(__Vfinal,"op", &(TOP.top__DOT__riscv__DOT__cu__DOT__op), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,6,0);
        __Vscope_top__riscv__cu.varInsert(__Vfinal,"pcsrcE", &(TOP.top__DOT__riscv__DOT__cu__DOT__pcsrcE), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__riscv__cu.varInsert(__Vfinal,"regwriteD", &(TOP.top__DOT__riscv__DOT__cu__DOT__regwriteD), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__riscv__cu.varInsert(__Vfinal,"regwriteE", &(TOP.top__DOT__riscv__DOT__cu__DOT__regwriteE), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__riscv__cu.varInsert(__Vfinal,"regwriteM", &(TOP.top__DOT__riscv__DOT__cu__DOT__regwriteM), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__riscv__cu.varInsert(__Vfinal,"regwriteW", &(TOP.top__DOT__riscv__DOT__cu__DOT__regwriteW), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__riscv__cu.varInsert(__Vfinal,"resultsrcD", &(TOP.top__DOT__riscv__DOT__cu__DOT__resultsrcD), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_top__riscv__cu.varInsert(__Vfinal,"resultsrcE", &(TOP.top__DOT__riscv__DOT__cu__DOT__resultsrcE), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_top__riscv__cu.varInsert(__Vfinal,"resultsrcM", &(TOP.top__DOT__riscv__DOT__cu__DOT__resultsrcM), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_top__riscv__cu.varInsert(__Vfinal,"resultsrcW", &(TOP.top__DOT__riscv__DOT__cu__DOT__resultsrcW), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_top__riscv__cu.varInsert(__Vfinal,"rst", &(TOP.top__DOT__riscv__DOT__cu__DOT__rst), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__riscv__cu.varInsert(__Vfinal,"zeroE", &(TOP.top__DOT__riscv__DOT__cu__DOT__zeroE), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__riscv__cu__ad.varInsert(__Vfinal,"alucontrol", &(TOP.top__DOT__riscv__DOT__cu__DOT__ad__DOT__alucontrol), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_top__riscv__cu__ad.varInsert(__Vfinal,"aluop", &(TOP.top__DOT__riscv__DOT__cu__DOT__ad__DOT__aluop), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_top__riscv__cu__ad.varInsert(__Vfinal,"funct3", &(TOP.top__DOT__riscv__DOT__cu__DOT__ad__DOT__funct3), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_top__riscv__cu__ad.varInsert(__Vfinal,"funct7b5", &(TOP.top__DOT__riscv__DOT__cu__DOT__ad__DOT__funct7b5), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__riscv__cu__ad.varInsert(__Vfinal,"opb5", &(TOP.top__DOT__riscv__DOT__cu__DOT__ad__DOT__opb5), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__riscv__cu__ad.varInsert(__Vfinal,"rsub", &(TOP.top__DOT__riscv__DOT__cu__DOT__ad__DOT__rsub), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__riscv__cu__md.varInsert(__Vfinal,"aluop", &(TOP.top__DOT__riscv__DOT__cu__DOT__md__DOT__aluop), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_top__riscv__cu__md.varInsert(__Vfinal,"alusrc", &(TOP.top__DOT__riscv__DOT__cu__DOT__md__DOT__alusrc), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__riscv__cu__md.varInsert(__Vfinal,"branch", &(TOP.top__DOT__riscv__DOT__cu__DOT__md__DOT__branch), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__riscv__cu__md.varInsert(__Vfinal,"controlsig", &(TOP.top__DOT__riscv__DOT__cu__DOT__md__DOT__controlsig), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,10,0);
        __Vscope_top__riscv__cu__md.varInsert(__Vfinal,"immsrc", &(TOP.top__DOT__riscv__DOT__cu__DOT__md__DOT__immsrc), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_top__riscv__cu__md.varInsert(__Vfinal,"jump", &(TOP.top__DOT__riscv__DOT__cu__DOT__md__DOT__jump), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__riscv__cu__md.varInsert(__Vfinal,"memwrite", &(TOP.top__DOT__riscv__DOT__cu__DOT__md__DOT__memwrite), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__riscv__cu__md.varInsert(__Vfinal,"op", &(TOP.top__DOT__riscv__DOT__cu__DOT__md__DOT__op), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,6,0);
        __Vscope_top__riscv__cu__md.varInsert(__Vfinal,"regwrite", &(TOP.top__DOT__riscv__DOT__cu__DOT__md__DOT__regwrite), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__riscv__cu__md.varInsert(__Vfinal,"resultsrc", &(TOP.top__DOT__riscv__DOT__cu__DOT__md__DOT__resultsrc), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_top__riscv__cu__regE.varInsert(__Vfinal,"WIDTH", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__riscv__DOT__cu__DOT__regE__DOT__WIDTH))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv__cu__regE.varInsert(__Vfinal,"clear", &(TOP.top__DOT__riscv__DOT__cu__DOT__regE__DOT__clear), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__riscv__cu__regE.varInsert(__Vfinal,"clk", &(TOP.top__DOT__riscv__DOT__cu__DOT__regE__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__riscv__cu__regE.varInsert(__Vfinal,"d", &(TOP.top__DOT__riscv__DOT__cu__DOT__regE__DOT__d), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,9,0);
        __Vscope_top__riscv__cu__regE.varInsert(__Vfinal,"q", &(TOP.top__DOT__riscv__DOT__cu__DOT__regE__DOT__q), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,9,0);
        __Vscope_top__riscv__cu__regE.varInsert(__Vfinal,"rst", &(TOP.top__DOT__riscv__DOT__cu__DOT__regE__DOT__rst), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__riscv__cu__regM.varInsert(__Vfinal,"WIDTH", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__riscv__DOT__cu__DOT__regM__DOT__WIDTH))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv__cu__regM.varInsert(__Vfinal,"clk", &(TOP.top__DOT__riscv__DOT__cu__DOT__regM__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__riscv__cu__regM.varInsert(__Vfinal,"d", &(TOP.top__DOT__riscv__DOT__cu__DOT__regM__DOT__d), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_top__riscv__cu__regM.varInsert(__Vfinal,"q", &(TOP.top__DOT__riscv__DOT__cu__DOT__regM__DOT__q), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_top__riscv__cu__regM.varInsert(__Vfinal,"rst", &(TOP.top__DOT__riscv__DOT__cu__DOT__regM__DOT__rst), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__riscv__cu__regW.varInsert(__Vfinal,"WIDTH", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__riscv__DOT__cu__DOT__regW__DOT__WIDTH))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv__cu__regW.varInsert(__Vfinal,"clk", &(TOP.top__DOT__riscv__DOT__cu__DOT__regW__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__riscv__cu__regW.varInsert(__Vfinal,"d", &(TOP.top__DOT__riscv__DOT__cu__DOT__regW__DOT__d), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_top__riscv__cu__regW.varInsert(__Vfinal,"q", &(TOP.top__DOT__riscv__DOT__cu__DOT__regW__DOT__q), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_top__riscv__cu__regW.varInsert(__Vfinal,"rst", &(TOP.top__DOT__riscv__DOT__cu__DOT__regW__DOT__rst), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__riscv__dp.varInsert(__Vfinal,"WIDTH", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__riscv__DOT__dp__DOT__WIDTH))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv__dp.varInsert(__Vfinal,"alucontrolE", &(TOP.top__DOT__riscv__DOT__dp__DOT__alucontrolE), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_top__riscv__dp.varInsert(__Vfinal,"aluresultE", &(TOP.top__DOT__riscv__DOT__dp__DOT__aluresultE), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv__dp.varInsert(__Vfinal,"aluresultM", &(TOP.top__DOT__riscv__DOT__dp__DOT__aluresultM), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv__dp.varInsert(__Vfinal,"aluresultW", &(TOP.top__DOT__riscv__DOT__dp__DOT__aluresultW), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv__dp.varInsert(__Vfinal,"alusrcE", &(TOP.top__DOT__riscv__DOT__dp__DOT__alusrcE), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__riscv__dp.varInsert(__Vfinal,"clk", &(TOP.top__DOT__riscv__DOT__dp__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__riscv__dp.varInsert(__Vfinal,"flushD", &(TOP.top__DOT__riscv__DOT__dp__DOT__flushD), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__riscv__dp.varInsert(__Vfinal,"flushE", &(TOP.top__DOT__riscv__DOT__dp__DOT__flushE), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__riscv__dp.varInsert(__Vfinal,"fmuxbout", &(TOP.top__DOT__riscv__DOT__dp__DOT__fmuxbout), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv__dp.varInsert(__Vfinal,"forwardAE", &(TOP.top__DOT__riscv__DOT__dp__DOT__forwardAE), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_top__riscv__dp.varInsert(__Vfinal,"forwardBE", &(TOP.top__DOT__riscv__DOT__dp__DOT__forwardBE), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_top__riscv__dp.varInsert(__Vfinal,"funct3", &(TOP.top__DOT__riscv__DOT__dp__DOT__funct3), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_top__riscv__dp.varInsert(__Vfinal,"funct7b5", &(TOP.top__DOT__riscv__DOT__dp__DOT__funct7b5), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__riscv__dp.varInsert(__Vfinal,"immextD", &(TOP.top__DOT__riscv__DOT__dp__DOT__immextD), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv__dp.varInsert(__Vfinal,"immextE", &(TOP.top__DOT__riscv__DOT__dp__DOT__immextE), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv__dp.varInsert(__Vfinal,"immsrcD", &(TOP.top__DOT__riscv__DOT__dp__DOT__immsrcD), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_top__riscv__dp.varInsert(__Vfinal,"instrD", &(TOP.top__DOT__riscv__DOT__dp__DOT__instrD), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv__dp.varInsert(__Vfinal,"instrF", &(TOP.top__DOT__riscv__DOT__dp__DOT__instrF), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv__dp.varInsert(__Vfinal,"op", &(TOP.top__DOT__riscv__DOT__dp__DOT__op), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,6,0);
        __Vscope_top__riscv__dp.varInsert(__Vfinal,"pcD", &(TOP.top__DOT__riscv__DOT__dp__DOT__pcD), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv__dp.varInsert(__Vfinal,"pcE", &(TOP.top__DOT__riscv__DOT__dp__DOT__pcE), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv__dp.varInsert(__Vfinal,"pcF", &(TOP.top__DOT__riscv__DOT__dp__DOT__pcF), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv__dp.varInsert(__Vfinal,"pcnextF", &(TOP.top__DOT__riscv__DOT__dp__DOT__pcnextF), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv__dp.varInsert(__Vfinal,"pcplus4D", &(TOP.top__DOT__riscv__DOT__dp__DOT__pcplus4D), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv__dp.varInsert(__Vfinal,"pcplus4E", &(TOP.top__DOT__riscv__DOT__dp__DOT__pcplus4E), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv__dp.varInsert(__Vfinal,"pcplus4F", &(TOP.top__DOT__riscv__DOT__dp__DOT__pcplus4F), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv__dp.varInsert(__Vfinal,"pcplus4M", &(TOP.top__DOT__riscv__DOT__dp__DOT__pcplus4M), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv__dp.varInsert(__Vfinal,"pcplus4W", &(TOP.top__DOT__riscv__DOT__dp__DOT__pcplus4W), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv__dp.varInsert(__Vfinal,"pcsrcE", &(TOP.top__DOT__riscv__DOT__dp__DOT__pcsrcE), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__riscv__dp.varInsert(__Vfinal,"pctargetE", &(TOP.top__DOT__riscv__DOT__dp__DOT__pctargetE), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv__dp.varInsert(__Vfinal,"rd1D", &(TOP.top__DOT__riscv__DOT__dp__DOT__rd1D), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv__dp.varInsert(__Vfinal,"rd1E", &(TOP.top__DOT__riscv__DOT__dp__DOT__rd1E), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv__dp.varInsert(__Vfinal,"rd2D", &(TOP.top__DOT__riscv__DOT__dp__DOT__rd2D), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv__dp.varInsert(__Vfinal,"rd2E", &(TOP.top__DOT__riscv__DOT__dp__DOT__rd2E), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv__dp.varInsert(__Vfinal,"rdD", &(TOP.top__DOT__riscv__DOT__dp__DOT__rdD), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_top__riscv__dp.varInsert(__Vfinal,"rdE", &(TOP.top__DOT__riscv__DOT__dp__DOT__rdE), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_top__riscv__dp.varInsert(__Vfinal,"rdM", &(TOP.top__DOT__riscv__DOT__dp__DOT__rdM), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_top__riscv__dp.varInsert(__Vfinal,"rdW", &(TOP.top__DOT__riscv__DOT__dp__DOT__rdW), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_top__riscv__dp.varInsert(__Vfinal,"readdataM", &(TOP.top__DOT__riscv__DOT__dp__DOT__readdataM), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv__dp.varInsert(__Vfinal,"readdataW", &(TOP.top__DOT__riscv__DOT__dp__DOT__readdataW), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv__dp.varInsert(__Vfinal,"regwriteW", &(TOP.top__DOT__riscv__DOT__dp__DOT__regwriteW), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__riscv__dp.varInsert(__Vfinal,"resultW", &(TOP.top__DOT__riscv__DOT__dp__DOT__resultW), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv__dp.varInsert(__Vfinal,"resultsrcW", &(TOP.top__DOT__riscv__DOT__dp__DOT__resultsrcW), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_top__riscv__dp.varInsert(__Vfinal,"rs1D", &(TOP.top__DOT__riscv__DOT__dp__DOT__rs1D), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_top__riscv__dp.varInsert(__Vfinal,"rs1E", &(TOP.top__DOT__riscv__DOT__dp__DOT__rs1E), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_top__riscv__dp.varInsert(__Vfinal,"rs2D", &(TOP.top__DOT__riscv__DOT__dp__DOT__rs2D), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_top__riscv__dp.varInsert(__Vfinal,"rs2E", &(TOP.top__DOT__riscv__DOT__dp__DOT__rs2E), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_top__riscv__dp.varInsert(__Vfinal,"rst", &(TOP.top__DOT__riscv__DOT__dp__DOT__rst), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__riscv__dp.varInsert(__Vfinal,"srcaE", &(TOP.top__DOT__riscv__DOT__dp__DOT__srcaE), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv__dp.varInsert(__Vfinal,"srcbE", &(TOP.top__DOT__riscv__DOT__dp__DOT__srcbE), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv__dp.varInsert(__Vfinal,"stallD", &(TOP.top__DOT__riscv__DOT__dp__DOT__stallD), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__riscv__dp.varInsert(__Vfinal,"stallF", &(TOP.top__DOT__riscv__DOT__dp__DOT__stallF), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__riscv__dp.varInsert(__Vfinal,"writedataE", &(TOP.top__DOT__riscv__DOT__dp__DOT__writedataE), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv__dp.varInsert(__Vfinal,"writedataM", &(TOP.top__DOT__riscv__DOT__dp__DOT__writedataM), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv__dp.varInsert(__Vfinal,"zeroE", &(TOP.top__DOT__riscv__DOT__dp__DOT__zeroE), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__riscv__dp__adderE.varInsert(__Vfinal,"WIDTH", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__riscv__DOT__dp__DOT__adderE__DOT__WIDTH))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv__dp__adderE.varInsert(__Vfinal,"a", &(TOP.top__DOT__riscv__DOT__dp__DOT__adderE__DOT__a), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv__dp__adderE.varInsert(__Vfinal,"b", &(TOP.top__DOT__riscv__DOT__dp__DOT__adderE__DOT__b), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv__dp__adderE.varInsert(__Vfinal,"y", &(TOP.top__DOT__riscv__DOT__dp__DOT__adderE__DOT__y), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv__dp__adderF.varInsert(__Vfinal,"WIDTH", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__riscv__DOT__dp__DOT__adderF__DOT__WIDTH))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv__dp__adderF.varInsert(__Vfinal,"a", &(TOP.top__DOT__riscv__DOT__dp__DOT__adderF__DOT__a), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv__dp__adderF.varInsert(__Vfinal,"b", &(TOP.top__DOT__riscv__DOT__dp__DOT__adderF__DOT__b), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv__dp__adderF.varInsert(__Vfinal,"y", &(TOP.top__DOT__riscv__DOT__dp__DOT__adderF__DOT__y), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv__dp__alu.varInsert(__Vfinal,"WIDTH", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__riscv__DOT__dp__DOT__alu__DOT__WIDTH))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv__dp__alu.varInsert(__Vfinal,"a", &(TOP.top__DOT__riscv__DOT__dp__DOT__alu__DOT__a), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv__dp__alu.varInsert(__Vfinal,"b", &(TOP.top__DOT__riscv__DOT__dp__DOT__alu__DOT__b), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv__dp__alu.varInsert(__Vfinal,"f", &(TOP.top__DOT__riscv__DOT__dp__DOT__alu__DOT__f), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_top__riscv__dp__alu.varInsert(__Vfinal,"y", &(TOP.top__DOT__riscv__DOT__dp__DOT__alu__DOT__y), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv__dp__alu.varInsert(__Vfinal,"zero", &(TOP.top__DOT__riscv__DOT__dp__DOT__alu__DOT__zero), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__riscv__dp__alumux.varInsert(__Vfinal,"WIDTH", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__riscv__DOT__dp__DOT__alumux__DOT__WIDTH))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv__dp__alumux.varInsert(__Vfinal,"a", &(TOP.top__DOT__riscv__DOT__dp__DOT__alumux__DOT__a), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv__dp__alumux.varInsert(__Vfinal,"b", &(TOP.top__DOT__riscv__DOT__dp__DOT__alumux__DOT__b), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv__dp__alumux.varInsert(__Vfinal,"sel", &(TOP.top__DOT__riscv__DOT__dp__DOT__alumux__DOT__sel), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__riscv__dp__alumux.varInsert(__Vfinal,"y", &(TOP.top__DOT__riscv__DOT__dp__DOT__alumux__DOT__y), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv__dp__ext.varInsert(__Vfinal,"OUTWIDTH", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__riscv__DOT__dp__DOT__ext__DOT__OUTWIDTH))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv__dp__ext.varInsert(__Vfinal,"immext", &(TOP.top__DOT__riscv__DOT__dp__DOT__ext__DOT__immext), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv__dp__ext.varInsert(__Vfinal,"immsrc", &(TOP.top__DOT__riscv__DOT__dp__DOT__ext__DOT__immsrc), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_top__riscv__dp__ext.varInsert(__Vfinal,"instr", &(TOP.top__DOT__riscv__DOT__dp__DOT__ext__DOT__instr), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,7);
        __Vscope_top__riscv__dp__fmuxa.varInsert(__Vfinal,"WIDTH", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__riscv__DOT__dp__DOT__fmuxa__DOT__WIDTH))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv__dp__fmuxa.varInsert(__Vfinal,"a", &(TOP.top__DOT__riscv__DOT__dp__DOT__fmuxa__DOT__a), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv__dp__fmuxa.varInsert(__Vfinal,"b", &(TOP.top__DOT__riscv__DOT__dp__DOT__fmuxa__DOT__b), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv__dp__fmuxa.varInsert(__Vfinal,"c", &(TOP.top__DOT__riscv__DOT__dp__DOT__fmuxa__DOT__c), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv__dp__fmuxa.varInsert(__Vfinal,"sel", &(TOP.top__DOT__riscv__DOT__dp__DOT__fmuxa__DOT__sel), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_top__riscv__dp__fmuxa.varInsert(__Vfinal,"y", &(TOP.top__DOT__riscv__DOT__dp__DOT__fmuxa__DOT__y), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv__dp__fmuxb.varInsert(__Vfinal,"WIDTH", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__riscv__DOT__dp__DOT__fmuxb__DOT__WIDTH))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv__dp__fmuxb.varInsert(__Vfinal,"a", &(TOP.top__DOT__riscv__DOT__dp__DOT__fmuxb__DOT__a), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv__dp__fmuxb.varInsert(__Vfinal,"b", &(TOP.top__DOT__riscv__DOT__dp__DOT__fmuxb__DOT__b), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv__dp__fmuxb.varInsert(__Vfinal,"c", &(TOP.top__DOT__riscv__DOT__dp__DOT__fmuxb__DOT__c), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv__dp__fmuxb.varInsert(__Vfinal,"sel", &(TOP.top__DOT__riscv__DOT__dp__DOT__fmuxb__DOT__sel), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_top__riscv__dp__fmuxb.varInsert(__Vfinal,"y", &(TOP.top__DOT__riscv__DOT__dp__DOT__fmuxb__DOT__y), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv__dp__pc.varInsert(__Vfinal,"WIDTH", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__riscv__DOT__dp__DOT__pc__DOT__WIDTH))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv__dp__pc.varInsert(__Vfinal,"clk", &(TOP.top__DOT__riscv__DOT__dp__DOT__pc__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__riscv__dp__pc.varInsert(__Vfinal,"d", &(TOP.top__DOT__riscv__DOT__dp__DOT__pc__DOT__d), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv__dp__pc.varInsert(__Vfinal,"en", &(TOP.top__DOT__riscv__DOT__dp__DOT__pc__DOT__en), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__riscv__dp__pc.varInsert(__Vfinal,"q", &(TOP.top__DOT__riscv__DOT__dp__DOT__pc__DOT__q), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv__dp__pc.varInsert(__Vfinal,"rst", &(TOP.top__DOT__riscv__DOT__dp__DOT__pc__DOT__rst), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__riscv__dp__pcmux.varInsert(__Vfinal,"WIDTH", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__riscv__DOT__dp__DOT__pcmux__DOT__WIDTH))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv__dp__pcmux.varInsert(__Vfinal,"a", &(TOP.top__DOT__riscv__DOT__dp__DOT__pcmux__DOT__a), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv__dp__pcmux.varInsert(__Vfinal,"b", &(TOP.top__DOT__riscv__DOT__dp__DOT__pcmux__DOT__b), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv__dp__pcmux.varInsert(__Vfinal,"sel", &(TOP.top__DOT__riscv__DOT__dp__DOT__pcmux__DOT__sel), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__riscv__dp__pcmux.varInsert(__Vfinal,"y", &(TOP.top__DOT__riscv__DOT__dp__DOT__pcmux__DOT__y), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv__dp__regD1.varInsert(__Vfinal,"WIDTH", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__riscv__DOT__dp__DOT__regD1__DOT__WIDTH))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv__dp__regD1.varInsert(__Vfinal,"clear", &(TOP.top__DOT__riscv__DOT__dp__DOT__regD1__DOT__clear), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__riscv__dp__regD1.varInsert(__Vfinal,"clk", &(TOP.top__DOT__riscv__DOT__dp__DOT__regD1__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__riscv__dp__regD1.varInsert(__Vfinal,"d", &(TOP.top__DOT__riscv__DOT__dp__DOT__regD1__DOT__d), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv__dp__regD1.varInsert(__Vfinal,"en", &(TOP.top__DOT__riscv__DOT__dp__DOT__regD1__DOT__en), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__riscv__dp__regD1.varInsert(__Vfinal,"q", &(TOP.top__DOT__riscv__DOT__dp__DOT__regD1__DOT__q), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv__dp__regD1.varInsert(__Vfinal,"rst", &(TOP.top__DOT__riscv__DOT__dp__DOT__regD1__DOT__rst), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__riscv__dp__regD2.varInsert(__Vfinal,"WIDTH", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__riscv__DOT__dp__DOT__regD2__DOT__WIDTH))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv__dp__regD2.varInsert(__Vfinal,"clear", &(TOP.top__DOT__riscv__DOT__dp__DOT__regD2__DOT__clear), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__riscv__dp__regD2.varInsert(__Vfinal,"clk", &(TOP.top__DOT__riscv__DOT__dp__DOT__regD2__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__riscv__dp__regD2.varInsert(__Vfinal,"d", &(TOP.top__DOT__riscv__DOT__dp__DOT__regD2__DOT__d), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv__dp__regD2.varInsert(__Vfinal,"en", &(TOP.top__DOT__riscv__DOT__dp__DOT__regD2__DOT__en), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__riscv__dp__regD2.varInsert(__Vfinal,"q", &(TOP.top__DOT__riscv__DOT__dp__DOT__regD2__DOT__q), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv__dp__regD2.varInsert(__Vfinal,"rst", &(TOP.top__DOT__riscv__DOT__dp__DOT__regD2__DOT__rst), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__riscv__dp__regD3.varInsert(__Vfinal,"WIDTH", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__riscv__DOT__dp__DOT__regD3__DOT__WIDTH))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv__dp__regD3.varInsert(__Vfinal,"clear", &(TOP.top__DOT__riscv__DOT__dp__DOT__regD3__DOT__clear), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__riscv__dp__regD3.varInsert(__Vfinal,"clk", &(TOP.top__DOT__riscv__DOT__dp__DOT__regD3__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__riscv__dp__regD3.varInsert(__Vfinal,"d", &(TOP.top__DOT__riscv__DOT__dp__DOT__regD3__DOT__d), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv__dp__regD3.varInsert(__Vfinal,"en", &(TOP.top__DOT__riscv__DOT__dp__DOT__regD3__DOT__en), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__riscv__dp__regD3.varInsert(__Vfinal,"q", &(TOP.top__DOT__riscv__DOT__dp__DOT__regD3__DOT__q), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv__dp__regD3.varInsert(__Vfinal,"rst", &(TOP.top__DOT__riscv__DOT__dp__DOT__regD3__DOT__rst), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__riscv__dp__regE1.varInsert(__Vfinal,"WIDTH", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__riscv__DOT__dp__DOT__regE1__DOT__WIDTH))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv__dp__regE1.varInsert(__Vfinal,"clear", &(TOP.top__DOT__riscv__DOT__dp__DOT__regE1__DOT__clear), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__riscv__dp__regE1.varInsert(__Vfinal,"clk", &(TOP.top__DOT__riscv__DOT__dp__DOT__regE1__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__riscv__dp__regE1.varInsert(__Vfinal,"d", &(TOP.top__DOT__riscv__DOT__dp__DOT__regE1__DOT__d), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv__dp__regE1.varInsert(__Vfinal,"q", &(TOP.top__DOT__riscv__DOT__dp__DOT__regE1__DOT__q), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv__dp__regE1.varInsert(__Vfinal,"rst", &(TOP.top__DOT__riscv__DOT__dp__DOT__regE1__DOT__rst), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__riscv__dp__regE2.varInsert(__Vfinal,"WIDTH", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__riscv__DOT__dp__DOT__regE2__DOT__WIDTH))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv__dp__regE2.varInsert(__Vfinal,"clear", &(TOP.top__DOT__riscv__DOT__dp__DOT__regE2__DOT__clear), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__riscv__dp__regE2.varInsert(__Vfinal,"clk", &(TOP.top__DOT__riscv__DOT__dp__DOT__regE2__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__riscv__dp__regE2.varInsert(__Vfinal,"d", &(TOP.top__DOT__riscv__DOT__dp__DOT__regE2__DOT__d), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv__dp__regE2.varInsert(__Vfinal,"q", &(TOP.top__DOT__riscv__DOT__dp__DOT__regE2__DOT__q), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv__dp__regE2.varInsert(__Vfinal,"rst", &(TOP.top__DOT__riscv__DOT__dp__DOT__regE2__DOT__rst), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__riscv__dp__regE3.varInsert(__Vfinal,"WIDTH", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__riscv__DOT__dp__DOT__regE3__DOT__WIDTH))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv__dp__regE3.varInsert(__Vfinal,"clear", &(TOP.top__DOT__riscv__DOT__dp__DOT__regE3__DOT__clear), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__riscv__dp__regE3.varInsert(__Vfinal,"clk", &(TOP.top__DOT__riscv__DOT__dp__DOT__regE3__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__riscv__dp__regE3.varInsert(__Vfinal,"d", &(TOP.top__DOT__riscv__DOT__dp__DOT__regE3__DOT__d), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv__dp__regE3.varInsert(__Vfinal,"q", &(TOP.top__DOT__riscv__DOT__dp__DOT__regE3__DOT__q), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv__dp__regE3.varInsert(__Vfinal,"rst", &(TOP.top__DOT__riscv__DOT__dp__DOT__regE3__DOT__rst), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__riscv__dp__regE4.varInsert(__Vfinal,"WIDTH", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__riscv__DOT__dp__DOT__regE4__DOT__WIDTH))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv__dp__regE4.varInsert(__Vfinal,"clear", &(TOP.top__DOT__riscv__DOT__dp__DOT__regE4__DOT__clear), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__riscv__dp__regE4.varInsert(__Vfinal,"clk", &(TOP.top__DOT__riscv__DOT__dp__DOT__regE4__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__riscv__dp__regE4.varInsert(__Vfinal,"d", &(TOP.top__DOT__riscv__DOT__dp__DOT__regE4__DOT__d), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_top__riscv__dp__regE4.varInsert(__Vfinal,"q", &(TOP.top__DOT__riscv__DOT__dp__DOT__regE4__DOT__q), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_top__riscv__dp__regE4.varInsert(__Vfinal,"rst", &(TOP.top__DOT__riscv__DOT__dp__DOT__regE4__DOT__rst), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__riscv__dp__regE5.varInsert(__Vfinal,"WIDTH", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__riscv__DOT__dp__DOT__regE5__DOT__WIDTH))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv__dp__regE5.varInsert(__Vfinal,"clear", &(TOP.top__DOT__riscv__DOT__dp__DOT__regE5__DOT__clear), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__riscv__dp__regE5.varInsert(__Vfinal,"clk", &(TOP.top__DOT__riscv__DOT__dp__DOT__regE5__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__riscv__dp__regE5.varInsert(__Vfinal,"d", &(TOP.top__DOT__riscv__DOT__dp__DOT__regE5__DOT__d), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_top__riscv__dp__regE5.varInsert(__Vfinal,"q", &(TOP.top__DOT__riscv__DOT__dp__DOT__regE5__DOT__q), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_top__riscv__dp__regE5.varInsert(__Vfinal,"rst", &(TOP.top__DOT__riscv__DOT__dp__DOT__regE5__DOT__rst), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__riscv__dp__regE6.varInsert(__Vfinal,"WIDTH", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__riscv__DOT__dp__DOT__regE6__DOT__WIDTH))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv__dp__regE6.varInsert(__Vfinal,"clear", &(TOP.top__DOT__riscv__DOT__dp__DOT__regE6__DOT__clear), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__riscv__dp__regE6.varInsert(__Vfinal,"clk", &(TOP.top__DOT__riscv__DOT__dp__DOT__regE6__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__riscv__dp__regE6.varInsert(__Vfinal,"d", &(TOP.top__DOT__riscv__DOT__dp__DOT__regE6__DOT__d), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_top__riscv__dp__regE6.varInsert(__Vfinal,"q", &(TOP.top__DOT__riscv__DOT__dp__DOT__regE6__DOT__q), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_top__riscv__dp__regE6.varInsert(__Vfinal,"rst", &(TOP.top__DOT__riscv__DOT__dp__DOT__regE6__DOT__rst), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__riscv__dp__regE7.varInsert(__Vfinal,"WIDTH", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__riscv__DOT__dp__DOT__regE7__DOT__WIDTH))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv__dp__regE7.varInsert(__Vfinal,"clear", &(TOP.top__DOT__riscv__DOT__dp__DOT__regE7__DOT__clear), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__riscv__dp__regE7.varInsert(__Vfinal,"clk", &(TOP.top__DOT__riscv__DOT__dp__DOT__regE7__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__riscv__dp__regE7.varInsert(__Vfinal,"d", &(TOP.top__DOT__riscv__DOT__dp__DOT__regE7__DOT__d), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv__dp__regE7.varInsert(__Vfinal,"q", &(TOP.top__DOT__riscv__DOT__dp__DOT__regE7__DOT__q), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv__dp__regE7.varInsert(__Vfinal,"rst", &(TOP.top__DOT__riscv__DOT__dp__DOT__regE7__DOT__rst), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__riscv__dp__regE8.varInsert(__Vfinal,"WIDTH", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__riscv__DOT__dp__DOT__regE8__DOT__WIDTH))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv__dp__regE8.varInsert(__Vfinal,"clear", &(TOP.top__DOT__riscv__DOT__dp__DOT__regE8__DOT__clear), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__riscv__dp__regE8.varInsert(__Vfinal,"clk", &(TOP.top__DOT__riscv__DOT__dp__DOT__regE8__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__riscv__dp__regE8.varInsert(__Vfinal,"d", &(TOP.top__DOT__riscv__DOT__dp__DOT__regE8__DOT__d), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv__dp__regE8.varInsert(__Vfinal,"q", &(TOP.top__DOT__riscv__DOT__dp__DOT__regE8__DOT__q), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv__dp__regE8.varInsert(__Vfinal,"rst", &(TOP.top__DOT__riscv__DOT__dp__DOT__regE8__DOT__rst), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__riscv__dp__regM1.varInsert(__Vfinal,"WIDTH", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__riscv__DOT__dp__DOT__regM1__DOT__WIDTH))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv__dp__regM1.varInsert(__Vfinal,"clk", &(TOP.top__DOT__riscv__DOT__dp__DOT__regM1__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__riscv__dp__regM1.varInsert(__Vfinal,"d", &(TOP.top__DOT__riscv__DOT__dp__DOT__regM1__DOT__d), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv__dp__regM1.varInsert(__Vfinal,"q", &(TOP.top__DOT__riscv__DOT__dp__DOT__regM1__DOT__q), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv__dp__regM1.varInsert(__Vfinal,"rst", &(TOP.top__DOT__riscv__DOT__dp__DOT__regM1__DOT__rst), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__riscv__dp__regM2.varInsert(__Vfinal,"WIDTH", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__riscv__DOT__dp__DOT__regM2__DOT__WIDTH))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv__dp__regM2.varInsert(__Vfinal,"clk", &(TOP.top__DOT__riscv__DOT__dp__DOT__regM2__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__riscv__dp__regM2.varInsert(__Vfinal,"d", &(TOP.top__DOT__riscv__DOT__dp__DOT__regM2__DOT__d), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv__dp__regM2.varInsert(__Vfinal,"q", &(TOP.top__DOT__riscv__DOT__dp__DOT__regM2__DOT__q), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv__dp__regM2.varInsert(__Vfinal,"rst", &(TOP.top__DOT__riscv__DOT__dp__DOT__regM2__DOT__rst), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__riscv__dp__regM3.varInsert(__Vfinal,"WIDTH", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__riscv__DOT__dp__DOT__regM3__DOT__WIDTH))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv__dp__regM3.varInsert(__Vfinal,"clk", &(TOP.top__DOT__riscv__DOT__dp__DOT__regM3__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__riscv__dp__regM3.varInsert(__Vfinal,"d", &(TOP.top__DOT__riscv__DOT__dp__DOT__regM3__DOT__d), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_top__riscv__dp__regM3.varInsert(__Vfinal,"q", &(TOP.top__DOT__riscv__DOT__dp__DOT__regM3__DOT__q), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_top__riscv__dp__regM3.varInsert(__Vfinal,"rst", &(TOP.top__DOT__riscv__DOT__dp__DOT__regM3__DOT__rst), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__riscv__dp__regM4.varInsert(__Vfinal,"WIDTH", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__riscv__DOT__dp__DOT__regM4__DOT__WIDTH))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv__dp__regM4.varInsert(__Vfinal,"clk", &(TOP.top__DOT__riscv__DOT__dp__DOT__regM4__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__riscv__dp__regM4.varInsert(__Vfinal,"d", &(TOP.top__DOT__riscv__DOT__dp__DOT__regM4__DOT__d), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv__dp__regM4.varInsert(__Vfinal,"q", &(TOP.top__DOT__riscv__DOT__dp__DOT__regM4__DOT__q), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv__dp__regM4.varInsert(__Vfinal,"rst", &(TOP.top__DOT__riscv__DOT__dp__DOT__regM4__DOT__rst), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__riscv__dp__regW1.varInsert(__Vfinal,"WIDTH", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__riscv__DOT__dp__DOT__regW1__DOT__WIDTH))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv__dp__regW1.varInsert(__Vfinal,"clk", &(TOP.top__DOT__riscv__DOT__dp__DOT__regW1__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__riscv__dp__regW1.varInsert(__Vfinal,"d", &(TOP.top__DOT__riscv__DOT__dp__DOT__regW1__DOT__d), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv__dp__regW1.varInsert(__Vfinal,"q", &(TOP.top__DOT__riscv__DOT__dp__DOT__regW1__DOT__q), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv__dp__regW1.varInsert(__Vfinal,"rst", &(TOP.top__DOT__riscv__DOT__dp__DOT__regW1__DOT__rst), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__riscv__dp__regW2.varInsert(__Vfinal,"WIDTH", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__riscv__DOT__dp__DOT__regW2__DOT__WIDTH))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv__dp__regW2.varInsert(__Vfinal,"clk", &(TOP.top__DOT__riscv__DOT__dp__DOT__regW2__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__riscv__dp__regW2.varInsert(__Vfinal,"d", &(TOP.top__DOT__riscv__DOT__dp__DOT__regW2__DOT__d), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv__dp__regW2.varInsert(__Vfinal,"q", &(TOP.top__DOT__riscv__DOT__dp__DOT__regW2__DOT__q), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv__dp__regW2.varInsert(__Vfinal,"rst", &(TOP.top__DOT__riscv__DOT__dp__DOT__regW2__DOT__rst), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__riscv__dp__regW3.varInsert(__Vfinal,"WIDTH", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__riscv__DOT__dp__DOT__regW3__DOT__WIDTH))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv__dp__regW3.varInsert(__Vfinal,"clk", &(TOP.top__DOT__riscv__DOT__dp__DOT__regW3__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__riscv__dp__regW3.varInsert(__Vfinal,"d", &(TOP.top__DOT__riscv__DOT__dp__DOT__regW3__DOT__d), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_top__riscv__dp__regW3.varInsert(__Vfinal,"q", &(TOP.top__DOT__riscv__DOT__dp__DOT__regW3__DOT__q), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_top__riscv__dp__regW3.varInsert(__Vfinal,"rst", &(TOP.top__DOT__riscv__DOT__dp__DOT__regW3__DOT__rst), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__riscv__dp__regW4.varInsert(__Vfinal,"WIDTH", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__riscv__DOT__dp__DOT__regW4__DOT__WIDTH))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv__dp__regW4.varInsert(__Vfinal,"clk", &(TOP.top__DOT__riscv__DOT__dp__DOT__regW4__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__riscv__dp__regW4.varInsert(__Vfinal,"d", &(TOP.top__DOT__riscv__DOT__dp__DOT__regW4__DOT__d), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv__dp__regW4.varInsert(__Vfinal,"q", &(TOP.top__DOT__riscv__DOT__dp__DOT__regW4__DOT__q), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv__dp__regW4.varInsert(__Vfinal,"rst", &(TOP.top__DOT__riscv__DOT__dp__DOT__regW4__DOT__rst), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__riscv__dp__resultmux.varInsert(__Vfinal,"WIDTH", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__riscv__DOT__dp__DOT__resultmux__DOT__WIDTH))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv__dp__resultmux.varInsert(__Vfinal,"a", &(TOP.top__DOT__riscv__DOT__dp__DOT__resultmux__DOT__a), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv__dp__resultmux.varInsert(__Vfinal,"b", &(TOP.top__DOT__riscv__DOT__dp__DOT__resultmux__DOT__b), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv__dp__resultmux.varInsert(__Vfinal,"c", &(TOP.top__DOT__riscv__DOT__dp__DOT__resultmux__DOT__c), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv__dp__resultmux.varInsert(__Vfinal,"sel", &(TOP.top__DOT__riscv__DOT__dp__DOT__resultmux__DOT__sel), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_top__riscv__dp__resultmux.varInsert(__Vfinal,"y", &(TOP.top__DOT__riscv__DOT__dp__DOT__resultmux__DOT__y), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv__dp__rf.varInsert(__Vfinal,"WIDTH", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__riscv__DOT__dp__DOT__rf__DOT__WIDTH))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv__dp__rf.varInsert(__Vfinal,"clk", &(TOP.top__DOT__riscv__DOT__dp__DOT__rf__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__riscv__dp__rf.varInsert(__Vfinal,"ra1", &(TOP.top__DOT__riscv__DOT__dp__DOT__rf__DOT__ra1), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_top__riscv__dp__rf.varInsert(__Vfinal,"ra2", &(TOP.top__DOT__riscv__DOT__dp__DOT__rf__DOT__ra2), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_top__riscv__dp__rf.varInsert(__Vfinal,"rd1", &(TOP.top__DOT__riscv__DOT__dp__DOT__rf__DOT__rd1), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv__dp__rf.varInsert(__Vfinal,"rd2", &(TOP.top__DOT__riscv__DOT__dp__DOT__rf__DOT__rd2), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv__dp__rf.varInsert(__Vfinal,"rf", &(TOP.top__DOT__riscv__DOT__dp__DOT__rf__DOT__rf), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1,1 ,31,0 ,31,0);
        __Vscope_top__riscv__dp__rf.varInsert(__Vfinal,"wa3", &(TOP.top__DOT__riscv__DOT__dp__DOT__rf__DOT__wa3), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_top__riscv__dp__rf.varInsert(__Vfinal,"wd3", &(TOP.top__DOT__riscv__DOT__dp__DOT__rf__DOT__wd3), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_top__riscv__dp__rf.varInsert(__Vfinal,"we3", &(TOP.top__DOT__riscv__DOT__dp__DOT__rf__DOT__we3), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__riscv__hu.varInsert(__Vfinal,"flushD", &(TOP.top__DOT__riscv__DOT__hu__DOT__flushD), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__riscv__hu.varInsert(__Vfinal,"flushE", &(TOP.top__DOT__riscv__DOT__hu__DOT__flushE), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__riscv__hu.varInsert(__Vfinal,"forwardAE", &(TOP.top__DOT__riscv__DOT__hu__DOT__forwardAE), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_top__riscv__hu.varInsert(__Vfinal,"forwardBE", &(TOP.top__DOT__riscv__DOT__hu__DOT__forwardBE), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_top__riscv__hu.varInsert(__Vfinal,"lwstall", &(TOP.top__DOT__riscv__DOT__hu__DOT__lwstall), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__riscv__hu.varInsert(__Vfinal,"pcsrcE", &(TOP.top__DOT__riscv__DOT__hu__DOT__pcsrcE), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__riscv__hu.varInsert(__Vfinal,"rdE", &(TOP.top__DOT__riscv__DOT__hu__DOT__rdE), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_top__riscv__hu.varInsert(__Vfinal,"rdM", &(TOP.top__DOT__riscv__DOT__hu__DOT__rdM), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_top__riscv__hu.varInsert(__Vfinal,"rdW", &(TOP.top__DOT__riscv__DOT__hu__DOT__rdW), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_top__riscv__hu.varInsert(__Vfinal,"regwriteM", &(TOP.top__DOT__riscv__DOT__hu__DOT__regwriteM), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__riscv__hu.varInsert(__Vfinal,"regwriteW", &(TOP.top__DOT__riscv__DOT__hu__DOT__regwriteW), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__riscv__hu.varInsert(__Vfinal,"resultsrcE", &(TOP.top__DOT__riscv__DOT__hu__DOT__resultsrcE), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_top__riscv__hu.varInsert(__Vfinal,"rs1D", &(TOP.top__DOT__riscv__DOT__hu__DOT__rs1D), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_top__riscv__hu.varInsert(__Vfinal,"rs1E", &(TOP.top__DOT__riscv__DOT__hu__DOT__rs1E), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_top__riscv__hu.varInsert(__Vfinal,"rs2D", &(TOP.top__DOT__riscv__DOT__hu__DOT__rs2D), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_top__riscv__hu.varInsert(__Vfinal,"rs2E", &(TOP.top__DOT__riscv__DOT__hu__DOT__rs2E), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_top__riscv__hu.varInsert(__Vfinal,"stallD", &(TOP.top__DOT__riscv__DOT__hu__DOT__stallD), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_top__riscv__hu.varInsert(__Vfinal,"stallF", &(TOP.top__DOT__riscv__DOT__hu__DOT__stallF), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
    }
}
