// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vtop.h for the primary calling header

#ifndef VERILATED_VTOP___024ROOT_H_
#define VERILATED_VTOP___024ROOT_H_  // guard

#include "verilated.h"


class Vtop__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vtop___024root final : public VerilatedModule {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clk,0,0);
        VL_IN8(rst,0,0);
        VL_OUT8(memwrite,0,0);
        CData/*0:0*/ top__DOT__clk;
        CData/*0:0*/ top__DOT__rst;
        CData/*0:0*/ top__DOT__memwrite;
        CData/*0:0*/ top__DOT__riscv__DOT__clk;
        CData/*0:0*/ top__DOT__riscv__DOT__rst;
        CData/*0:0*/ top__DOT__riscv__DOT__memwriteM;
        CData/*6:0*/ top__DOT__riscv__DOT__op;
        CData/*2:0*/ top__DOT__riscv__DOT__funct3;
        CData/*0:0*/ top__DOT__riscv__DOT__funct7b5;
        CData/*0:0*/ top__DOT__riscv__DOT__stallF;
        CData/*0:0*/ top__DOT__riscv__DOT__stallD;
        CData/*0:0*/ top__DOT__riscv__DOT__flushD;
        CData/*1:0*/ top__DOT__riscv__DOT__immsrcD;
        CData/*4:0*/ top__DOT__riscv__DOT__rs1D;
        CData/*4:0*/ top__DOT__riscv__DOT__rs2D;
        CData/*0:0*/ top__DOT__riscv__DOT__zeroE;
        CData/*0:0*/ top__DOT__riscv__DOT__pcsrcE;
        CData/*0:0*/ top__DOT__riscv__DOT__alusrcE;
        CData/*0:0*/ top__DOT__riscv__DOT__flushE;
        CData/*1:0*/ top__DOT__riscv__DOT__resultsrcE;
        CData/*1:0*/ top__DOT__riscv__DOT__forwardAE;
        CData/*1:0*/ top__DOT__riscv__DOT__forwardBE;
        CData/*2:0*/ top__DOT__riscv__DOT__alucontrolE;
        CData/*4:0*/ top__DOT__riscv__DOT__rs1E;
        CData/*4:0*/ top__DOT__riscv__DOT__rs2E;
        CData/*4:0*/ top__DOT__riscv__DOT__rdE;
        CData/*0:0*/ top__DOT__riscv__DOT__regwriteM;
        CData/*4:0*/ top__DOT__riscv__DOT__rdM;
        CData/*0:0*/ top__DOT__riscv__DOT__regwriteW;
        CData/*1:0*/ top__DOT__riscv__DOT__resultsrcW;
        CData/*4:0*/ top__DOT__riscv__DOT__rdW;
        CData/*0:0*/ top__DOT__riscv__DOT__dp__DOT__clk;
        CData/*0:0*/ top__DOT__riscv__DOT__dp__DOT__rst;
        CData/*0:0*/ top__DOT__riscv__DOT__dp__DOT__pcsrcE;
        CData/*0:0*/ top__DOT__riscv__DOT__dp__DOT__stallF;
        CData/*1:0*/ top__DOT__riscv__DOT__dp__DOT__immsrcD;
        CData/*0:0*/ top__DOT__riscv__DOT__dp__DOT__stallD;
        CData/*0:0*/ top__DOT__riscv__DOT__dp__DOT__flushD;
        CData/*0:0*/ top__DOT__riscv__DOT__dp__DOT__regwriteW;
        CData/*6:0*/ top__DOT__riscv__DOT__dp__DOT__op;
        CData/*2:0*/ top__DOT__riscv__DOT__dp__DOT__funct3;
        CData/*0:0*/ top__DOT__riscv__DOT__dp__DOT__funct7b5;
        CData/*4:0*/ top__DOT__riscv__DOT__dp__DOT__rs1D;
        CData/*4:0*/ top__DOT__riscv__DOT__dp__DOT__rs2D;
        CData/*0:0*/ top__DOT__riscv__DOT__dp__DOT__flushE;
        CData/*1:0*/ top__DOT__riscv__DOT__dp__DOT__forwardAE;
        CData/*1:0*/ top__DOT__riscv__DOT__dp__DOT__forwardBE;
        CData/*2:0*/ top__DOT__riscv__DOT__dp__DOT__alucontrolE;
        CData/*0:0*/ top__DOT__riscv__DOT__dp__DOT__alusrcE;
        CData/*4:0*/ top__DOT__riscv__DOT__dp__DOT__rs1E;
        CData/*4:0*/ top__DOT__riscv__DOT__dp__DOT__rs2E;
        CData/*4:0*/ top__DOT__riscv__DOT__dp__DOT__rdE;
        CData/*0:0*/ top__DOT__riscv__DOT__dp__DOT__zeroE;
        CData/*4:0*/ top__DOT__riscv__DOT__dp__DOT__rdM;
        CData/*1:0*/ top__DOT__riscv__DOT__dp__DOT__resultsrcW;
        CData/*4:0*/ top__DOT__riscv__DOT__dp__DOT__rdW;
        CData/*4:0*/ top__DOT__riscv__DOT__dp__DOT__rdD;
        CData/*0:0*/ top__DOT__riscv__DOT__dp__DOT__pcmux__DOT__sel;
        CData/*0:0*/ top__DOT__riscv__DOT__dp__DOT__pc__DOT__clk;
        CData/*0:0*/ top__DOT__riscv__DOT__dp__DOT__pc__DOT__rst;
        CData/*0:0*/ top__DOT__riscv__DOT__dp__DOT__pc__DOT__en;
    };
    struct {
        CData/*0:0*/ top__DOT__riscv__DOT__dp__DOT__regD1__DOT__clk;
        CData/*0:0*/ top__DOT__riscv__DOT__dp__DOT__regD1__DOT__rst;
        CData/*0:0*/ top__DOT__riscv__DOT__dp__DOT__regD1__DOT__en;
        CData/*0:0*/ top__DOT__riscv__DOT__dp__DOT__regD1__DOT__clear;
        CData/*0:0*/ top__DOT__riscv__DOT__dp__DOT__regD2__DOT__clk;
        CData/*0:0*/ top__DOT__riscv__DOT__dp__DOT__regD2__DOT__rst;
        CData/*0:0*/ top__DOT__riscv__DOT__dp__DOT__regD2__DOT__en;
        CData/*0:0*/ top__DOT__riscv__DOT__dp__DOT__regD2__DOT__clear;
        CData/*0:0*/ top__DOT__riscv__DOT__dp__DOT__regD3__DOT__clk;
        CData/*0:0*/ top__DOT__riscv__DOT__dp__DOT__regD3__DOT__rst;
        CData/*0:0*/ top__DOT__riscv__DOT__dp__DOT__regD3__DOT__en;
        CData/*0:0*/ top__DOT__riscv__DOT__dp__DOT__regD3__DOT__clear;
        CData/*0:0*/ top__DOT__riscv__DOT__dp__DOT__rf__DOT__clk;
        CData/*0:0*/ top__DOT__riscv__DOT__dp__DOT__rf__DOT__we3;
        CData/*4:0*/ top__DOT__riscv__DOT__dp__DOT__rf__DOT__ra1;
        CData/*4:0*/ top__DOT__riscv__DOT__dp__DOT__rf__DOT__ra2;
        CData/*4:0*/ top__DOT__riscv__DOT__dp__DOT__rf__DOT__wa3;
        CData/*1:0*/ top__DOT__riscv__DOT__dp__DOT__ext__DOT__immsrc;
        CData/*0:0*/ top__DOT__riscv__DOT__dp__DOT__regE1__DOT__clk;
        CData/*0:0*/ top__DOT__riscv__DOT__dp__DOT__regE1__DOT__rst;
        CData/*0:0*/ top__DOT__riscv__DOT__dp__DOT__regE1__DOT__clear;
        CData/*0:0*/ top__DOT__riscv__DOT__dp__DOT__regE2__DOT__clk;
        CData/*0:0*/ top__DOT__riscv__DOT__dp__DOT__regE2__DOT__rst;
        CData/*0:0*/ top__DOT__riscv__DOT__dp__DOT__regE2__DOT__clear;
        CData/*0:0*/ top__DOT__riscv__DOT__dp__DOT__regE3__DOT__clk;
        CData/*0:0*/ top__DOT__riscv__DOT__dp__DOT__regE3__DOT__rst;
        CData/*0:0*/ top__DOT__riscv__DOT__dp__DOT__regE3__DOT__clear;
        CData/*0:0*/ top__DOT__riscv__DOT__dp__DOT__regE4__DOT__clk;
        CData/*0:0*/ top__DOT__riscv__DOT__dp__DOT__regE4__DOT__rst;
        CData/*0:0*/ top__DOT__riscv__DOT__dp__DOT__regE4__DOT__clear;
        CData/*4:0*/ top__DOT__riscv__DOT__dp__DOT__regE4__DOT__d;
        CData/*4:0*/ top__DOT__riscv__DOT__dp__DOT__regE4__DOT__q;
        CData/*0:0*/ top__DOT__riscv__DOT__dp__DOT__regE5__DOT__clk;
        CData/*0:0*/ top__DOT__riscv__DOT__dp__DOT__regE5__DOT__rst;
        CData/*0:0*/ top__DOT__riscv__DOT__dp__DOT__regE5__DOT__clear;
        CData/*4:0*/ top__DOT__riscv__DOT__dp__DOT__regE5__DOT__d;
        CData/*4:0*/ top__DOT__riscv__DOT__dp__DOT__regE5__DOT__q;
        CData/*0:0*/ top__DOT__riscv__DOT__dp__DOT__regE6__DOT__clk;
        CData/*0:0*/ top__DOT__riscv__DOT__dp__DOT__regE6__DOT__rst;
        CData/*0:0*/ top__DOT__riscv__DOT__dp__DOT__regE6__DOT__clear;
        CData/*4:0*/ top__DOT__riscv__DOT__dp__DOT__regE6__DOT__d;
        CData/*4:0*/ top__DOT__riscv__DOT__dp__DOT__regE6__DOT__q;
        CData/*0:0*/ top__DOT__riscv__DOT__dp__DOT__regE7__DOT__clk;
        CData/*0:0*/ top__DOT__riscv__DOT__dp__DOT__regE7__DOT__rst;
        CData/*0:0*/ top__DOT__riscv__DOT__dp__DOT__regE7__DOT__clear;
        CData/*0:0*/ top__DOT__riscv__DOT__dp__DOT__regE8__DOT__clk;
        CData/*0:0*/ top__DOT__riscv__DOT__dp__DOT__regE8__DOT__rst;
        CData/*0:0*/ top__DOT__riscv__DOT__dp__DOT__regE8__DOT__clear;
        CData/*1:0*/ top__DOT__riscv__DOT__dp__DOT__fmuxa__DOT__sel;
        CData/*1:0*/ top__DOT__riscv__DOT__dp__DOT__fmuxb__DOT__sel;
        CData/*0:0*/ top__DOT__riscv__DOT__dp__DOT__alumux__DOT__sel;
        CData/*2:0*/ top__DOT__riscv__DOT__dp__DOT__alu__DOT__f;
        CData/*0:0*/ top__DOT__riscv__DOT__dp__DOT__alu__DOT__zero;
        CData/*0:0*/ top__DOT__riscv__DOT__dp__DOT__regM1__DOT__clk;
        CData/*0:0*/ top__DOT__riscv__DOT__dp__DOT__regM1__DOT__rst;
        CData/*0:0*/ top__DOT__riscv__DOT__dp__DOT__regM2__DOT__clk;
        CData/*0:0*/ top__DOT__riscv__DOT__dp__DOT__regM2__DOT__rst;
        CData/*0:0*/ top__DOT__riscv__DOT__dp__DOT__regM3__DOT__clk;
        CData/*0:0*/ top__DOT__riscv__DOT__dp__DOT__regM3__DOT__rst;
        CData/*4:0*/ top__DOT__riscv__DOT__dp__DOT__regM3__DOT__d;
        CData/*4:0*/ top__DOT__riscv__DOT__dp__DOT__regM3__DOT__q;
        CData/*0:0*/ top__DOT__riscv__DOT__dp__DOT__regM4__DOT__clk;
        CData/*0:0*/ top__DOT__riscv__DOT__dp__DOT__regM4__DOT__rst;
        CData/*0:0*/ top__DOT__riscv__DOT__dp__DOT__regW1__DOT__clk;
    };
    struct {
        CData/*0:0*/ top__DOT__riscv__DOT__dp__DOT__regW1__DOT__rst;
        CData/*0:0*/ top__DOT__riscv__DOT__dp__DOT__regW2__DOT__clk;
        CData/*0:0*/ top__DOT__riscv__DOT__dp__DOT__regW2__DOT__rst;
        CData/*0:0*/ top__DOT__riscv__DOT__dp__DOT__regW3__DOT__clk;
        CData/*0:0*/ top__DOT__riscv__DOT__dp__DOT__regW3__DOT__rst;
        CData/*4:0*/ top__DOT__riscv__DOT__dp__DOT__regW3__DOT__d;
        CData/*4:0*/ top__DOT__riscv__DOT__dp__DOT__regW3__DOT__q;
        CData/*0:0*/ top__DOT__riscv__DOT__dp__DOT__regW4__DOT__clk;
        CData/*0:0*/ top__DOT__riscv__DOT__dp__DOT__regW4__DOT__rst;
        CData/*1:0*/ top__DOT__riscv__DOT__dp__DOT__resultmux__DOT__sel;
        CData/*0:0*/ top__DOT__riscv__DOT__cu__DOT__clk;
        CData/*0:0*/ top__DOT__riscv__DOT__cu__DOT__rst;
        CData/*6:0*/ top__DOT__riscv__DOT__cu__DOT__op;
        CData/*2:0*/ top__DOT__riscv__DOT__cu__DOT__funct3;
        CData/*0:0*/ top__DOT__riscv__DOT__cu__DOT__funct7b5;
        CData/*1:0*/ top__DOT__riscv__DOT__cu__DOT__immsrcD;
        CData/*0:0*/ top__DOT__riscv__DOT__cu__DOT__flushE;
        CData/*0:0*/ top__DOT__riscv__DOT__cu__DOT__zeroE;
        CData/*0:0*/ top__DOT__riscv__DOT__cu__DOT__pcsrcE;
        CData/*0:0*/ top__DOT__riscv__DOT__cu__DOT__alusrcE;
        CData/*1:0*/ top__DOT__riscv__DOT__cu__DOT__resultsrcE;
        CData/*2:0*/ top__DOT__riscv__DOT__cu__DOT__alucontrolE;
        CData/*0:0*/ top__DOT__riscv__DOT__cu__DOT__regwriteM;
        CData/*0:0*/ top__DOT__riscv__DOT__cu__DOT__memwriteM;
        CData/*0:0*/ top__DOT__riscv__DOT__cu__DOT__regwriteW;
        CData/*1:0*/ top__DOT__riscv__DOT__cu__DOT__resultsrcW;
        CData/*1:0*/ top__DOT__riscv__DOT__cu__DOT__aluop;
        CData/*0:0*/ top__DOT__riscv__DOT__cu__DOT__regwriteD;
        CData/*1:0*/ top__DOT__riscv__DOT__cu__DOT__resultsrcD;
        CData/*0:0*/ top__DOT__riscv__DOT__cu__DOT__memwriteD;
        CData/*0:0*/ top__DOT__riscv__DOT__cu__DOT__jumpD;
        CData/*0:0*/ top__DOT__riscv__DOT__cu__DOT__branchD;
        CData/*2:0*/ top__DOT__riscv__DOT__cu__DOT__alucontrolD;
        CData/*0:0*/ top__DOT__riscv__DOT__cu__DOT__alusrcD;
        CData/*0:0*/ top__DOT__riscv__DOT__cu__DOT__regwriteE;
        CData/*0:0*/ top__DOT__riscv__DOT__cu__DOT__memwriteE;
        CData/*0:0*/ top__DOT__riscv__DOT__cu__DOT__jumpE;
        CData/*0:0*/ top__DOT__riscv__DOT__cu__DOT__branchE;
        CData/*1:0*/ top__DOT__riscv__DOT__cu__DOT__immsrcE;
        CData/*1:0*/ top__DOT__riscv__DOT__cu__DOT__resultsrcM;
        CData/*6:0*/ top__DOT__riscv__DOT__cu__DOT__md__DOT__op;
        CData/*1:0*/ top__DOT__riscv__DOT__cu__DOT__md__DOT__resultsrc;
        CData/*0:0*/ top__DOT__riscv__DOT__cu__DOT__md__DOT__regwrite;
        CData/*0:0*/ top__DOT__riscv__DOT__cu__DOT__md__DOT__memwrite;
        CData/*0:0*/ top__DOT__riscv__DOT__cu__DOT__md__DOT__jump;
        CData/*0:0*/ top__DOT__riscv__DOT__cu__DOT__md__DOT__branch;
        CData/*0:0*/ top__DOT__riscv__DOT__cu__DOT__md__DOT__alusrc;
        CData/*1:0*/ top__DOT__riscv__DOT__cu__DOT__md__DOT__immsrc;
        CData/*1:0*/ top__DOT__riscv__DOT__cu__DOT__md__DOT__aluop;
        CData/*0:0*/ top__DOT__riscv__DOT__cu__DOT__ad__DOT__opb5;
        CData/*2:0*/ top__DOT__riscv__DOT__cu__DOT__ad__DOT__funct3;
        CData/*0:0*/ top__DOT__riscv__DOT__cu__DOT__ad__DOT__funct7b5;
        CData/*1:0*/ top__DOT__riscv__DOT__cu__DOT__ad__DOT__aluop;
        CData/*2:0*/ top__DOT__riscv__DOT__cu__DOT__ad__DOT__alucontrol;
        CData/*0:0*/ top__DOT__riscv__DOT__cu__DOT__ad__DOT__rsub;
        CData/*0:0*/ top__DOT__riscv__DOT__cu__DOT__regE__DOT__clk;
        CData/*0:0*/ top__DOT__riscv__DOT__cu__DOT__regE__DOT__rst;
        CData/*0:0*/ top__DOT__riscv__DOT__cu__DOT__regE__DOT__clear;
        CData/*0:0*/ top__DOT__riscv__DOT__cu__DOT__regM__DOT__clk;
        CData/*0:0*/ top__DOT__riscv__DOT__cu__DOT__regM__DOT__rst;
        CData/*3:0*/ top__DOT__riscv__DOT__cu__DOT__regM__DOT__d;
        CData/*3:0*/ top__DOT__riscv__DOT__cu__DOT__regM__DOT__q;
        CData/*0:0*/ top__DOT__riscv__DOT__cu__DOT__regW__DOT__clk;
        CData/*0:0*/ top__DOT__riscv__DOT__cu__DOT__regW__DOT__rst;
    };
    struct {
        CData/*2:0*/ top__DOT__riscv__DOT__cu__DOT__regW__DOT__d;
        CData/*2:0*/ top__DOT__riscv__DOT__cu__DOT__regW__DOT__q;
        CData/*4:0*/ top__DOT__riscv__DOT__hu__DOT__rs1D;
        CData/*4:0*/ top__DOT__riscv__DOT__hu__DOT__rs2D;
        CData/*4:0*/ top__DOT__riscv__DOT__hu__DOT__rs1E;
        CData/*4:0*/ top__DOT__riscv__DOT__hu__DOT__rs2E;
        CData/*4:0*/ top__DOT__riscv__DOT__hu__DOT__rdE;
        CData/*1:0*/ top__DOT__riscv__DOT__hu__DOT__resultsrcE;
        CData/*0:0*/ top__DOT__riscv__DOT__hu__DOT__pcsrcE;
        CData/*4:0*/ top__DOT__riscv__DOT__hu__DOT__rdM;
        CData/*0:0*/ top__DOT__riscv__DOT__hu__DOT__regwriteM;
        CData/*4:0*/ top__DOT__riscv__DOT__hu__DOT__rdW;
        CData/*0:0*/ top__DOT__riscv__DOT__hu__DOT__regwriteW;
        CData/*0:0*/ top__DOT__riscv__DOT__hu__DOT__stallF;
        CData/*0:0*/ top__DOT__riscv__DOT__hu__DOT__stallD;
        CData/*0:0*/ top__DOT__riscv__DOT__hu__DOT__flushD;
        CData/*0:0*/ top__DOT__riscv__DOT__hu__DOT__flushE;
        CData/*1:0*/ top__DOT__riscv__DOT__hu__DOT__forwardAE;
        CData/*1:0*/ top__DOT__riscv__DOT__hu__DOT__forwardBE;
        CData/*0:0*/ top__DOT__riscv__DOT__hu__DOT__lwstall;
        CData/*5:0*/ top__DOT__imem__DOT__a;
        CData/*0:0*/ top__DOT__dmem__DOT__clk;
        CData/*0:0*/ top__DOT__dmem__DOT__we;
        CData/*5:0*/ top__DOT__dmem__DOT__index;
        CData/*0:0*/ __VstlFirstIteration;
        CData/*0:0*/ __VicoFirstIteration;
        CData/*0:0*/ __Vtrigprevexpr___TOP__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__rst__0;
        CData/*2:0*/ __Vtrigprevexpr___TOP__top__DOT__riscv__DOT__alucontrolE__0;
        CData/*0:0*/ __VactDidInit;
        CData/*0:0*/ __VactContinue;
        SData/*9:0*/ top__DOT__riscv__DOT__cu__DOT____Vcellinp__regE__d;
        SData/*10:0*/ top__DOT__riscv__DOT__cu__DOT__md__DOT__controlsig;
        SData/*9:0*/ top__DOT__riscv__DOT__cu__DOT__regE__DOT__d;
        SData/*9:0*/ top__DOT__riscv__DOT__cu__DOT__regE__DOT__q;
        VL_OUT(writedata,31,0);
        VL_OUT(dataadr,31,0);
        IData/*31:0*/ top__DOT__writedata;
        IData/*31:0*/ top__DOT__dataadr;
        IData/*31:0*/ top__DOT__pcF;
        IData/*31:0*/ top__DOT__instrF;
        IData/*31:0*/ top__DOT__readdataW;
        IData/*31:0*/ top__DOT__riscv__DOT__instrF;
        IData/*31:0*/ top__DOT__riscv__DOT__pcF;
        IData/*31:0*/ top__DOT__riscv__DOT__readdataM;
        IData/*31:0*/ top__DOT__riscv__DOT__aluresultM;
        IData/*31:0*/ top__DOT__riscv__DOT__writedataM;
        IData/*31:0*/ top__DOT__riscv__DOT__dp__DOT__instrF;
        IData/*31:0*/ top__DOT__riscv__DOT__dp__DOT__pcF;
        IData/*31:0*/ top__DOT__riscv__DOT__dp__DOT__readdataM;
        IData/*31:0*/ top__DOT__riscv__DOT__dp__DOT__aluresultM;
        IData/*31:0*/ top__DOT__riscv__DOT__dp__DOT__writedataM;
        IData/*31:0*/ top__DOT__riscv__DOT__dp__DOT__pcnextF;
        IData/*31:0*/ top__DOT__riscv__DOT__dp__DOT__pcplus4F;
        IData/*31:0*/ top__DOT__riscv__DOT__dp__DOT__instrD;
        IData/*31:0*/ top__DOT__riscv__DOT__dp__DOT__rd1D;
        IData/*31:0*/ top__DOT__riscv__DOT__dp__DOT__rd2D;
        IData/*31:0*/ top__DOT__riscv__DOT__dp__DOT__pcD;
        IData/*31:0*/ top__DOT__riscv__DOT__dp__DOT__immextD;
        IData/*31:0*/ top__DOT__riscv__DOT__dp__DOT__pcplus4D;
        IData/*31:0*/ top__DOT__riscv__DOT__dp__DOT__rd1E;
        IData/*31:0*/ top__DOT__riscv__DOT__dp__DOT__rd2E;
        IData/*31:0*/ top__DOT__riscv__DOT__dp__DOT__pcE;
        IData/*31:0*/ top__DOT__riscv__DOT__dp__DOT__immextE;
    };
    struct {
        IData/*31:0*/ top__DOT__riscv__DOT__dp__DOT__pcplus4E;
        IData/*31:0*/ top__DOT__riscv__DOT__dp__DOT__srcaE;
        IData/*31:0*/ top__DOT__riscv__DOT__dp__DOT__srcbE;
        IData/*31:0*/ top__DOT__riscv__DOT__dp__DOT__fmuxbout;
        IData/*31:0*/ top__DOT__riscv__DOT__dp__DOT__writedataE;
        IData/*31:0*/ top__DOT__riscv__DOT__dp__DOT__pctargetE;
        IData/*31:0*/ top__DOT__riscv__DOT__dp__DOT__aluresultE;
        IData/*31:0*/ top__DOT__riscv__DOT__dp__DOT__pcplus4M;
        IData/*31:0*/ top__DOT__riscv__DOT__dp__DOT__aluresultW;
        IData/*31:0*/ top__DOT__riscv__DOT__dp__DOT__readdataW;
        IData/*31:0*/ top__DOT__riscv__DOT__dp__DOT__pcplus4W;
        IData/*31:0*/ top__DOT__riscv__DOT__dp__DOT__resultW;
        IData/*31:0*/ top__DOT__riscv__DOT__dp__DOT__pcmux__DOT__a;
        IData/*31:0*/ top__DOT__riscv__DOT__dp__DOT__pcmux__DOT__b;
        IData/*31:0*/ top__DOT__riscv__DOT__dp__DOT__pcmux__DOT__y;
        IData/*31:0*/ top__DOT__riscv__DOT__dp__DOT__pc__DOT__d;
        IData/*31:0*/ top__DOT__riscv__DOT__dp__DOT__pc__DOT__q;
        IData/*31:0*/ top__DOT__riscv__DOT__dp__DOT__adderF__DOT__a;
        IData/*31:0*/ top__DOT__riscv__DOT__dp__DOT__adderF__DOT__b;
        IData/*31:0*/ top__DOT__riscv__DOT__dp__DOT__adderF__DOT__y;
        IData/*31:0*/ top__DOT__riscv__DOT__dp__DOT__regD1__DOT__d;
        IData/*31:0*/ top__DOT__riscv__DOT__dp__DOT__regD1__DOT__q;
        IData/*31:0*/ top__DOT__riscv__DOT__dp__DOT__regD2__DOT__d;
        IData/*31:0*/ top__DOT__riscv__DOT__dp__DOT__regD2__DOT__q;
        IData/*31:0*/ top__DOT__riscv__DOT__dp__DOT__regD3__DOT__d;
        IData/*31:0*/ top__DOT__riscv__DOT__dp__DOT__regD3__DOT__q;
        IData/*31:0*/ top__DOT__riscv__DOT__dp__DOT__rf__DOT__wd3;
        IData/*31:0*/ top__DOT__riscv__DOT__dp__DOT__rf__DOT__rd1;
        IData/*31:0*/ top__DOT__riscv__DOT__dp__DOT__rf__DOT__rd2;
        IData/*24:0*/ top__DOT__riscv__DOT__dp__DOT__ext__DOT__instr;
        IData/*31:0*/ top__DOT__riscv__DOT__dp__DOT__ext__DOT__immext;
        IData/*31:0*/ top__DOT__riscv__DOT__dp__DOT__regE1__DOT__d;
        IData/*31:0*/ top__DOT__riscv__DOT__dp__DOT__regE1__DOT__q;
        IData/*31:0*/ top__DOT__riscv__DOT__dp__DOT__regE2__DOT__d;
        IData/*31:0*/ top__DOT__riscv__DOT__dp__DOT__regE2__DOT__q;
        IData/*31:0*/ top__DOT__riscv__DOT__dp__DOT__regE3__DOT__d;
        IData/*31:0*/ top__DOT__riscv__DOT__dp__DOT__regE3__DOT__q;
        IData/*31:0*/ top__DOT__riscv__DOT__dp__DOT__regE7__DOT__d;
        IData/*31:0*/ top__DOT__riscv__DOT__dp__DOT__regE7__DOT__q;
        IData/*31:0*/ top__DOT__riscv__DOT__dp__DOT__regE8__DOT__d;
        IData/*31:0*/ top__DOT__riscv__DOT__dp__DOT__regE8__DOT__q;
        IData/*31:0*/ top__DOT__riscv__DOT__dp__DOT__fmuxa__DOT__a;
        IData/*31:0*/ top__DOT__riscv__DOT__dp__DOT__fmuxa__DOT__b;
        IData/*31:0*/ top__DOT__riscv__DOT__dp__DOT__fmuxa__DOT__c;
        IData/*31:0*/ top__DOT__riscv__DOT__dp__DOT__fmuxa__DOT__y;
        IData/*31:0*/ top__DOT__riscv__DOT__dp__DOT__fmuxb__DOT__a;
        IData/*31:0*/ top__DOT__riscv__DOT__dp__DOT__fmuxb__DOT__b;
        IData/*31:0*/ top__DOT__riscv__DOT__dp__DOT__fmuxb__DOT__c;
        IData/*31:0*/ top__DOT__riscv__DOT__dp__DOT__fmuxb__DOT__y;
        IData/*31:0*/ top__DOT__riscv__DOT__dp__DOT__alumux__DOT__a;
        IData/*31:0*/ top__DOT__riscv__DOT__dp__DOT__alumux__DOT__b;
        IData/*31:0*/ top__DOT__riscv__DOT__dp__DOT__alumux__DOT__y;
        IData/*31:0*/ top__DOT__riscv__DOT__dp__DOT__adderE__DOT__a;
        IData/*31:0*/ top__DOT__riscv__DOT__dp__DOT__adderE__DOT__b;
        IData/*31:0*/ top__DOT__riscv__DOT__dp__DOT__adderE__DOT__y;
        IData/*31:0*/ top__DOT__riscv__DOT__dp__DOT__alu__DOT__a;
        IData/*31:0*/ top__DOT__riscv__DOT__dp__DOT__alu__DOT__b;
        IData/*31:0*/ top__DOT__riscv__DOT__dp__DOT__alu__DOT__y;
        IData/*31:0*/ top__DOT__riscv__DOT__dp__DOT__regM1__DOT__d;
        IData/*31:0*/ top__DOT__riscv__DOT__dp__DOT__regM1__DOT__q;
        IData/*31:0*/ top__DOT__riscv__DOT__dp__DOT__regM2__DOT__d;
        IData/*31:0*/ top__DOT__riscv__DOT__dp__DOT__regM2__DOT__q;
        IData/*31:0*/ top__DOT__riscv__DOT__dp__DOT__regM4__DOT__d;
        IData/*31:0*/ top__DOT__riscv__DOT__dp__DOT__regM4__DOT__q;
    };
    struct {
        IData/*31:0*/ top__DOT__riscv__DOT__dp__DOT__regW1__DOT__d;
        IData/*31:0*/ top__DOT__riscv__DOT__dp__DOT__regW1__DOT__q;
        IData/*31:0*/ top__DOT__riscv__DOT__dp__DOT__regW2__DOT__d;
        IData/*31:0*/ top__DOT__riscv__DOT__dp__DOT__regW2__DOT__q;
        IData/*31:0*/ top__DOT__riscv__DOT__dp__DOT__regW4__DOT__d;
        IData/*31:0*/ top__DOT__riscv__DOT__dp__DOT__regW4__DOT__q;
        IData/*31:0*/ top__DOT__riscv__DOT__dp__DOT__resultmux__DOT__a;
        IData/*31:0*/ top__DOT__riscv__DOT__dp__DOT__resultmux__DOT__b;
        IData/*31:0*/ top__DOT__riscv__DOT__dp__DOT__resultmux__DOT__c;
        IData/*31:0*/ top__DOT__riscv__DOT__dp__DOT__resultmux__DOT__y;
        IData/*31:0*/ top__DOT__imem__DOT__rd;
        IData/*31:0*/ top__DOT__dmem__DOT__a;
        IData/*31:0*/ top__DOT__dmem__DOT__wd;
        IData/*31:0*/ top__DOT__dmem__DOT__rd;
        IData/*31:0*/ __Vtrigprevexpr___TOP__top__DOT__riscv__DOT__dp__DOT__srcaE__0;
        IData/*31:0*/ __Vtrigprevexpr___TOP__top__DOT__riscv__DOT__dp__DOT__srcbE__0;
        IData/*31:0*/ __Vtrigprevexpr___TOP__top__DOT__riscv__DOT__dp__DOT__alu__DOT__y__0;
        IData/*31:0*/ __VactIterCount;
        VlUnpacked<IData/*31:0*/, 32> top__DOT__riscv__DOT__dp__DOT__rf__DOT__rf;
        VlUnpacked<IData/*31:0*/, 64> top__DOT__imem__DOT__RAM;
        VlUnpacked<IData/*31:0*/, 64> top__DOT__dmem__DOT__RAM;
    };
    VlTriggerVec<1> __VstlTriggered;
    VlTriggerVec<1> __VicoTriggered;
    VlTriggerVec<7> __VactTriggered;
    VlTriggerVec<7> __VnbaTriggered;

    // INTERNAL VARIABLES
    Vtop__Syms* const vlSymsp;

    // PARAMETERS
    static constexpr IData/*31:0*/ top__DOT__WIDTH = 0x00000020U;
    static constexpr IData/*31:0*/ top__DOT__riscv__DOT__WIDTH = 0x00000020U;
    static constexpr IData/*31:0*/ top__DOT__riscv__DOT__dp__DOT__WIDTH = 0x00000020U;
    static constexpr IData/*31:0*/ top__DOT__riscv__DOT__dp__DOT__pcmux__DOT__WIDTH = 0x00000020U;
    static constexpr IData/*31:0*/ top__DOT__riscv__DOT__dp__DOT__pc__DOT__WIDTH = 0x00000020U;
    static constexpr IData/*31:0*/ top__DOT__riscv__DOT__dp__DOT__adderF__DOT__WIDTH = 0x00000020U;
    static constexpr IData/*31:0*/ top__DOT__riscv__DOT__dp__DOT__regD1__DOT__WIDTH = 0x00000020U;
    static constexpr IData/*31:0*/ top__DOT__riscv__DOT__dp__DOT__regD2__DOT__WIDTH = 0x00000020U;
    static constexpr IData/*31:0*/ top__DOT__riscv__DOT__dp__DOT__regD3__DOT__WIDTH = 0x00000020U;
    static constexpr IData/*31:0*/ top__DOT__riscv__DOT__dp__DOT__rf__DOT__WIDTH = 0x00000020U;
    static constexpr IData/*31:0*/ top__DOT__riscv__DOT__dp__DOT__ext__DOT__OUTWIDTH = 0x00000020U;
    static constexpr IData/*31:0*/ top__DOT__riscv__DOT__dp__DOT__regE1__DOT__WIDTH = 0x00000020U;
    static constexpr IData/*31:0*/ top__DOT__riscv__DOT__dp__DOT__regE2__DOT__WIDTH = 0x00000020U;
    static constexpr IData/*31:0*/ top__DOT__riscv__DOT__dp__DOT__regE3__DOT__WIDTH = 0x00000020U;
    static constexpr IData/*31:0*/ top__DOT__riscv__DOT__dp__DOT__regE4__DOT__WIDTH = 5U;
    static constexpr IData/*31:0*/ top__DOT__riscv__DOT__dp__DOT__regE5__DOT__WIDTH = 5U;
    static constexpr IData/*31:0*/ top__DOT__riscv__DOT__dp__DOT__regE6__DOT__WIDTH = 5U;
    static constexpr IData/*31:0*/ top__DOT__riscv__DOT__dp__DOT__regE7__DOT__WIDTH = 0x00000020U;
    static constexpr IData/*31:0*/ top__DOT__riscv__DOT__dp__DOT__regE8__DOT__WIDTH = 0x00000020U;
    static constexpr IData/*31:0*/ top__DOT__riscv__DOT__dp__DOT__fmuxa__DOT__WIDTH = 0x00000020U;
    static constexpr IData/*31:0*/ top__DOT__riscv__DOT__dp__DOT__fmuxb__DOT__WIDTH = 0x00000020U;
    static constexpr IData/*31:0*/ top__DOT__riscv__DOT__dp__DOT__alumux__DOT__WIDTH = 0x00000020U;
    static constexpr IData/*31:0*/ top__DOT__riscv__DOT__dp__DOT__adderE__DOT__WIDTH = 0x00000020U;
    static constexpr IData/*31:0*/ top__DOT__riscv__DOT__dp__DOT__alu__DOT__WIDTH = 0x00000020U;
    static constexpr IData/*31:0*/ top__DOT__riscv__DOT__dp__DOT__regM1__DOT__WIDTH = 0x00000020U;
    static constexpr IData/*31:0*/ top__DOT__riscv__DOT__dp__DOT__regM2__DOT__WIDTH = 0x00000020U;
    static constexpr IData/*31:0*/ top__DOT__riscv__DOT__dp__DOT__regM3__DOT__WIDTH = 5U;
    static constexpr IData/*31:0*/ top__DOT__riscv__DOT__dp__DOT__regM4__DOT__WIDTH = 0x00000020U;
    static constexpr IData/*31:0*/ top__DOT__riscv__DOT__dp__DOT__regW1__DOT__WIDTH = 0x00000020U;
    static constexpr IData/*31:0*/ top__DOT__riscv__DOT__dp__DOT__regW2__DOT__WIDTH = 0x00000020U;
    static constexpr IData/*31:0*/ top__DOT__riscv__DOT__dp__DOT__regW3__DOT__WIDTH = 5U;
    static constexpr IData/*31:0*/ top__DOT__riscv__DOT__dp__DOT__regW4__DOT__WIDTH = 0x00000020U;
    static constexpr IData/*31:0*/ top__DOT__riscv__DOT__dp__DOT__resultmux__DOT__WIDTH = 0x00000020U;
    static constexpr IData/*31:0*/ top__DOT__riscv__DOT__cu__DOT__regE__DOT__WIDTH = 0x0000000aU;
    static constexpr IData/*31:0*/ top__DOT__riscv__DOT__cu__DOT__regM__DOT__WIDTH = 4U;
    static constexpr IData/*31:0*/ top__DOT__riscv__DOT__cu__DOT__regW__DOT__WIDTH = 3U;
    static constexpr IData/*31:0*/ top__DOT__imem__DOT__WIDTH = 0x00000020U;
    static constexpr IData/*31:0*/ top__DOT__dmem__DOT__WIDTH = 0x00000020U;

    // CONSTRUCTORS
    Vtop___024root(Vtop__Syms* symsp, const char* v__name);
    ~Vtop___024root();
    VL_UNCOPYABLE(Vtop___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
