// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Tracing implementation internals
#include "verilated_vcd_c.h"
#include "Vtop__Syms.h"


VL_ATTR_COLD void Vtop___024root__trace_init_sub__TOP__0(Vtop___024root* vlSelf, VerilatedVcd* tracep) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_init_sub__TOP__0\n"); );
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Init
    const int c = vlSymsp->__Vm_baseCode;
    // Body
    tracep->declBit(c+1,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+2,0,"rst",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+3,0,"writedata",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+4,0,"dataadr",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+5,0,"memwrite",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->pushPrefix("top", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+359,0,"WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+6,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+7,0,"rst",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+8,0,"writedata",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+9,0,"dataadr",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+10,0,"memwrite",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+11,0,"pcF",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+12,0,"instrF",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+13,0,"readdataW",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->pushPrefix("dmem", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+359,0,"WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+14,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+15,0,"we",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+16,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+17,0,"wd",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+18,0,"rd",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+19,0,"index",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 5,0);
    tracep->popPrefix();
    tracep->pushPrefix("imem", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+359,0,"WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+20,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 5,0);
    tracep->declBus(c+21,0,"rd",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->popPrefix();
    tracep->pushPrefix("riscv", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+359,0,"WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+22,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+23,0,"rst",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+24,0,"instrF",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+25,0,"pcF",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+26,0,"readdataM",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+27,0,"memwriteM",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+28,0,"aluresultM",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+29,0,"writedataM",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+30,0,"op",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 6,0);
    tracep->declBus(c+31,0,"funct3",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBit(c+32,0,"funct7b5",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+33,0,"stallF",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+34,0,"stallD",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+35,0,"flushD",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+36,0,"immsrcD",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+37,0,"rs1D",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+38,0,"rs2D",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBit(c+39,0,"zeroE",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+40,0,"pcsrcE",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+41,0,"alusrcE",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+42,0,"flushE",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+43,0,"resultsrcE",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+44,0,"forwardAE",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+45,0,"forwardBE",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+46,0,"alucontrolE",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+47,0,"rs1E",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+48,0,"rs2E",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+49,0,"rdE",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBit(c+50,0,"regwriteM",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+51,0,"rdM",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBit(c+52,0,"regwriteW",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+53,0,"resultsrcW",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+54,0,"rdW",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->pushPrefix("cu", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+55,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+56,0,"rst",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+57,0,"op",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 6,0);
    tracep->declBus(c+58,0,"funct3",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBit(c+59,0,"funct7b5",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+60,0,"immsrcD",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBit(c+61,0,"flushE",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+62,0,"zeroE",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+63,0,"pcsrcE",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+64,0,"alusrcE",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+65,0,"resultsrcE",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+66,0,"alucontrolE",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBit(c+67,0,"regwriteM",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+68,0,"memwriteM",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+69,0,"regwriteW",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+70,0,"resultsrcW",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+71,0,"aluop",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBit(c+72,0,"regwriteD",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+73,0,"resultsrcD",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBit(c+74,0,"memwriteD",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+75,0,"jumpD",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+76,0,"branchD",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+77,0,"alucontrolD",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBit(c+78,0,"alusrcD",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+79,0,"regwriteE",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+80,0,"memwriteE",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+81,0,"jumpE",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+82,0,"branchE",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+83,0,"immsrcE",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+84,0,"resultsrcM",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->pushPrefix("ad", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+85,0,"opb5",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+86,0,"funct3",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBit(c+87,0,"funct7b5",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+88,0,"aluop",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+89,0,"alucontrol",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBit(c+90,0,"rsub",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->pushPrefix("md", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+91,0,"op",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 6,0);
    tracep->declBus(c+92,0,"resultsrc",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBit(c+93,0,"regwrite",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+94,0,"memwrite",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+95,0,"jump",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+96,0,"branch",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+97,0,"alusrc",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+98,0,"immsrc",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+99,0,"aluop",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+100,0,"controlsig",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 10,0);
    tracep->popPrefix();
    tracep->pushPrefix("regE", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+360,0,"WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+101,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+102,0,"rst",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+103,0,"clear",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+104,0,"d",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 9,0);
    tracep->declBus(c+105,0,"q",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 9,0);
    tracep->popPrefix();
    tracep->pushPrefix("regM", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+361,0,"WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+106,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+107,0,"rst",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+108,0,"d",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+109,0,"q",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->popPrefix();
    tracep->pushPrefix("regW", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+362,0,"WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+110,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+111,0,"rst",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+112,0,"d",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+113,0,"q",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->popPrefix();
    tracep->popPrefix();
    tracep->pushPrefix("dp", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+359,0,"WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+114,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+115,0,"rst",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+116,0,"pcsrcE",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+117,0,"stallF",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+118,0,"instrF",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+119,0,"pcF",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+120,0,"immsrcD",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBit(c+121,0,"stallD",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+122,0,"flushD",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+123,0,"regwriteW",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+124,0,"op",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 6,0);
    tracep->declBus(c+125,0,"funct3",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBit(c+126,0,"funct7b5",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+127,0,"rs1D",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+128,0,"rs2D",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBit(c+129,0,"flushE",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+130,0,"forwardAE",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+131,0,"forwardBE",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+132,0,"alucontrolE",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBit(c+133,0,"alusrcE",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+134,0,"rs1E",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+135,0,"rs2E",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+136,0,"rdE",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBit(c+137,0,"zeroE",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+138,0,"readdataM",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+139,0,"aluresultM",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+140,0,"writedataM",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+141,0,"rdM",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+142,0,"resultsrcW",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+143,0,"rdW",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+144,0,"pcnextF",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+145,0,"pcplus4F",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+146,0,"instrD",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+147,0,"rd1D",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+148,0,"rd2D",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+149,0,"rdD",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+150,0,"pcD",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+151,0,"immextD",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+152,0,"pcplus4D",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+153,0,"rd1E",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+154,0,"rd2E",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+155,0,"pcE",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+156,0,"immextE",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+157,0,"pcplus4E",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+158,0,"srcaE",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+159,0,"srcbE",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+160,0,"fmuxbout",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+161,0,"writedataE",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+162,0,"pctargetE",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+163,0,"aluresultE",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+164,0,"pcplus4M",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+165,0,"aluresultW",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+166,0,"readdataW",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+167,0,"pcplus4W",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+168,0,"resultW",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->pushPrefix("adderE", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+359,0,"WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+169,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+170,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+171,0,"y",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->popPrefix();
    tracep->pushPrefix("adderF", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+359,0,"WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+172,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+173,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+174,0,"y",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->popPrefix();
    tracep->pushPrefix("alu", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+359,0,"WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+175,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+176,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+177,0,"f",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+178,0,"y",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+179,0,"zero",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->pushPrefix("alumux", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+359,0,"WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+180,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+181,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+182,0,"sel",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+183,0,"y",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->popPrefix();
    tracep->pushPrefix("ext", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+359,0,"OUTWIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+184,0,"instr",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,7);
    tracep->declBus(c+185,0,"immsrc",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+186,0,"immext",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->popPrefix();
    tracep->pushPrefix("fmuxa", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+359,0,"WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+187,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+188,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+189,0,"c",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+190,0,"sel",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+191,0,"y",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->popPrefix();
    tracep->pushPrefix("fmuxb", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+359,0,"WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+192,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+193,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+194,0,"c",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+195,0,"sel",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+196,0,"y",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->popPrefix();
    tracep->pushPrefix("pc", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+359,0,"WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+197,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+198,0,"rst",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+199,0,"en",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+200,0,"d",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+201,0,"q",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->popPrefix();
    tracep->pushPrefix("pcmux", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+359,0,"WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+202,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+203,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+204,0,"sel",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+205,0,"y",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->popPrefix();
    tracep->pushPrefix("regD1", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+359,0,"WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+206,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+207,0,"rst",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+208,0,"en",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+209,0,"clear",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+210,0,"d",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+211,0,"q",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->popPrefix();
    tracep->pushPrefix("regD2", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+359,0,"WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+212,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+213,0,"rst",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+214,0,"en",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+215,0,"clear",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+216,0,"d",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+217,0,"q",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->popPrefix();
    tracep->pushPrefix("regD3", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+359,0,"WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+218,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+219,0,"rst",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+220,0,"en",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+221,0,"clear",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+222,0,"d",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+223,0,"q",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->popPrefix();
    tracep->pushPrefix("regE1", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+359,0,"WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+224,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+225,0,"rst",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+226,0,"clear",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+227,0,"d",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+228,0,"q",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->popPrefix();
    tracep->pushPrefix("regE2", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+359,0,"WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+229,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+230,0,"rst",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+231,0,"clear",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+232,0,"d",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+233,0,"q",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->popPrefix();
    tracep->pushPrefix("regE3", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+359,0,"WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+234,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+235,0,"rst",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+236,0,"clear",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+237,0,"d",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+238,0,"q",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->popPrefix();
    tracep->pushPrefix("regE4", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+363,0,"WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+239,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+240,0,"rst",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+241,0,"clear",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+242,0,"d",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+243,0,"q",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->popPrefix();
    tracep->pushPrefix("regE5", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+363,0,"WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+244,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+245,0,"rst",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+246,0,"clear",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+247,0,"d",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+248,0,"q",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->popPrefix();
    tracep->pushPrefix("regE6", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+363,0,"WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+249,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+250,0,"rst",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+251,0,"clear",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+252,0,"d",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+253,0,"q",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->popPrefix();
    tracep->pushPrefix("regE7", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+359,0,"WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+254,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+255,0,"rst",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+256,0,"clear",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+257,0,"d",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+258,0,"q",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->popPrefix();
    tracep->pushPrefix("regE8", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+359,0,"WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+259,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+260,0,"rst",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+261,0,"clear",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+262,0,"d",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+263,0,"q",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->popPrefix();
    tracep->pushPrefix("regM1", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+359,0,"WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+264,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+265,0,"rst",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+266,0,"d",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+267,0,"q",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->popPrefix();
    tracep->pushPrefix("regM2", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+359,0,"WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+268,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+269,0,"rst",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+270,0,"d",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+271,0,"q",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->popPrefix();
    tracep->pushPrefix("regM3", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+363,0,"WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+272,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+273,0,"rst",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+274,0,"d",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+275,0,"q",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->popPrefix();
    tracep->pushPrefix("regM4", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+359,0,"WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+276,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+277,0,"rst",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+278,0,"d",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+279,0,"q",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->popPrefix();
    tracep->pushPrefix("regW1", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+359,0,"WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+280,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+281,0,"rst",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+282,0,"d",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+283,0,"q",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->popPrefix();
    tracep->pushPrefix("regW2", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+359,0,"WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+284,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+285,0,"rst",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+286,0,"d",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+287,0,"q",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->popPrefix();
    tracep->pushPrefix("regW3", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+363,0,"WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+288,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+289,0,"rst",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+290,0,"d",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+291,0,"q",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->popPrefix();
    tracep->pushPrefix("regW4", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+359,0,"WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+292,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+293,0,"rst",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+294,0,"d",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+295,0,"q",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->popPrefix();
    tracep->pushPrefix("resultmux", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+359,0,"WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+296,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+297,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+298,0,"c",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+299,0,"sel",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+300,0,"y",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->popPrefix();
    tracep->pushPrefix("rf", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+359,0,"WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+301,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+302,0,"we3",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+303,0,"ra1",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+304,0,"ra2",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+305,0,"wa3",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+306,0,"wd3",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+307,0,"rd1",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+308,0,"rd2",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->pushPrefix("rf", VerilatedTracePrefixType::ARRAY_UNPACKED);
    for (int i = 0; i < 32; ++i) {
        tracep->declBus(c+309+i*1,0,"",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, true,(i+0), 31,0);
    }
    tracep->popPrefix();
    tracep->popPrefix();
    tracep->popPrefix();
    tracep->pushPrefix("hu", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+341,0,"rs1D",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+342,0,"rs2D",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+343,0,"rs1E",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+344,0,"rs2E",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+345,0,"rdE",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+346,0,"resultsrcE",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBit(c+347,0,"pcsrcE",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+348,0,"rdM",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBit(c+349,0,"regwriteM",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+350,0,"rdW",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBit(c+351,0,"regwriteW",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+352,0,"stallF",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+353,0,"stallD",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+354,0,"flushD",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+355,0,"flushE",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+356,0,"forwardAE",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+357,0,"forwardBE",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBit(c+358,0,"lwstall",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->popPrefix();
    tracep->popPrefix();
}

VL_ATTR_COLD void Vtop___024root__trace_init_top(Vtop___024root* vlSelf, VerilatedVcd* tracep) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_init_top\n"); );
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Body
    Vtop___024root__trace_init_sub__TOP__0(vlSelf, tracep);
}

VL_ATTR_COLD void Vtop___024root__trace_const_0(void* voidSelf, VerilatedVcd::Buffer* bufp);
VL_ATTR_COLD void Vtop___024root__trace_full_0(void* voidSelf, VerilatedVcd::Buffer* bufp);
void Vtop___024root__trace_chg_0(void* voidSelf, VerilatedVcd::Buffer* bufp);
void Vtop___024root__trace_cleanup(void* voidSelf, VerilatedVcd* /*unused*/);

VL_ATTR_COLD void Vtop___024root__trace_register(Vtop___024root* vlSelf, VerilatedVcd* tracep) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_register\n"); );
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Body
    tracep->addConstCb(&Vtop___024root__trace_const_0, 0U, vlSelf);
    tracep->addFullCb(&Vtop___024root__trace_full_0, 0U, vlSelf);
    tracep->addChgCb(&Vtop___024root__trace_chg_0, 0U, vlSelf);
    tracep->addCleanupCb(&Vtop___024root__trace_cleanup, vlSelf);
}

VL_ATTR_COLD void Vtop___024root__trace_const_0_sub_0(Vtop___024root* vlSelf, VerilatedVcd::Buffer* bufp);

VL_ATTR_COLD void Vtop___024root__trace_const_0(void* voidSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_const_0\n"); );
    // Init
    Vtop___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vtop___024root*>(voidSelf);
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    // Body
    Vtop___024root__trace_const_0_sub_0((&vlSymsp->TOP), bufp);
}

VL_ATTR_COLD void Vtop___024root__trace_const_0_sub_0(Vtop___024root* vlSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_const_0_sub_0\n"); );
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Init
    uint32_t* const oldp VL_ATTR_UNUSED = bufp->oldp(vlSymsp->__Vm_baseCode);
    // Body
    bufp->fullIData(oldp+359,(0x20U),32);
    bufp->fullIData(oldp+360,(0xaU),32);
    bufp->fullIData(oldp+361,(4U),32);
    bufp->fullIData(oldp+362,(3U),32);
    bufp->fullIData(oldp+363,(5U),32);
}

VL_ATTR_COLD void Vtop___024root__trace_full_0_sub_0(Vtop___024root* vlSelf, VerilatedVcd::Buffer* bufp);

VL_ATTR_COLD void Vtop___024root__trace_full_0(void* voidSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_full_0\n"); );
    // Init
    Vtop___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vtop___024root*>(voidSelf);
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    // Body
    Vtop___024root__trace_full_0_sub_0((&vlSymsp->TOP), bufp);
}

VL_ATTR_COLD void Vtop___024root__trace_full_0_sub_0(Vtop___024root* vlSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_full_0_sub_0\n"); );
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Init
    uint32_t* const oldp VL_ATTR_UNUSED = bufp->oldp(vlSymsp->__Vm_baseCode);
    // Body
    bufp->fullBit(oldp+1,(vlSelfRef.clk));
    bufp->fullBit(oldp+2,(vlSelfRef.rst));
    bufp->fullIData(oldp+3,(vlSelfRef.writedata),32);
    bufp->fullIData(oldp+4,(vlSelfRef.dataadr),32);
    bufp->fullBit(oldp+5,(vlSelfRef.memwrite));
    bufp->fullBit(oldp+6,(vlSelfRef.top__DOT__clk));
    bufp->fullBit(oldp+7,(vlSelfRef.top__DOT__rst));
    bufp->fullIData(oldp+8,(vlSelfRef.top__DOT__writedata),32);
    bufp->fullIData(oldp+9,(vlSelfRef.top__DOT__dataadr),32);
    bufp->fullBit(oldp+10,(vlSelfRef.top__DOT__memwrite));
    bufp->fullIData(oldp+11,(vlSelfRef.top__DOT__pcF),32);
    bufp->fullIData(oldp+12,(vlSelfRef.top__DOT__instrF),32);
    bufp->fullIData(oldp+13,(vlSelfRef.top__DOT__readdataW),32);
    bufp->fullBit(oldp+14,(vlSelfRef.top__DOT__dmem__DOT__clk));
    bufp->fullBit(oldp+15,(vlSelfRef.top__DOT__dmem__DOT__we));
    bufp->fullIData(oldp+16,(vlSelfRef.top__DOT__dmem__DOT__a),32);
    bufp->fullIData(oldp+17,(vlSelfRef.top__DOT__dmem__DOT__wd),32);
    bufp->fullIData(oldp+18,(vlSelfRef.top__DOT__dmem__DOT__rd),32);
    bufp->fullCData(oldp+19,(vlSelfRef.top__DOT__dmem__DOT__index),6);
    bufp->fullCData(oldp+20,(vlSelfRef.top__DOT__imem__DOT__a),6);
    bufp->fullIData(oldp+21,(vlSelfRef.top__DOT__imem__DOT__rd),32);
    bufp->fullBit(oldp+22,(vlSelfRef.top__DOT__riscv__DOT__clk));
    bufp->fullBit(oldp+23,(vlSelfRef.top__DOT__riscv__DOT__rst));
    bufp->fullIData(oldp+24,(vlSelfRef.top__DOT__riscv__DOT__instrF),32);
    bufp->fullIData(oldp+25,(vlSelfRef.top__DOT__riscv__DOT__pcF),32);
    bufp->fullIData(oldp+26,(vlSelfRef.top__DOT__riscv__DOT__readdataM),32);
    bufp->fullBit(oldp+27,(vlSelfRef.top__DOT__riscv__DOT__memwriteM));
    bufp->fullIData(oldp+28,(vlSelfRef.top__DOT__riscv__DOT__aluresultM),32);
    bufp->fullIData(oldp+29,(vlSelfRef.top__DOT__riscv__DOT__writedataM),32);
    bufp->fullCData(oldp+30,(vlSelfRef.top__DOT__riscv__DOT__op),7);
    bufp->fullCData(oldp+31,(vlSelfRef.top__DOT__riscv__DOT__funct3),3);
    bufp->fullBit(oldp+32,(vlSelfRef.top__DOT__riscv__DOT__funct7b5));
    bufp->fullBit(oldp+33,(vlSelfRef.top__DOT__riscv__DOT__stallF));
    bufp->fullBit(oldp+34,(vlSelfRef.top__DOT__riscv__DOT__stallD));
    bufp->fullBit(oldp+35,(vlSelfRef.top__DOT__riscv__DOT__flushD));
    bufp->fullCData(oldp+36,(vlSelfRef.top__DOT__riscv__DOT__immsrcD),2);
    bufp->fullCData(oldp+37,(vlSelfRef.top__DOT__riscv__DOT__rs1D),5);
    bufp->fullCData(oldp+38,(vlSelfRef.top__DOT__riscv__DOT__rs2D),5);
    bufp->fullBit(oldp+39,(vlSelfRef.top__DOT__riscv__DOT__zeroE));
    bufp->fullBit(oldp+40,(vlSelfRef.top__DOT__riscv__DOT__pcsrcE));
    bufp->fullBit(oldp+41,(vlSelfRef.top__DOT__riscv__DOT__alusrcE));
    bufp->fullBit(oldp+42,(vlSelfRef.top__DOT__riscv__DOT__flushE));
    bufp->fullCData(oldp+43,(vlSelfRef.top__DOT__riscv__DOT__resultsrcE),2);
    bufp->fullCData(oldp+44,(vlSelfRef.top__DOT__riscv__DOT__forwardAE),2);
    bufp->fullCData(oldp+45,(vlSelfRef.top__DOT__riscv__DOT__forwardBE),2);
    bufp->fullCData(oldp+46,(vlSelfRef.top__DOT__riscv__DOT__alucontrolE),3);
    bufp->fullCData(oldp+47,(vlSelfRef.top__DOT__riscv__DOT__rs1E),5);
    bufp->fullCData(oldp+48,(vlSelfRef.top__DOT__riscv__DOT__rs2E),5);
    bufp->fullCData(oldp+49,(vlSelfRef.top__DOT__riscv__DOT__rdE),5);
    bufp->fullBit(oldp+50,(vlSelfRef.top__DOT__riscv__DOT__regwriteM));
    bufp->fullCData(oldp+51,(vlSelfRef.top__DOT__riscv__DOT__rdM),5);
    bufp->fullBit(oldp+52,(vlSelfRef.top__DOT__riscv__DOT__regwriteW));
    bufp->fullCData(oldp+53,(vlSelfRef.top__DOT__riscv__DOT__resultsrcW),2);
    bufp->fullCData(oldp+54,(vlSelfRef.top__DOT__riscv__DOT__rdW),5);
    bufp->fullBit(oldp+55,(vlSelfRef.top__DOT__riscv__DOT__cu__DOT__clk));
    bufp->fullBit(oldp+56,(vlSelfRef.top__DOT__riscv__DOT__cu__DOT__rst));
    bufp->fullCData(oldp+57,(vlSelfRef.top__DOT__riscv__DOT__cu__DOT__op),7);
    bufp->fullCData(oldp+58,(vlSelfRef.top__DOT__riscv__DOT__cu__DOT__funct3),3);
    bufp->fullBit(oldp+59,(vlSelfRef.top__DOT__riscv__DOT__cu__DOT__funct7b5));
    bufp->fullCData(oldp+60,(vlSelfRef.top__DOT__riscv__DOT__cu__DOT__immsrcD),2);
    bufp->fullBit(oldp+61,(vlSelfRef.top__DOT__riscv__DOT__cu__DOT__flushE));
    bufp->fullBit(oldp+62,(vlSelfRef.top__DOT__riscv__DOT__cu__DOT__zeroE));
    bufp->fullBit(oldp+63,(vlSelfRef.top__DOT__riscv__DOT__cu__DOT__pcsrcE));
    bufp->fullBit(oldp+64,(vlSelfRef.top__DOT__riscv__DOT__cu__DOT__alusrcE));
    bufp->fullCData(oldp+65,(vlSelfRef.top__DOT__riscv__DOT__cu__DOT__resultsrcE),2);
    bufp->fullCData(oldp+66,(vlSelfRef.top__DOT__riscv__DOT__cu__DOT__alucontrolE),3);
    bufp->fullBit(oldp+67,(vlSelfRef.top__DOT__riscv__DOT__cu__DOT__regwriteM));
    bufp->fullBit(oldp+68,(vlSelfRef.top__DOT__riscv__DOT__cu__DOT__memwriteM));
    bufp->fullBit(oldp+69,(vlSelfRef.top__DOT__riscv__DOT__cu__DOT__regwriteW));
    bufp->fullCData(oldp+70,(vlSelfRef.top__DOT__riscv__DOT__cu__DOT__resultsrcW),2);
    bufp->fullCData(oldp+71,(vlSelfRef.top__DOT__riscv__DOT__cu__DOT__aluop),2);
    bufp->fullBit(oldp+72,(vlSelfRef.top__DOT__riscv__DOT__cu__DOT__regwriteD));
    bufp->fullCData(oldp+73,(vlSelfRef.top__DOT__riscv__DOT__cu__DOT__resultsrcD),2);
    bufp->fullBit(oldp+74,(vlSelfRef.top__DOT__riscv__DOT__cu__DOT__memwriteD));
    bufp->fullBit(oldp+75,(vlSelfRef.top__DOT__riscv__DOT__cu__DOT__jumpD));
    bufp->fullBit(oldp+76,(vlSelfRef.top__DOT__riscv__DOT__cu__DOT__branchD));
    bufp->fullCData(oldp+77,(vlSelfRef.top__DOT__riscv__DOT__cu__DOT__alucontrolD),3);
    bufp->fullBit(oldp+78,(vlSelfRef.top__DOT__riscv__DOT__cu__DOT__alusrcD));
    bufp->fullBit(oldp+79,(vlSelfRef.top__DOT__riscv__DOT__cu__DOT__regwriteE));
    bufp->fullBit(oldp+80,(vlSelfRef.top__DOT__riscv__DOT__cu__DOT__memwriteE));
    bufp->fullBit(oldp+81,(vlSelfRef.top__DOT__riscv__DOT__cu__DOT__jumpE));
    bufp->fullBit(oldp+82,(vlSelfRef.top__DOT__riscv__DOT__cu__DOT__branchE));
    bufp->fullCData(oldp+83,(vlSelfRef.top__DOT__riscv__DOT__cu__DOT__immsrcE),2);
    bufp->fullCData(oldp+84,(vlSelfRef.top__DOT__riscv__DOT__cu__DOT__resultsrcM),2);
    bufp->fullBit(oldp+85,(vlSelfRef.top__DOT__riscv__DOT__cu__DOT__ad__DOT__opb5));
    bufp->fullCData(oldp+86,(vlSelfRef.top__DOT__riscv__DOT__cu__DOT__ad__DOT__funct3),3);
    bufp->fullBit(oldp+87,(vlSelfRef.top__DOT__riscv__DOT__cu__DOT__ad__DOT__funct7b5));
    bufp->fullCData(oldp+88,(vlSelfRef.top__DOT__riscv__DOT__cu__DOT__ad__DOT__aluop),2);
    bufp->fullCData(oldp+89,(vlSelfRef.top__DOT__riscv__DOT__cu__DOT__ad__DOT__alucontrol),3);
    bufp->fullBit(oldp+90,(vlSelfRef.top__DOT__riscv__DOT__cu__DOT__ad__DOT__rsub));
    bufp->fullCData(oldp+91,(vlSelfRef.top__DOT__riscv__DOT__cu__DOT__md__DOT__op),7);
    bufp->fullCData(oldp+92,(vlSelfRef.top__DOT__riscv__DOT__cu__DOT__md__DOT__resultsrc),2);
    bufp->fullBit(oldp+93,(vlSelfRef.top__DOT__riscv__DOT__cu__DOT__md__DOT__regwrite));
    bufp->fullBit(oldp+94,(vlSelfRef.top__DOT__riscv__DOT__cu__DOT__md__DOT__memwrite));
    bufp->fullBit(oldp+95,(vlSelfRef.top__DOT__riscv__DOT__cu__DOT__md__DOT__jump));
    bufp->fullBit(oldp+96,(vlSelfRef.top__DOT__riscv__DOT__cu__DOT__md__DOT__branch));
    bufp->fullBit(oldp+97,(vlSelfRef.top__DOT__riscv__DOT__cu__DOT__md__DOT__alusrc));
    bufp->fullCData(oldp+98,(vlSelfRef.top__DOT__riscv__DOT__cu__DOT__md__DOT__immsrc),2);
    bufp->fullCData(oldp+99,(vlSelfRef.top__DOT__riscv__DOT__cu__DOT__md__DOT__aluop),2);
    bufp->fullSData(oldp+100,(vlSelfRef.top__DOT__riscv__DOT__cu__DOT__md__DOT__controlsig),11);
    bufp->fullBit(oldp+101,(vlSelfRef.top__DOT__riscv__DOT__cu__DOT__regE__DOT__clk));
    bufp->fullBit(oldp+102,(vlSelfRef.top__DOT__riscv__DOT__cu__DOT__regE__DOT__rst));
    bufp->fullBit(oldp+103,(vlSelfRef.top__DOT__riscv__DOT__cu__DOT__regE__DOT__clear));
    bufp->fullSData(oldp+104,(vlSelfRef.top__DOT__riscv__DOT__cu__DOT__regE__DOT__d),10);
    bufp->fullSData(oldp+105,(vlSelfRef.top__DOT__riscv__DOT__cu__DOT__regE__DOT__q),10);
    bufp->fullBit(oldp+106,(vlSelfRef.top__DOT__riscv__DOT__cu__DOT__regM__DOT__clk));
    bufp->fullBit(oldp+107,(vlSelfRef.top__DOT__riscv__DOT__cu__DOT__regM__DOT__rst));
    bufp->fullCData(oldp+108,(vlSelfRef.top__DOT__riscv__DOT__cu__DOT__regM__DOT__d),4);
    bufp->fullCData(oldp+109,(vlSelfRef.top__DOT__riscv__DOT__cu__DOT__regM__DOT__q),4);
    bufp->fullBit(oldp+110,(vlSelfRef.top__DOT__riscv__DOT__cu__DOT__regW__DOT__clk));
    bufp->fullBit(oldp+111,(vlSelfRef.top__DOT__riscv__DOT__cu__DOT__regW__DOT__rst));
    bufp->fullCData(oldp+112,(vlSelfRef.top__DOT__riscv__DOT__cu__DOT__regW__DOT__d),3);
    bufp->fullCData(oldp+113,(vlSelfRef.top__DOT__riscv__DOT__cu__DOT__regW__DOT__q),3);
    bufp->fullBit(oldp+114,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__clk));
    bufp->fullBit(oldp+115,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__rst));
    bufp->fullBit(oldp+116,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__pcsrcE));
    bufp->fullBit(oldp+117,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__stallF));
    bufp->fullIData(oldp+118,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__instrF),32);
    bufp->fullIData(oldp+119,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__pcF),32);
    bufp->fullCData(oldp+120,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__immsrcD),2);
    bufp->fullBit(oldp+121,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__stallD));
    bufp->fullBit(oldp+122,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__flushD));
    bufp->fullBit(oldp+123,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__regwriteW));
    bufp->fullCData(oldp+124,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__op),7);
    bufp->fullCData(oldp+125,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__funct3),3);
    bufp->fullBit(oldp+126,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__funct7b5));
    bufp->fullCData(oldp+127,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__rs1D),5);
    bufp->fullCData(oldp+128,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__rs2D),5);
    bufp->fullBit(oldp+129,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__flushE));
    bufp->fullCData(oldp+130,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__forwardAE),2);
    bufp->fullCData(oldp+131,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__forwardBE),2);
    bufp->fullCData(oldp+132,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__alucontrolE),3);
    bufp->fullBit(oldp+133,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__alusrcE));
    bufp->fullCData(oldp+134,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__rs1E),5);
    bufp->fullCData(oldp+135,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__rs2E),5);
    bufp->fullCData(oldp+136,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__rdE),5);
    bufp->fullBit(oldp+137,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__zeroE));
    bufp->fullIData(oldp+138,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__readdataM),32);
    bufp->fullIData(oldp+139,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__aluresultM),32);
    bufp->fullIData(oldp+140,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__writedataM),32);
    bufp->fullCData(oldp+141,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__rdM),5);
    bufp->fullCData(oldp+142,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__resultsrcW),2);
    bufp->fullCData(oldp+143,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__rdW),5);
    bufp->fullIData(oldp+144,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__pcnextF),32);
    bufp->fullIData(oldp+145,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__pcplus4F),32);
    bufp->fullIData(oldp+146,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__instrD),32);
    bufp->fullIData(oldp+147,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__rd1D),32);
    bufp->fullIData(oldp+148,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__rd2D),32);
    bufp->fullCData(oldp+149,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__rdD),5);
    bufp->fullIData(oldp+150,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__pcD),32);
    bufp->fullIData(oldp+151,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__immextD),32);
    bufp->fullIData(oldp+152,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__pcplus4D),32);
    bufp->fullIData(oldp+153,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__rd1E),32);
    bufp->fullIData(oldp+154,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__rd2E),32);
    bufp->fullIData(oldp+155,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__pcE),32);
    bufp->fullIData(oldp+156,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__immextE),32);
    bufp->fullIData(oldp+157,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__pcplus4E),32);
    bufp->fullIData(oldp+158,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__srcaE),32);
    bufp->fullIData(oldp+159,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__srcbE),32);
    bufp->fullIData(oldp+160,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__fmuxbout),32);
    bufp->fullIData(oldp+161,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__writedataE),32);
    bufp->fullIData(oldp+162,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__pctargetE),32);
    bufp->fullIData(oldp+163,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__aluresultE),32);
    bufp->fullIData(oldp+164,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__pcplus4M),32);
    bufp->fullIData(oldp+165,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__aluresultW),32);
    bufp->fullIData(oldp+166,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__readdataW),32);
    bufp->fullIData(oldp+167,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__pcplus4W),32);
    bufp->fullIData(oldp+168,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__resultW),32);
    bufp->fullIData(oldp+169,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__adderE__DOT__a),32);
    bufp->fullIData(oldp+170,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__adderE__DOT__b),32);
    bufp->fullIData(oldp+171,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__adderE__DOT__y),32);
    bufp->fullIData(oldp+172,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__adderF__DOT__a),32);
    bufp->fullIData(oldp+173,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__adderF__DOT__b),32);
    bufp->fullIData(oldp+174,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__adderF__DOT__y),32);
    bufp->fullIData(oldp+175,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__alu__DOT__a),32);
    bufp->fullIData(oldp+176,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__alu__DOT__b),32);
    bufp->fullCData(oldp+177,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__alu__DOT__f),3);
    bufp->fullIData(oldp+178,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__alu__DOT__y),32);
    bufp->fullBit(oldp+179,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__alu__DOT__zero));
    bufp->fullIData(oldp+180,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__alumux__DOT__a),32);
    bufp->fullIData(oldp+181,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__alumux__DOT__b),32);
    bufp->fullBit(oldp+182,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__alumux__DOT__sel));
    bufp->fullIData(oldp+183,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__alumux__DOT__y),32);
    bufp->fullIData(oldp+184,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__ext__DOT__instr),25);
    bufp->fullCData(oldp+185,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__ext__DOT__immsrc),2);
    bufp->fullIData(oldp+186,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__ext__DOT__immext),32);
    bufp->fullIData(oldp+187,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__fmuxa__DOT__a),32);
    bufp->fullIData(oldp+188,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__fmuxa__DOT__b),32);
    bufp->fullIData(oldp+189,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__fmuxa__DOT__c),32);
    bufp->fullCData(oldp+190,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__fmuxa__DOT__sel),2);
    bufp->fullIData(oldp+191,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__fmuxa__DOT__y),32);
    bufp->fullIData(oldp+192,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__fmuxb__DOT__a),32);
    bufp->fullIData(oldp+193,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__fmuxb__DOT__b),32);
    bufp->fullIData(oldp+194,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__fmuxb__DOT__c),32);
    bufp->fullCData(oldp+195,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__fmuxb__DOT__sel),2);
    bufp->fullIData(oldp+196,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__fmuxb__DOT__y),32);
    bufp->fullBit(oldp+197,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__pc__DOT__clk));
    bufp->fullBit(oldp+198,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__pc__DOT__rst));
    bufp->fullBit(oldp+199,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__pc__DOT__en));
    bufp->fullIData(oldp+200,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__pc__DOT__d),32);
    bufp->fullIData(oldp+201,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__pc__DOT__q),32);
    bufp->fullIData(oldp+202,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__pcmux__DOT__a),32);
    bufp->fullIData(oldp+203,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__pcmux__DOT__b),32);
    bufp->fullBit(oldp+204,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__pcmux__DOT__sel));
    bufp->fullIData(oldp+205,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__pcmux__DOT__y),32);
    bufp->fullBit(oldp+206,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__regD1__DOT__clk));
    bufp->fullBit(oldp+207,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__regD1__DOT__rst));
    bufp->fullBit(oldp+208,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__regD1__DOT__en));
    bufp->fullBit(oldp+209,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__regD1__DOT__clear));
    bufp->fullIData(oldp+210,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__regD1__DOT__d),32);
    bufp->fullIData(oldp+211,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__regD1__DOT__q),32);
    bufp->fullBit(oldp+212,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__regD2__DOT__clk));
    bufp->fullBit(oldp+213,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__regD2__DOT__rst));
    bufp->fullBit(oldp+214,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__regD2__DOT__en));
    bufp->fullBit(oldp+215,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__regD2__DOT__clear));
    bufp->fullIData(oldp+216,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__regD2__DOT__d),32);
    bufp->fullIData(oldp+217,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__regD2__DOT__q),32);
    bufp->fullBit(oldp+218,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__regD3__DOT__clk));
    bufp->fullBit(oldp+219,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__regD3__DOT__rst));
    bufp->fullBit(oldp+220,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__regD3__DOT__en));
    bufp->fullBit(oldp+221,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__regD3__DOT__clear));
    bufp->fullIData(oldp+222,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__regD3__DOT__d),32);
    bufp->fullIData(oldp+223,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__regD3__DOT__q),32);
    bufp->fullBit(oldp+224,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__regE1__DOT__clk));
    bufp->fullBit(oldp+225,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__regE1__DOT__rst));
    bufp->fullBit(oldp+226,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__regE1__DOT__clear));
    bufp->fullIData(oldp+227,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__regE1__DOT__d),32);
    bufp->fullIData(oldp+228,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__regE1__DOT__q),32);
    bufp->fullBit(oldp+229,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__regE2__DOT__clk));
    bufp->fullBit(oldp+230,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__regE2__DOT__rst));
    bufp->fullBit(oldp+231,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__regE2__DOT__clear));
    bufp->fullIData(oldp+232,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__regE2__DOT__d),32);
    bufp->fullIData(oldp+233,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__regE2__DOT__q),32);
    bufp->fullBit(oldp+234,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__regE3__DOT__clk));
    bufp->fullBit(oldp+235,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__regE3__DOT__rst));
    bufp->fullBit(oldp+236,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__regE3__DOT__clear));
    bufp->fullIData(oldp+237,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__regE3__DOT__d),32);
    bufp->fullIData(oldp+238,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__regE3__DOT__q),32);
    bufp->fullBit(oldp+239,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__regE4__DOT__clk));
    bufp->fullBit(oldp+240,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__regE4__DOT__rst));
    bufp->fullBit(oldp+241,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__regE4__DOT__clear));
    bufp->fullCData(oldp+242,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__regE4__DOT__d),5);
    bufp->fullCData(oldp+243,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__regE4__DOT__q),5);
    bufp->fullBit(oldp+244,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__regE5__DOT__clk));
    bufp->fullBit(oldp+245,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__regE5__DOT__rst));
    bufp->fullBit(oldp+246,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__regE5__DOT__clear));
    bufp->fullCData(oldp+247,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__regE5__DOT__d),5);
    bufp->fullCData(oldp+248,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__regE5__DOT__q),5);
    bufp->fullBit(oldp+249,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__regE6__DOT__clk));
    bufp->fullBit(oldp+250,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__regE6__DOT__rst));
    bufp->fullBit(oldp+251,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__regE6__DOT__clear));
    bufp->fullCData(oldp+252,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__regE6__DOT__d),5);
    bufp->fullCData(oldp+253,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__regE6__DOT__q),5);
    bufp->fullBit(oldp+254,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__regE7__DOT__clk));
    bufp->fullBit(oldp+255,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__regE7__DOT__rst));
    bufp->fullBit(oldp+256,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__regE7__DOT__clear));
    bufp->fullIData(oldp+257,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__regE7__DOT__d),32);
    bufp->fullIData(oldp+258,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__regE7__DOT__q),32);
    bufp->fullBit(oldp+259,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__regE8__DOT__clk));
    bufp->fullBit(oldp+260,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__regE8__DOT__rst));
    bufp->fullBit(oldp+261,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__regE8__DOT__clear));
    bufp->fullIData(oldp+262,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__regE8__DOT__d),32);
    bufp->fullIData(oldp+263,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__regE8__DOT__q),32);
    bufp->fullBit(oldp+264,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__regM1__DOT__clk));
    bufp->fullBit(oldp+265,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__regM1__DOT__rst));
    bufp->fullIData(oldp+266,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__regM1__DOT__d),32);
    bufp->fullIData(oldp+267,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__regM1__DOT__q),32);
    bufp->fullBit(oldp+268,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__regM2__DOT__clk));
    bufp->fullBit(oldp+269,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__regM2__DOT__rst));
    bufp->fullIData(oldp+270,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__regM2__DOT__d),32);
    bufp->fullIData(oldp+271,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__regM2__DOT__q),32);
    bufp->fullBit(oldp+272,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__regM3__DOT__clk));
    bufp->fullBit(oldp+273,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__regM3__DOT__rst));
    bufp->fullCData(oldp+274,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__regM3__DOT__d),5);
    bufp->fullCData(oldp+275,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__regM3__DOT__q),5);
    bufp->fullBit(oldp+276,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__regM4__DOT__clk));
    bufp->fullBit(oldp+277,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__regM4__DOT__rst));
    bufp->fullIData(oldp+278,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__regM4__DOT__d),32);
    bufp->fullIData(oldp+279,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__regM4__DOT__q),32);
    bufp->fullBit(oldp+280,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__regW1__DOT__clk));
    bufp->fullBit(oldp+281,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__regW1__DOT__rst));
    bufp->fullIData(oldp+282,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__regW1__DOT__d),32);
    bufp->fullIData(oldp+283,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__regW1__DOT__q),32);
    bufp->fullBit(oldp+284,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__regW2__DOT__clk));
    bufp->fullBit(oldp+285,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__regW2__DOT__rst));
    bufp->fullIData(oldp+286,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__regW2__DOT__d),32);
    bufp->fullIData(oldp+287,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__regW2__DOT__q),32);
    bufp->fullBit(oldp+288,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__regW3__DOT__clk));
    bufp->fullBit(oldp+289,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__regW3__DOT__rst));
    bufp->fullCData(oldp+290,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__regW3__DOT__d),5);
    bufp->fullCData(oldp+291,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__regW3__DOT__q),5);
    bufp->fullBit(oldp+292,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__regW4__DOT__clk));
    bufp->fullBit(oldp+293,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__regW4__DOT__rst));
    bufp->fullIData(oldp+294,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__regW4__DOT__d),32);
    bufp->fullIData(oldp+295,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__regW4__DOT__q),32);
    bufp->fullIData(oldp+296,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__resultmux__DOT__a),32);
    bufp->fullIData(oldp+297,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__resultmux__DOT__b),32);
    bufp->fullIData(oldp+298,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__resultmux__DOT__c),32);
    bufp->fullCData(oldp+299,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__resultmux__DOT__sel),2);
    bufp->fullIData(oldp+300,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__resultmux__DOT__y),32);
    bufp->fullBit(oldp+301,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__rf__DOT__clk));
    bufp->fullBit(oldp+302,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__rf__DOT__we3));
    bufp->fullCData(oldp+303,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__rf__DOT__ra1),5);
    bufp->fullCData(oldp+304,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__rf__DOT__ra2),5);
    bufp->fullCData(oldp+305,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__rf__DOT__wa3),5);
    bufp->fullIData(oldp+306,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__rf__DOT__wd3),32);
    bufp->fullIData(oldp+307,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__rf__DOT__rd1),32);
    bufp->fullIData(oldp+308,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__rf__DOT__rd2),32);
    bufp->fullIData(oldp+309,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__rf__DOT__rf[0]),32);
    bufp->fullIData(oldp+310,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__rf__DOT__rf[1]),32);
    bufp->fullIData(oldp+311,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__rf__DOT__rf[2]),32);
    bufp->fullIData(oldp+312,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__rf__DOT__rf[3]),32);
    bufp->fullIData(oldp+313,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__rf__DOT__rf[4]),32);
    bufp->fullIData(oldp+314,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__rf__DOT__rf[5]),32);
    bufp->fullIData(oldp+315,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__rf__DOT__rf[6]),32);
    bufp->fullIData(oldp+316,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__rf__DOT__rf[7]),32);
    bufp->fullIData(oldp+317,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__rf__DOT__rf[8]),32);
    bufp->fullIData(oldp+318,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__rf__DOT__rf[9]),32);
    bufp->fullIData(oldp+319,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__rf__DOT__rf[10]),32);
    bufp->fullIData(oldp+320,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__rf__DOT__rf[11]),32);
    bufp->fullIData(oldp+321,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__rf__DOT__rf[12]),32);
    bufp->fullIData(oldp+322,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__rf__DOT__rf[13]),32);
    bufp->fullIData(oldp+323,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__rf__DOT__rf[14]),32);
    bufp->fullIData(oldp+324,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__rf__DOT__rf[15]),32);
    bufp->fullIData(oldp+325,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__rf__DOT__rf[16]),32);
    bufp->fullIData(oldp+326,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__rf__DOT__rf[17]),32);
    bufp->fullIData(oldp+327,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__rf__DOT__rf[18]),32);
    bufp->fullIData(oldp+328,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__rf__DOT__rf[19]),32);
    bufp->fullIData(oldp+329,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__rf__DOT__rf[20]),32);
    bufp->fullIData(oldp+330,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__rf__DOT__rf[21]),32);
    bufp->fullIData(oldp+331,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__rf__DOT__rf[22]),32);
    bufp->fullIData(oldp+332,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__rf__DOT__rf[23]),32);
    bufp->fullIData(oldp+333,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__rf__DOT__rf[24]),32);
    bufp->fullIData(oldp+334,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__rf__DOT__rf[25]),32);
    bufp->fullIData(oldp+335,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__rf__DOT__rf[26]),32);
    bufp->fullIData(oldp+336,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__rf__DOT__rf[27]),32);
    bufp->fullIData(oldp+337,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__rf__DOT__rf[28]),32);
    bufp->fullIData(oldp+338,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__rf__DOT__rf[29]),32);
    bufp->fullIData(oldp+339,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__rf__DOT__rf[30]),32);
    bufp->fullIData(oldp+340,(vlSelfRef.top__DOT__riscv__DOT__dp__DOT__rf__DOT__rf[31]),32);
    bufp->fullCData(oldp+341,(vlSelfRef.top__DOT__riscv__DOT__hu__DOT__rs1D),5);
    bufp->fullCData(oldp+342,(vlSelfRef.top__DOT__riscv__DOT__hu__DOT__rs2D),5);
    bufp->fullCData(oldp+343,(vlSelfRef.top__DOT__riscv__DOT__hu__DOT__rs1E),5);
    bufp->fullCData(oldp+344,(vlSelfRef.top__DOT__riscv__DOT__hu__DOT__rs2E),5);
    bufp->fullCData(oldp+345,(vlSelfRef.top__DOT__riscv__DOT__hu__DOT__rdE),5);
    bufp->fullCData(oldp+346,(vlSelfRef.top__DOT__riscv__DOT__hu__DOT__resultsrcE),2);
    bufp->fullBit(oldp+347,(vlSelfRef.top__DOT__riscv__DOT__hu__DOT__pcsrcE));
    bufp->fullCData(oldp+348,(vlSelfRef.top__DOT__riscv__DOT__hu__DOT__rdM),5);
    bufp->fullBit(oldp+349,(vlSelfRef.top__DOT__riscv__DOT__hu__DOT__regwriteM));
    bufp->fullCData(oldp+350,(vlSelfRef.top__DOT__riscv__DOT__hu__DOT__rdW),5);
    bufp->fullBit(oldp+351,(vlSelfRef.top__DOT__riscv__DOT__hu__DOT__regwriteW));
    bufp->fullBit(oldp+352,(vlSelfRef.top__DOT__riscv__DOT__hu__DOT__stallF));
    bufp->fullBit(oldp+353,(vlSelfRef.top__DOT__riscv__DOT__hu__DOT__stallD));
    bufp->fullBit(oldp+354,(vlSelfRef.top__DOT__riscv__DOT__hu__DOT__flushD));
    bufp->fullBit(oldp+355,(vlSelfRef.top__DOT__riscv__DOT__hu__DOT__flushE));
    bufp->fullCData(oldp+356,(vlSelfRef.top__DOT__riscv__DOT__hu__DOT__forwardAE),2);
    bufp->fullCData(oldp+357,(vlSelfRef.top__DOT__riscv__DOT__hu__DOT__forwardBE),2);
    bufp->fullBit(oldp+358,(vlSelfRef.top__DOT__riscv__DOT__hu__DOT__lwstall));
}
